### ISSUE TITLE
More space between headerbar and canvas in Nautilus

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#109]
![screenshot-from-2018-01-18-16-23-12](https://user-images.githubusercontent.com/3986894/35419338-b54eed54-0237-11e8-9378-d47d648648de.gif)

**Comment by madsrh** [comment]
The padding also moves the scrollbar. It might be the wrong container the padding is added to.

**Comment by clobrano** [comment]
> The padding also moves the scrollbar. It might be the wrong container the padding is added to.

Confirmed, I am going to fix this in #405

**Comment by madsrh** [comment]
@clobrano This isn't fix with #405. This (109) issue is still present, but if we can't have both, we can discard this padding issue.

**Comment by clobrano** [comment]
Uhm, weird it should, I actually kept a little margin between scrollbar and top view, maybe you're seeing this one?

**Comment by madsrh** [comment]
Is that the 2px? I should still look like [this ](https://user-images.githubusercontent.com/3986894/35419338-b54eed54-0237-11e8-9378-d47d648648de.gif)- with and without scrollbars. And if the scrollbars are there they should start at the top, right? 🤔

**Comment by clobrano** [comment]
:man_facepalming: damn you're right

**Comment by clobrano** [comment]
Unfortunately, scrolledwindows is inside the container we want to move down, so scrollbar will always move with it

**Comment by clobrano** [comment]
Closing this now, until upstream issue goes its way
