### ISSUE TITLE
Scale's slider gets thicker when in fine-tune

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#113]
When keep pressing on the scale's slider it acquire the "fine-tune" style class and gets visibly thicker

![image](https://user-images.githubusercontent.com/2883614/35474007-9c52b482-0388-11e8-9334-819c03e4a0af.png)

normal size is below
![image](https://user-images.githubusercontent.com/2883614/35474020-af8b2282-0388-11e8-9a0d-a8257b7ece98.png)

**Comment by godlyranchdressing** [comment]
That's on purpose and is a carry over from Adwaita. Should we make it smaller instead?

**Comment by clobrano** [comment]
I guessed that, but since we make the initial bar smaller, the increment looks to much to me. What do you think about replicating the same percentage increment Adwaita has?

**Comment by clobrano** [comment]
I understand is a very little change, but what do you think about this?

![image](https://user-images.githubusercontent.com/2883614/35650912-1223b3c0-06de-11e8-8db5-3abd84225afe.png)

**Comment by nana-4** [comment]
The _change (-1px)_ looks so good to me. 😃

**Comment by galgalesh** [comment]
Wow, I had no idea this feature existed xD
