### ISSUE TITLE
Libreoffice menu hover is hard to spot

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#115]
Here's a comparison with Ambiance where I'm hovering over Calc
![li](https://user-images.githubusercontent.com/3986894/35486726-8a7ef730-0472-11e8-8afb-1d37b0d6a076.gif)

**Comment by madsrh** [comment]
Also, when launching LibleOffice the splash screen has an orange progressbar. Shouldn't that be blue? I don't know if this is outside the theme, so I haven't created an issue.

**Comment by fitojb** [comment]
> Also, when launching LibleOffice the splash screen has an orange progressbar. Shouldn't that be blue? I don't know if this is outside the theme, so I haven't created an issue.

Please file a bug against the `libreoffice` package on Launchpad. See also [LP: #1026059](https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1026059).

**Comment by clobrano** [comment]
@madsrh could you try installing first gtk2-engines-pixbuf?

**Comment by madsrh** [comment]
@clobrano gtk2-engines-pixbuf is already installed.

**Comment by fitojb** [comment]
#115 has fixed this (LibreOffice on Ubuntu, by default, uses GTK+ 3).

**Comment by clobrano** [comment]
Closing this as per @fitojb comment
