### ISSUE TITLE
Menu bars have no hover effect

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#124]
Check Terminal for example.

Proposed fix: use the brighter white for text (which is currently used when clicked) on hover (but without the orange underline)

**Comment by godlyranchdressing** [comment]
I could be wrong, but I don't think it's possible. The :hover pseudo-class styling is used when you click on a menubar item, not when you hover over it.

**Comment by clobrano** [comment]
>  The :hover pseudo-class styling is used when you click on a menubar item, not when you hover over it. There's no hover effect for menubar items in any other theme.

Just confirmed with gtk inspector
