### ISSUE TITLE
Active sidebar element shouldn't have hover effect

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#125]
An active sidebar element (orange state) should have no hover effect as this darkens the orange to be weirdly brownish and has no necessary meaning. Although it can be clicked technically, the element is already active and clicking it has no further consequences. It has no hover on inactive windows.

See Files/Nautilus, Settings, Tweaks for example.

**Comment by madsrh** [comment]
@ya-d This behavior is carried over from Adwaita I believe. +1 for **no hover on selected item**. Ambiance (and also OSX) does this too.
