### ISSUE TITLE
Suru style user icon in GDM

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#129]
Also mentioned https://github.com/Ubuntu/gnome-shell-communitheme/issues/24

Use the Suru style user login icon:
https://github.com/CanonicalLtd/desktop-design/blob/master/User%20icon/user-icon.svg

**Comment by clobrano** [comment]
Sorry for the stupid question, but I can't find from where the current user-icon comes in the source code

**Comment by Feichtmeier** [comment]
I found an indication on how to change the icon in this link:

https://mike632t.wordpress.com/2016/05/28/gnome-3-customizing-the-login-screen/

GDM settings can be changed here: 
/usr/share/gdm/greeter.dconf-defaults

Though this sounds more like a hack instead of a default installation but maybe it helps

**Comment by madsrh** [comment]
@Feichtmeier It's not _how_ to change the icon, but where to find the icon.

@clobrano I've PM [Sam Hewitt](https://github.com/snwh) a week ago and still waiting for him to reply.

**Comment by clobrano** [comment]
> @clobrano I've PM Sam Hewitt a week ago and still waiting for him to reply.

Thanks a lot 😉 @madsrh

**Comment by madsrh** [comment]
@clobrano can we simply use the .svg from my first comment and include the file for now or is that considered a bad solution? Later, when the icon theme is shipped, we can switch to that.

I've also send an email in the meantime, but still no word from SH :/

**Comment by clobrano** [comment]
@madsrh no problem in using your svg, it's still unclear to me where the make the change. I had a look at what @Feichtmeier proposed, but that wouldn't work

**Comment by nana-4** [comment]
I guess this issue should be reassigned to `gnome-shell-communitheme` repo.

By default, `prefix/icon-name/scalable/status/avatar-default-symbolic.svg` is used for the icon:
https://github.com/GNOME/gnome-shell/blob/d903978937499a365d5d8586b83eb7323b21efd0/js/ui/userWidget.js#L60

In SCSS/CSS, it can be styled by `.framed-user-icon`:
https://github.com/Ubuntu/gnome-shell-communitheme/blob/3a438006b9adc1e6e162c102ddfbbc4896ea596f/communitheme/gnome-shell-sass/_common.scss#L1780

**Comment by clobrano** [comment]
awesome @nana-4! I'll have a look a it

**Comment by nana-4** [comment]
I tried using the SVG on my local branch, and it seems to work well.
So I will send a PR. ;)

**Comment by clobrano** [comment]
Closing since this is managed in gnome-shell-communitheme
