### ISSUE TITLE
Hover effect darkens window close button

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#137]
I just noticed that no other button but "close window" changes colors on hover (see LibreOffice for many colorful ones; any gnome app for white monochrome). If you hover any button the hover effect is *behind* the icon so colors (including whites) stay the same. If you hover over the close button its icon darkens (orange circle as well as white x) as the overlay sits *in front* of the icon.

In backdrop windows the muted white brightens on hover for window controls. The grey circle of the close buttons remains the same color/brightness though.

**Comment by clobrano** [comment]
Moreover in backdrop, window controls border are darker than headerbar color.

This part of the fix depends on #123, If we decide in favor of hover effect in backdrop state or not
