### ISSUE TITLE
Tooltips are very big

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#140]
Go to Files/Nautilus and hover over any sidebar element. Tooltips are bigger then the entries itself and as tall as the header bar.

Maybe use #139 as a reference and even consider using a smaller font size (like explanations for text labels).

![tooltips-big](https://user-images.githubusercontent.com/30781876/35696514-07eb0b10-0788-11e8-91ea-4e2c063a76f4.png)

**Comment by nana-4** [comment]
I also feel tooltips are too big. I will send a PR to reduce the size.

However, using a smaller font size (`font-size: smaller`) may look the font too small (depending on the root font size, though).

| current | my proposal | my proposal + `smaller` font size |
|:-:|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/9556384/35747173-ab5443b6-088c-11e8-945d-9ee69cc5408a.png) | ![image](https://user-images.githubusercontent.com/9556384/35747175-af3e9f8a-088c-11e8-9a52-b23c60d629eb.png) | ![image](https://user-images.githubusercontent.com/9556384/35747182-b3ceefa0-088c-11e8-9a05-b1fb3cc22ae4.png) |
