### ISSUE TITLE
GTK Stack Switcher and GTK Button Box - low contrast on foreground font color

### ISSUE THREAD

**Issue by Feichtmeier** [Ubuntu/gtk-communitheme#141]
I first though these would be the same GTK element but they are not.

On gnome to do (and prbly more gnome apps) the stack switcher font foreground contrast is too low.
In the gnome software headerbar, there is something different, I think it is called "button box", with a wrong contrast. Best regards

![bildschirmfoto-20180202091404-1252x895](https://user-images.githubusercontent.com/15329494/35723474-ad315f4e-07fa-11e8-86d5-69231a8c5990.png)
![bildschirmfoto-20180202091947-1779x852](https://user-images.githubusercontent.com/15329494/35723472-acfd0956-07fa-11e8-9620-b0851b27a2a4.png)
![bildschirmfoto-20180202091429-1098x763](https://user-images.githubusercontent.com/15329494/35723473-ad154c14-07fa-11e8-9795-25decdbf5680.png)
![bildschirmfoto-20180202092055-1409x763](https://user-images.githubusercontent.com/15329494/35723471-acb6d800-07fa-11e8-9131-4b46bbd1151a.png)

**Comment by slackmate** [comment]
I have also come across the very same issue in Gnome System Monitor as it also uses `Gtk.StackSwitcher`.
