### ISSUE TITLE
Step under activities on top bar 

### ISSUE THREAD

**Issue by jasonflindt** [Ubuntu/gtk-communitheme#144]
In the community session there is a step under the activities text . It only in the dedicated community theme. https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/371?u=jasonflindt 
After more investigation i found that the step is the top of the dock . Its a dark line that will slide in in you enable auto hide

**Comment by jasonflindt** [comment]
And the gap between a maximised window and the top of the dock is still persisting . Once again these issues are only in the community session and no other session affected even when the community theme is applied.

**Comment by madsrh** [comment]
@clobrano I just did a fresh install in a vm and I'm seeing this too.

Could it be releated to [the gray separator line](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/247)?

**Comment by clobrano** [comment]
@madsrh not sure, maybe @godlyranchdressing knows it better, however it's really important to know that I can reproduce it on a VM, thanks a lot!

**Comment by clobrano** [comment]
Didn't see this was in gtk-communitheme. I'm going to link this issue on gnome-shell-communitheme project and close this issue here.
