### ISSUE TITLE
Electron - menu bar hardly visible - low contrast - grey on black

### ISSUE THREAD

**Issue by Feichtmeier** [Ubuntu/gtk-communitheme#148]
The new skype app uses electron and is a quiet good example:
- the menu bar has a very low contrast as you can see in the picture attached:

![bildschirmfoto von 2018-02-09 09-25-55](https://user-images.githubusercontent.com/15329494/36018377-d73d2b84-0d7b-11e8-863f-d5146a5616c4.png)

With ambiance the menu looks high contrasted:

![bildschirmfoto von 2018-02-09 09-41-36](https://user-images.githubusercontent.com/15329494/36018835-798ed940-0d7d-11e8-9c73-3cabb1c77a83.png)

Atom is also a good example, to show that it is not only a skype issue:

![bildschirmfoto von 2018-02-09 09-39-00](https://user-images.githubusercontent.com/15329494/36018722-1713e10c-0d7d-11e8-8ee0-d6a97e9fe042.png)

**Comment by Xyaneon** [comment]
Visual Studio Code is Electron-based as well, and also affected by this.

**Comment by clobrano** [comment]
It might be a long shot, but have you tried installing gtk2-engines-pixbuf?

**Comment by Feichtmeier** [comment]
Yes, with gtk2-engines-pixbuf the issue remains on all affected apps
