### ISSUE TITLE
Buttons in software center headerbar broken

### ISSUE THREAD

**Issue by galgalesh** [Ubuntu/gtk-communitheme#149]
@clobrano it seems I did miss an issue with your headerbar PR. The stackswitcher? buttons in the software center seem broken.

**backdrop**

![image](https://user-images.githubusercontent.com/1492981/36029554-fd2e22e4-0da3-11e8-8961-eaa71b5b425a.png)

**foreground**

![image](https://user-images.githubusercontent.com/1492981/36029565-0ae76d3c-0da4-11e8-97d8-0afe92808e0f.png)

**Comment by clobrano** [comment]
that's weird, this is mine
backdrop
![image](https://user-images.githubusercontent.com/2883614/36031803-47de6b8e-0dac-11e8-82f7-755a16a58651.png)

foreground
![image](https://user-images.githubusercontent.com/2883614/36031789-3c5ada2c-0dac-11e8-9c71-029a6b4eb111.png)

**Comment by galgalesh** [comment]
Hm, this seems fixed when I build from master. I guess the ppa will catch up soon.. Closing this for now.
