### ISSUE TITLE
In Nautilus List View moving through several items using arrow down key leaves a line between items

### ISSUE THREAD

**Issue by slackmate** [Ubuntu/gtk-communitheme#151]
In Nautilus when in List View moving through _several_ items in a downward direction using an arrow down key (⬇︎) an orange line is left behind at the bottom of the previously selected item. This is best illustrated with a screenshot.

![nautilus](https://user-images.githubusercontent.com/30923711/36060495-0253d0d2-0e4b-11e8-945d-353a345942a7.png)

**Comment by venorz** [comment]
I noticed that too
