### ISSUE TITLE
Rounded focus rect

### ISSUE THREAD

**Issue by CDrummond** [Ubuntu/gtk-communitheme#159]
Checkboxes, radios, and popover items have a square orange focus rectangle, perhaps this should be rounded to fit in with the rest of the theme?

**Comment by madsrh** [comment]
I see that there's already a PR from @godlyranchdressing - I'm going to post this image here anyway for reference and close the issue.
![image](https://user-images.githubusercontent.com/3986894/36208045-0c625990-1198-11e8-8903-d5bae77c4738.png)
