### ISSUE TITLE
"double titlebar" on apps with classic menubars

### ISSUE THREAD

**Issue by galgalesh** [ubuntu/gtk-communitheme#16]
The black line between the titlebar and menubar looks a little off to me.

Example: the terminal:

![image](https://user-images.githubusercontent.com/1492981/34580489-86317b50-f18d-11e7-981c-62c7d8674f81.png)

**Comment by didrocks** [comment]
+1
(also, the terminal background color is really disturbing to me with the default background, the contrast is high with it, and not really high with the text IMHO)

**Comment by clobrano** [comment]
I was trying to work on this, but couldn't find the definition of this element in both theme and gnome shell, does anyone know it?

**Comment by didrocks** [comment]
I would say it's either the top of the menu header or the gtkbox around it (from gtk/the app), or the bottom of server-side decoration (which is also in the gtk theme). @3v1n0, any hint?

**Comment by clobrano** [comment]
>  the bottom of server-side decoration

oh, thanks! I didn't think about that one

**Comment by galgalesh** [comment]
@didrocks the terminal color scheme is being discussed here: https://github.com/Ubuntu/gtk-communitheme/issues/29

I think that screenshot is Solarized dark

**Comment by didrocks** [comment]
Yep, just noticed it (catching up on history from old to new, including closed PR/issues ;)), thanks!

**Comment by 3v1n0** [comment]
Mh, could be related to the serverside decorations.... Keep in mind that changes to those doesn't apply without resetting g-s (I should actually fix this in mutter!), so better to use Xorg and `Alt+F2 -> r` for that

**Comment by clobrano** [comment]
I'll have a look at that, thanks!

**Comment by clobrano** [comment]
closed by #392
