### ISSUE TITLE
When clicking a button, orange selection focus flashes for a moment

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#161]
Can this be suppressed? Seems distracting to me (was not the case before latest update, if i remember correctly).

**Comment by clobrano** [comment]
@ya-d could you confirm that this happen on gtk2 application only? I cannot reproduce it on gtk-3-demo nor gtk3-widget-factory, but I'd like to be sure

**Comment by ya-d** [comment]
Thanks for looking into it! I'm afraid I can not reproduce the issue (as an issue) for now. It only occurs if keyboard focus is triggerd by pressing the Tab key and than buttons are clicked – but that seems less an issue than expected behavior I guess. The "flashing" is gone if I open a new window. I'm really sorry, I was under the impression it happens all the time.

![keybord focus](https://user-images.githubusercontent.com/30781876/36282033-0ac2abd6-12a0-11e8-9df2-97952c31e68a.gif)

**Comment by clobrano** [comment]
It's a tricky thing, I agree 😃 
This effect is due to the fact that a button can also be selected (:focus style class) using the keyboard. When one clicks with the mouse the button gets both the :focus and :active style classes. If we get rid of that, no one could see the selection using just the keyboard anymore.

**Comment by ya-d** [comment]
Absoluty fine, my mistake as I didn’t realize that I obviously triggered keyboard selection. I'll close this issue.

**Comment by ya-d** [comment]
PS: I now realize how my perception came to be. If you type in Text Editor this triggers "keyboard input mode" (without explicitly hitting the tab key) and activates keyboard focus states for buttons with their corresponding style classes.
