### ISSUE TITLE
Thin line between GtkRevealer in GtkFileChoserDialog is hard to see

### ISSUE THREAD

**Issue by Feichtmeier** [Ubuntu/gtk-communitheme#174]
I guess this css part comes from the NautilusPathBar theming.
This "same" line in a white version is now in the GtkFileChoserDialog, too.

![bildschirmfoto-20180215205828-1283x1005](https://user-images.githubusercontent.com/15329494/36336532-d82689e2-1388-11e8-8110-06503bb8cb34.png)
![bildschirmfoto-20180217021654-1494x973](https://user-images.githubusercontent.com/15329494/36336533-dbefd4e8-1388-11e8-96ce-549418e8f031.png)

Imho it is really hard to see - maybe it would be better to remove the thin line in nauiluspathbar & gtkrevealer again

**Comment by clobrano** [comment]
I guess you're right. I spotted this "brighter" version of the normal theme in other places too

**Comment by clobrano** [comment]
With the new stackswitcher (which is actually the older) the situation is now the one below

![image](https://user-images.githubusercontent.com/2883614/36376752-9286e038-1574-11e8-84cd-147740a868b3.png)

That is, slighly better, but the last separator between button and arrow persisted
