### ISSUE TITLE
Titlebar has a border and does not match other applications

### ISSUE THREAD

**Issue by themccallister** [Ubuntu/gtk-communitheme#176]
![image](https://user-images.githubusercontent.com/5354908/36344678-11b3e7f0-13ec-11e8-9116-7ad9b0b1fa2d.png)

When using the communitheme, I noticed a drastic border on Firefox and Chrome. Other applications do not have this border and it feels inconsistent. Is this intentional, or something that has not been noticed yet?

I don't mind making a PR, but I have no idea how to style anything related to Gnome/GTK.

_Also, unrelated to this issue, is there a shell theme for communitheme?_

**Comment by clobrano** [comment]
Hi @themccallister,
thanks for taking time to test and report 😉 

> When using the communitheme, I noticed a drastic border on Firefox and Chrome. Other applications do not have this border and it feels inconsistent. Is this intentional, or something that has not been noticed yet?

If you are talking about the border between titlebar and menubar, it has been reported already in issue #16 

> Also, unrelated to this issue, is there a shell theme for communitheme?

Yes again 😄 [Ubuntu/gnome-shell-communitheme](https://github.com/ubuntu/gnome-shell-communitheme)

**Comment by clobrano** [comment]
duplicate of #16

**Comment by themccallister** [comment]
Thanks, lets close this out then. Sorry for the dupe!

I do not see the theme as an option, I will make sure I read those docs on installation to make sure I did not miss anything. 

Also, I'm looking forward to running this fulltime, its a much better theme than the Pop!_OS and default Unity theme, so its very exciting to see this coming along!

Has there been any thought to a light variant of the theme?

**Comment by themccallister** [comment]
Closing

**Comment by clobrano** [comment]
> Has there been any thought to a light variant of the theme?

Not yet, we are totally focused on this variant only.
 
By the way, some people asked for a **dark** variant of this theme as well, I think that it is still to be discussed if this one is dark or light 😄 

There's a PPA for having the last update always available

Thanks for the feedback!
