### ISSUE TITLE
boxed hover effect on window control buttons

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#18]
This idea comes from [madsrh's mockup](http://madsrosendahl.dk/ubuntu/mockup6.html).

![box-hover-window-controls](https://user-images.githubusercontent.com/2883614/34611643-a57aa25e-f226-11e7-9471-3cbade26c54d.gif)

It requires background-images for control buttons, so it's not a high priority task

**Comment by madsrh** [comment]
But no circle on hover for min and max, right?

**Comment by clobrano** [comment]
No circles, correct

**Comment by godlyranchdressing** [comment]
I did some testing with this, but I decided to omit the boxed effect. It doesn't work without the white circle present in the mockup. Since the current buttons themselves rely on a circle effect when interacted with you end up with this double background color that looks like an error, too. 

Should we merge the changes or try with another design instead?

**Comment by clobrano** [comment]
Can you post a picture of the result?

**Comment by godlyranchdressing** [comment]
Sure.

Background-image lets us use larger buttons without the background-color taking up the full dimensions of the box which would look awkward:
![windowbuttons](https://user-images.githubusercontent.com/27529229/34908407-b27b30e6-f865-11e7-9eea-dbddd094fe2e.gif)

With the boxed effect, a 1:1 ratio would make the buttons too wide and the close button can't reach the edge of the headerbar unless we remove the headerbar's padding:
![windowbuttonsboxed](https://user-images.githubusercontent.com/27529229/34908453-281296e6-f866-11e7-819f-4f1da4830fe3.gif)

**Comment by godlyranchdressing** [comment]
I thought about it. We could make them look and work like regular headerbar buttons, but then the orange circle will need to go. 

I think I might reduce the target space since it's too probably a little unreasonably large the way it is now. 2-3px outside of the circle's radius should be fair.

**Comment by madsrh** [comment]
- I too think the hover in the second picture should be removed. 
- I really like the large target space
- Excuse my ignorance here, but isn't it possible to change the X image to be a rectangle, so the padding would be part of the image? or maybe that would look silly.
![close](https://user-images.githubusercontent.com/3986894/34908836-0ccbca52-f897-11e7-8033-fa37a00c228d.jpg)

**Comment by clobrano** [comment]
If I understood correctly, the effect should be this one

![window-controls-boxed-effect](https://user-images.githubusercontent.com/2883614/35109340-5f513c52-fc76-11e7-9842-dc697df04e85.gif)

**Comment by clobrano** [comment]
@godlyranchdressing do you mind if I commit this?

**Comment by godlyranchdressing** [comment]
Of course, though I think it'd be better if they have a radius to match the other headerbar buttons.

**Comment by clobrano** [comment]
> Of course, though I think it'd be better if they have a radius to match the other headerbar buttons.

That'd be surely better
