### ISSUE TITLE
Light font-weight for body?

### ISSUE THREAD

**Issue by nana-4** [Ubuntu/gtk-communitheme#181]
I noticed some [official Ubuntu website](https://www.ubuntu.com)s have `font-weight: 300;` in `body`. Then I thought that using `300` weight for the theme would fit more to Suru icons. What do you think about this?

Here is the adapted screenshot (with a few text color adjustments):

![image](https://user-images.githubusercontent.com/9556384/36419532-89436e4a-1675-11e8-9950-cfe77a70bfa9.png)

**Comment by clobrano** [comment]
I'd say I prefer current version, where fonts look more rounded and regular, while here they look taller than large. However, this is just my opinion, so I'm adding "design" label

**Comment by madsrh** [comment]
I prefer the current version too and agree with @clobrano that they look too tall.

What colors did you change? I would like to see a darker color for regular text. Are we following[ this pallette](https://github.com/CanonicalLtd/desktop-design/blob/master/Colour/colour.md) now @clobrano ?

Here's a slightly darker text color compared to the current:
![font_color](https://user-images.githubusercontent.com/3986894/36482493-c477baf4-1713-11e8-9aa7-284c272eb3b2.gif)

**Comment by nana-4** [comment]
@madsrh 
I used `$inkstone` (`#3D3D3D`) for _entry fields_, _views_, _list boxes_, etc. and `$graphite` (`#666666`) for _unchecked tabs_ from the [current Communitheme's color palette](https://github.com/Ubuntu/gtk-communitheme/blob/master/Communitheme/gtk-3.0/_ubuntu-colors.scss). See also #172 discussion.

> I would like to see a darker color for regular text.

+1 Completely agree. :)

**Comment by nana-4** [comment]
After reconsideration, I thought this my proposal was a bad idea, because it looks too thin with non-*Ubuntu* fonts such as Roboto, DejaVu, M+, etc.

Here's an example with M+ 1c:
![image](https://user-images.githubusercontent.com/9556384/36486197-4a008fd2-1761-11e8-88c6-4a3cacd72211.png)

Sorry for the spam. Should I close this? Or please feel free to close this issue.

**Comment by madsrh** [comment]
@nana-4 Could you post a screenshot of the current font for comparison?
I think it looks too thin in your screenshot. Did you change the font size also?

**Comment by nana-4** [comment]
@madsrh I changed change the font size to `10.5`. Here's the current font, with `Ubuntu Regular 10.5`:

![image](https://user-images.githubusercontent.com/9556384/36488849-d79ce088-1767-11e8-84f1-6e8f7abb50a0.png)

You can also test it quickly by using the [GTK Inspector](https://github.com/Ubuntu/gnome-shell-communitheme/blob/master/CONTRIBUTING.md#quick-testing-in-the-gtk-inspector) as follows. :wink: 

1. Run the following command in the terminal:

```
GTK_DEBUG=interactive gtk3-widget-factory
```

2. Go to the "**CSS**" tab in the GTK Inspector and add the following code:

```
* { font-weight: 300; }

tab:not(:checked) { color: #666666; }

entry:not(:disabled),
.view:not(:selected):not(check):not(radio),
.view text,
list { color: #3D3D3D; }
```

**Comment by nana-4** [comment]
@madsrh So now, are you thinking we should use light font-weight (`font-weight: 300;`) for the theme body?

However, I have to admit that my proposal was too adventurous. Yes, `* { font-weight: 300; }` with "**Ubuntu font**" is very sharp, but with **other fonts** it looks too thin (as shown in my screenshot above).

Compared to other Light (`300` weight) fonts, "**Ubuntu Light**" font is a little _thick_. (In other words, it's _sharp_ in smaller font-size.) I was testing only with "Ubuntu (Light) font", but I should have considered various use cases before filing this issue. :-/

**Comment by madsrh** [comment]
@nana-4 I'm saying that this is IMO the best and sharpes look. 
I actually thought the font-weight **wouldn't** apply to all fonts - so changing the font would reset to the default 400 weight and the CSS above would only apply to the Ubuntu font :( 

Anyway of doing that, or is that considered a hacky solution?

**Comment by nana-4** [comment]
@madsrh I see.
The `* { font-weight: 300; }` applies to all fonts as long as the font family has `300` weight.

> or is that considered a hacky solution?

I guess so.

Ideally, it would be great if "**Ubuntu Light**" could be applied from GNOME Tweaks (or dconf) (without CSS changes), but it seems GNOME doesn't allow that so far. 😥 (Even if we specify "Ubuntu Light" from GNOME Tweaks, regular weight (`400`) is used for the interface. Or should we report this problem to the upstream?)

**Comment by madsrh** [comment]
@nana-4 what would you suggest the upstream bug report would say?

I know that this opinion will be like pissing against the wind but I would say, let's use weight 300 and have a beautiful sharp font. I'm guessing 99,8% of Ubuntu users never change their fonts anyway. It would be silly to settle for the second best thing for millions of users, because of a small subset of font changing users. Just MHO.

**Comment by nana-4** [comment]
@madsrh As I said, setting the `font-weight` to `300` _by_ CSS may look too thin in other fonts. Also IMO we should consider characters that "Ubuntu font" does not support (e.g. Japanese, Chinese, etc). Even if users does not change the font (family), only characters that "Ubuntu font" does not support may look too thin.

IMO the best solution of that is changing the default _interface_ font from "Ubuntu Regular" to "Ubuntu Light" (by using a patch to dconf). But even changed the interface font to Ubuntu _Light_, GNOME still uses its _Regular_ weight. GNOME should respect the font weight chosen by users or distros, right?

What do you think?

**Comment by madsrh** [comment]
+1 yes!
I don't know anything about coding, but I don't think a patch to dconf will be allowed - if so, yes please!
I didn't consider support for Japanese, Chinese, etc.

If you file a bug upstream, could you post the link here?

**Comment by clobrano** [comment]
Sorry, but Gtk2 applications look weird with Ubuntu light

![image](https://user-images.githubusercontent.com/2883614/36629743-d728a138-195a-11e8-987d-a29db13eb329.png)

below with ubuntu regular

![image](https://user-images.githubusercontent.com/2883614/36629750-ed2b3f4a-195a-11e8-86e7-7a6a8ec81427.png)

**Comment by madsrh** [comment]
Hmmm, I actually think [the first one](https://user-images.githubusercontent.com/2883614/36629743-d728a138-195a-11e8-987d-a29db13eb329.png) looks better :/

Is this the new font color #2d2d2d ?

**Comment by clobrano** [comment]
> Hmmm, I actually think the first one looks better :/
It looks old to me or a problem with antialiasing, while the first is more likable, but it's just my taste. The bigger problem is that gtk3 applications will still using the other font.

> Is this the new font color #2d2d2d ?
I just changed the interface font on Tweak

**Comment by madsrh** [comment]
I see your point, but I think with the darker color and only at size 10, Ubuntu Light will look really sharp and modern ;).

> ...but it's just my taste. 

and this is just my taste LOL Your opinion is just as good as mine - we can agree to disagree :D

This "project" may require more research so let's stay with 400 and close it for now. Okay @nana-4 ?

**Comment by nana-4** [comment]
IMHO Ubuntu Light looks better even with the gtk2 app (and the text color should be darker). Just my taste, though.

@madsrh I'm okay to close this :)

I'm not sure yet which GNOME project to report that issue (maybe gtk+?), but I'll post the link here when I reported that issue.

**Comment by madsrh** [comment]
+1 I agree! 

Yeah, finding the right project can be a pain when reporting bugs to Gnome.

**Comment by madsrh** [comment]
**This is still closed!** 
During the discussion I created this comparison and just wanted to upload here, in case this topic is to be revisited again later. 

![colors_font_weight](https://user-images.githubusercontent.com/3986894/36779285-c0360fa2-1c6f-11e8-87f7-5ad6dc8c6e21.gif)

**Comment by nana-4** [comment]
Sorry for the delay in reporting.

Well, I said I'll report the issue to the upstream, but it was already reported and treated as NOTABUG. :(
https://bugzilla.gnome.org/show_bug.cgi?id=786398

**Comment by madsrh** [comment]
I have a 17.10 WM where I've set the weight, font color and size and it's a absolute joy to use! 🤗 

I know that there's a wish for as few patches as possible, but do you guys think they would consider carrying a patch for this issue?

![font-weight](https://user-images.githubusercontent.com/3986894/39153008-4559c5e8-474a-11e8-8404-58fc8b1092eb.gif)
