### ISSUE TITLE
borderless hover highlight on headerbar buttons

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#19]
![borderless-hover-hb-buttons](https://user-images.githubusercontent.com/2883614/34611851-7f18d670-f227-11e7-8803-27e12083c688.gif)

see [here](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/119)

**Comment by godlyranchdressing** [comment]
I was thinking to update the button mixin to take a $bc value. If if you use `$bc: none` then "fake" borders using the background color would be used. That'll get around any size issues since without borders the target for headerbar buttons would be 2px smaller.
