### ISSUE TITLE
Filled area of slider appears through handle in inactive windows.

### ISSUE THREAD

**Issue by CDrummond** [Ubuntu/gtk-communitheme#193]
As can be seen in the following screenshot (from gtk3-widget-factory), the handle of sliders in inactive windows are drawn semi-transparent. This causes the filled area of the slider to appear within the handle.

![gtk3-widget-factory](https://user-images.githubusercontent.com/1141694/36568146-cc1adc92-1820-11e8-81a8-493d2991f4e3.png)

**Comment by clobrano** [comment]
Hi @CDrummond thank you for reporting this, but it's a duplicate of #91

**Comment by CDrummond** [comment]
D'oh!!! Sorry.
