### ISSUE TITLE
Popup windows' corners are not equally rounded

### ISSUE THREAD

**Issue by FrancescoCuiusIuculano** [Ubuntu/gtk-communitheme#195]
The radius of the corners at the top of the window is different than the one at the bottom
![schermata da 2018-02-23 21-13-48](https://user-images.githubusercontent.com/29411952/36615114-57a4e2e4-18df-11e8-9ac6-58b3ef31202c.png)
Personally, I suggest reducing the radius of the bottom corners to better fit the rest of the theme

**Comment by madsrh** [comment]
Thanks for reporting this issue @FrancescoCuiusIuculano

This is related to https://github.com/Ubuntu/gtk-communitheme/issues/130

**Comment by clobrano** [comment]
closing this since it's a duplicate
