### ISSUE TITLE
Error pop-up window does not show low corners (white fg on white bg)

### ISSUE THREAD

**Issue by fthx** [Ubuntu/gtk-communitheme#203]
Hi,

Better than words :

![capture d ecran de 2018-02-26 16-02-21](https://user-images.githubusercontent.com/23138504/36677503-9707676e-1b0e-11e8-9cee-0c30d03225b7.png)

In Synaptic's usual error message.

**Comment by clobrano** [comment]
Curious problem, only with bright bg

![image](https://user-images.githubusercontent.com/2883614/36683526-1608b856-1b1e-11e8-822a-aaa8a0129b66.png)
