### ISSUE TITLE
Selection mode: Buttons and inactive state

### ISSUE THREAD

**Issue by yawzub** [Ubuntu/gtk-communitheme#204]
Selection mode is using unstyled buttons. And its inactive state is pretty bugged.
![selection-mode-1](https://user-images.githubusercontent.com/36858800/36687625-38ce0374-1b3b-11e8-99e1-6ddd005ce43f.png)

**Comment by clobrano** [comment]
@yawzub is still gnome todo? Can you tell me how to reach this view?

**Comment by godlyranchdressing** [comment]
Should be fixed with #208

**Comment by yawzub** [comment]
@clobrano No, this one is gnome software. Installed > Button with a check mark

**Comment by clobrano** [comment]
closed by #208
