### ISSUE TITLE
Wrong hover color in Gnome Logs

### ISSUE THREAD

**Issue by yawzub** [Ubuntu/gtk-communitheme#206]
I'm pretty sure it's supposed to be darker.
![gnome-logs](https://user-images.githubusercontent.com/36858800/36687768-9a0ea058-1b3b-11e8-95fd-aef3454d18dd.png)

**Comment by unicyn** [comment]
Same for gnome calculator.
![peek 2018-02-27 09-36](https://user-images.githubusercontent.com/5579957/36718457-2590e954-1ba2-11e8-92fc-6cee498a6c1f.gif)
