### ISSUE TITLE
Selection mode color

### ISSUE THREAD

**Issue by yawzub** [Ubuntu/gtk-communitheme#207]
In my opinion, it's better to use green color instead of blue. It will be

1. more consistent with Adwaita (selection mode color = suggested action color)
2. consistent with checkboxes

![selection-mode-2](https://user-images.githubusercontent.com/36858800/36687929-ffc28eaa-1b3b-11e8-9e12-48a043fbf74b.png)

**Comment by clobrano** [comment]
Hi @yawzub nice catch! I don't use Gnome Task and I wasn't aware of this colors :+1:

**Comment by godlyranchdressing** [comment]
It seems like such an obvious choice since _checkboxes use green_ but I never thought of it like that.

**Comment by clobrano** [comment]
closes by #208
