### ISSUE TITLE
Separation between active and passive (backdrop) windows is very harsh

### ISSUE THREAD

**Issue by ya-d** [ubuntu/gtk-communitheme#212]
As posted by @Luxamman (https://github.com/Ubuntu/gtk-communitheme/issues/194#issuecomment-368857266):

> The passive windows are tricky, I had to rethink them a little because the separation between active and passive windows is very harsh.
> 
> This is especially irritation when working with two windows side by side (something very common I think) - because passive windows look almost like deactivated or like they hung up.
> 
> Like in other systems, it is good to give a hint which window is passive (like windows control orange getting grey and headerbar little lighter, and content colors getting brighter or grey), but maybe we should not separate the whole content and buttons too hard.
> 
> When windows are stacked, they have separation lines and a shadow to be visually separated - so I'm with you to reduce the overall passive look - including buttons and content.

**Comment by ya-d** [comment]
(Quickly wrote down, so probably incomplete…)

*Main issue for me:*
- active entry fields and inactive buttons/fields swap colors: from white to grey/transparent or vice versa

*Minor issues:*
- Terminal changing background colors is rather intrusive
- sliders are not recognizable as active or inactive (proposal coming)
- …?

*Proposal:*
- white stays white (like new check/radiobuttons)
- inactive doesn't need to change at all
- active elements should be recognizable by higher contrast
- does the background really need to change? (same goes for Terminal background)
- maybe all colors should become the same grey value (see new check/radiobuttons) [currently their different even for the same color – maybe resulting from making them more transparent which makes the final color dependent of the background]

+ reconsider/check all colored buttons/elements in their various states

![window in focus](https://user-images.githubusercontent.com/30781876/36734230-29d14244-1bd3-11e8-94fd-bfbb7b98a911.png) 
![window in backdrop](https://user-images.githubusercontent.com/30781876/36734234-2f6a748c-1bd3-11e8-8f58-f2cb7614eef3.png)

**Comment by ya-d** [comment]
Quick and dirty mockup:
![window in backdrop mockup qnd](https://user-images.githubusercontent.com/30781876/36734320-6375d596-1bd3-11e8-9a64-934286d29d01.png)

**Comment by madsrh** [comment]
...Or we could keep the colors and behavior, but add a gray overlay. Here it's Silk #cdcdcd

![backdrop](https://user-images.githubusercontent.com/3986894/36781353-edfc051c-1c75-11e8-8184-458c6ade3266.jpg)

**Comment by CDrummond** [comment]
That looks much nicer. But does the difference need to be so drastic? Perhaps a more subtle difference? Also, how would this affect apps such as GIMP? Would the image being edited also be affected by the overlay? If so, that would be (IMHO) bad...

By keeping behavior - do you mean the mouse-over of items in inactive windows? That would be great too :-)

**Comment by madsrh** [comment]
> That looks much nicer. 

I think so too :)

> But does the difference need to be so drastic? Perhaps a more subtle difference? 

Perhaps you're right. I like this particular difference though. The idea is that you, at a glance, can tell which window is in focus.

> Also, how would this affect apps such as GIMP? Would the image being edited also be affected by the overlay?

Not sure, but I don't think so. This isn't actually an overlay, I'm just describing the effect. I guess we would have to style each item to look this way. How does GIMP look in Adwaita, I never noticed?

> By keeping behavior - do you mean the mouse-over of items in inactive windows?

Exactly! At the moment, the style items differently in backdrop (like the switches/toggels)

**Comment by CDrummond** [comment]
As to the 'drasticiness' of the effect - I'll leave that up to you, I'm no designer!

GIMP was perhaps a bad example - as its Gtk2. Just wanted to check that the 'view' within windows would not change - as the term 'overlay' had me thinking it would affect all windows. Anyway, I've just checked GIMP and GNOME Photos - and in neither of these, when styled with Adwaita, is the image affected when switching between active and inactive window states.

So for me, this would be an excellent change to have. I'm 100% in favour of widgets in inactive windows reacting to mouse-over (as they still receive any clicks over them, so should act as if they do)

**Comment by didrocks** [comment]
There still need to be a visual difference, even via side-by-side windows: only one window will receive keyboard inputs. However, I agree it can be way more subtle.

**Comment by madsrh** [comment]
>  I agree it can be way more subtle.

Way more, or just more?

The headerbar looses color (window controls, suggested-action / destructive-action - well like now) but everything inside the window keeps their colors with, this time, a Silk overlay at 50% (white becomes #e6e6e6).

![1](https://user-images.githubusercontent.com/3986894/36871449-95d3bdca-1da2-11e8-82fa-4676c03e162f.jpg)

![2](https://user-images.githubusercontent.com/3986894/36871454-98ecfa3a-1da2-11e8-93c0-ea2c32a1ae36.jpg)

**Comment by didrocks** [comment]
I find it quite obvious that way that the window isn't focused. However I think it's a little too visible when you work on side-by-side windows, as the original report stated, do you agree?

**Comment by madsrh** [comment]
I noticed that the color in the mockup above is actually darker that the current backdrop (#f2f2f2 vs. #e6e6e6), but this was done intentionally since the window elements keep their color and therefore steal more focus. 
I don't disagree with you, but at the same time I would like to keep that "_quite obvious_" difference. I'm +1 for a bit brighter.

@didrocks So would you like to see:
- a brighter overlay color (like #f2f2f2)
- only the headerbar to be colored
- or using the original concept that strips the all colors from the window but lighter

**Comment by didrocks** [comment]
@madsrh: I think a brighter overlay color might work. At worse, we reverse the decision and go for only the headerbar to be color.
The concept of stripping all the colors out was really cool, but I'm afraid it's a little bit too distracting for the side-by-side workflow.

I think we'll see soon a new "state" for those windows being side-by-side (but not in the current release), which may help differentiate like "being immediately workarable, even if not focused" and backdrop, which thus can use that stripping color concept.

**Comment by madsrh** [comment]
Okay, let's see if one of these might work:

![backdrop1](https://user-images.githubusercontent.com/3986894/37005824-d09efb1e-20d5-11e8-9d54-bb18648504a9.jpg)
![backdrop2](https://user-images.githubusercontent.com/3986894/37005825-d0b76ce4-20d5-11e8-9ad0-bc4ae0747cf1.jpg)
![backdrop3](https://user-images.githubusercontent.com/3986894/37005826-d0d25c7a-20d5-11e8-8ae3-813d76a2f56f.jpg)
![backdrop4](https://user-images.githubusercontent.com/3986894/37005827-d0f3efa2-20d5-11e8-9bb8-a6330314b8bb.jpg)
![backdrop5](https://user-images.githubusercontent.com/3986894/37005828-d10ba638-20d5-11e8-9ad6-8919b7a16a9a.jpg)

**Comment by CDrummond** [comment]
FWIW, I'd go with `f5f5f5` or `f0f0f0`

**Comment by clobrano** [comment]
Consider also #211, which will make active window's background a little less bright and almost the color of the buttons' background in above mockups

**Comment by madsrh** [comment]
We didn't actually consider making the backdrop lighter. As @luxamann pointed out, if the backdrop is too dark, it looks like it's deactivated or like they hung up.

Some light versions:
![backdrop_nocolor](https://user-images.githubusercontent.com/3986894/37020560-7098c686-211c-11e8-921b-7de31f5fba40.jpg)
![backdrop_25](https://user-images.githubusercontent.com/3986894/37020556-702e4c70-211c-11e8-9865-67c6d67c97aa.jpg)
![backdrop_33](https://user-images.githubusercontent.com/3986894/37020557-704ca116-211c-11e8-93be-dc4fdeecd0f6.jpg)
![backdrop_50](https://user-images.githubusercontent.com/3986894/37020558-7066bf2e-211c-11e8-9111-01c17a767dd2.jpg)
![backdrop_66](https://user-images.githubusercontent.com/3986894/37020559-707f8a0e-211c-11e8-9cbf-641815fa1d11.jpg)

**Comment by madsrh** [comment]
> Consider also #211, which will make active window's background a little less bright and almost the color of the buttons' background in above mockups

@clobrano Let's do another round of mockups when the button style, background and text color lands

**Comment by CDrummond** [comment]
To me, the lighter versions look like something has gone wrong with the app.

I'm no designer - but usually things in the background are darker, hence why (IMHO) the darker tinting looks nicer. The `f5f5f5` and `f0f0f0` shades are quite subtle, do don't make the app look disabled - just further away.

**Comment by clobrano** [comment]
> We didn't actually consider making the backdrop lighter.

Right, but if the active window is darker, the difference from the backdrop would be less visibile. About button restyle, I'd like to see if I can push some other changes for consistency, but it's almost done.

**Comment by madsrh** [comment]
> Right, but if the active window is darker, the difference from the backdrop would be less visible.

Well, the light backdrop is actually stripping away the colors again. So it's no so much that the active window is darker as it is that the backdrop looks pale. You can see what I mean below at the 100%. Anyway, I do agree that the slightly darkened versions **CDrummond** mentioned works best, but at least we explored this option. Let's hear what the bdfl @didrocks says :stuck_out_tongue_closed_eyes:

![backdrop100](https://user-images.githubusercontent.com/3986894/37021372-9a8c39a2-211f-11e8-8f10-d5be74d592cc.jpg)

**Comment by didrocks** [comment]
bdfl? Honored and scared :p

That's true that we shouldn't too much on the light or dark shadowing/overlay as it has the connotation the application has done something bad or stuck.

I personnally like `fefefe` (`f0f0f0` is a little bit too much to my taste), `fafafa` or 25% opacity works as well for me.

**Comment by CDrummond** [comment]
The changes are great for the light variant. The variant, however, is still very harsh when changing between active an inactive. The terminal also changes from a purple background to a black background when going from active -> inactive.

So, this issue is only partialy resolved.

**Comment by clobrano** [comment]
>The variant, however, is still very harsh when changing between active an inactive

do you mean the "dark" variant, or are you talking about the transition?

**Comment by CDrummond** [comment]
I meant when a dark window is focused, then unfocused, etc - the change to the dark window's widgets is quite harsh. Likewise the change in console background colour seems unnecessary - if a change is required, then a slight change in the shade but not a whole colour change.

**Comment by clobrano** [comment]
> The terminal also changes from a purple background to a black background when going from active -> inactive.

double checked now and this shouldn't look right, it should be this way now
![image](https://user-images.githubusercontent.com/2883614/37847129-0da4c16c-2ed0-11e8-89b8-e4d0add3f51e.png)

**Comment by CDrummond** [comment]
Ah, I was using the dark variant for GNOME terminal - this sets inactive window to black. Just tried with the light variant, and it is indeed a darker purple. Still think the difference is too strong - but that's just my opinion...

**Comment by clobrano** [comment]
The original proble is fixed now, closing this.

**Comment by Feichtmeier** [comment]
Necromancing this old conversation. Also we had a solution for this, I think we could still de-colorize the orange in backdrop a bit:
![image](https://user-images.githubusercontent.com/15329494/40367501-df7d7ae8-5dd9-11e8-8b4b-9eecf338d395.png)
This is too intense imho. Same for the orange underline in the stackswitcher:
![image](https://user-images.githubusercontent.com/15329494/40367558-07a70480-5dda-11e8-9dd6-ba42b90eb76e.png)

If you mostly disagree I will leave this in issue in peace ;D Otherwise I'll reopen and upload some pics (I can't say mockups, since I try stuff in CSS since I am bad with gimp)

**Comment by clobrano** [comment]
Right, @madsrh requested the same some days ago proposing a color similar to #dd501e

**Comment by madsrh** [comment]
Well, [the idea here](https://github.com/ubuntu/gtk-communitheme/issues/212#issuecomment-370606475) was to give everything a #f2f2f2 overlay. This will make everything slightly darker (obviously). In Gimp I simply create a solid color layer above a screenshot and set mode to multiply.

![image](https://user-images.githubusercontent.com/3986894/40386114-15dcbe30-5e09-11e8-88df-31164e980fea.png)

@clobrano I was merely pointing out the the backdrop orange isn't #dd501e as it should be if we follow the above reference 😃 
@Feichtmeier are you suggestion making everything darker like #f5f5f5 or are you only talking about the orange sidebar?

**Comment by Feichtmeier** [comment]
@madsrh currently every color is lightened up or "de-colorized". So for me that's why it would make sense to lighten/de-colorize the orange, too.

**Comment by Feichtmeier** [comment]
Sorry to be that annoying, but the window backdrop looks still unfinished to me.
I'd like to get have a solution which most of you agree on before opening a PR ;D

This is what happens at the moment:
- the header bar lightens (bg color)
- the icons in nautilus lighten (opacity)
- the icons in the sidebar lighten (opacity)
- the close button lightens/gets its background completely removed
- the orange does not change (and if it does, I can not see that :) ) and stays orange
![communibackdrop](https://user-images.githubusercontent.com/15329494/40609074-d7ae8364-626d-11e8-9ea1-636aaf21faed.gif)

This is how ambiance does it:
- everything becomes lighter and less colorful
- the orange gets exchanged by gray everywhere
![ambiancebackdrop](https://user-images.githubusercontent.com/15329494/40609082-e189e7e8-626d-11e8-8d91-8854989becc2.gif)

This is how adwaita does it:
- the 3d header bar becomes 2d 
- blue stay blue
- the text color lightens
- every dark border become light gray
![adwaitabackdrop](https://user-images.githubusercontent.com/15329494/40609099-e7b154ee-626d-11e8-8cec-e8db343edbbf.gif)

_______________________________

I like @madsrh idea to let the backdrop window fade into darkness.
I like the solution of adwaita and ambiance.
But the current solution is mixed up and misleading.
Either become lighter and less colorful or become darker but mixing both seems looks like a mixed communication to the user.

**Comment by clobrano** [comment]
I would certainly update the backdrop orange color, however where do you see a mixed approach?

the header bar **lightens** (bg color)
the icons in nautilus **lighten** (opacity)
the icons in the sidebar **lighten** (opacity)
the close button **lightens**/gets its background completely removed
the orange does not change (and if it does, I can not see that :) ) and stays orange

**Comment by Feichtmeier** [comment]
@clobrano 
The "mix" is that the orange does not lighten, it actually darkens a tiny bit somehow (could be an optical illusion, then sorry)

**Comment by Feichtmeier** [comment]
![yo](https://user-images.githubusercontent.com/15329494/40844243-afa532f2-65b3-11e8-8410-57bfbd3a6642.gif)

What about this? :angel: :innocent:

**Comment by madsrh** [comment]
@Feichtmeier I like, but I'm not sure if too much difference when working in side-by-side windows 🤷‍♂️ 
We also need to to make some kind of logic for the backdrop as we've talked about before.

IMO if you have a PR we could give this a try, but let's hear what the others have to say 😃

**Comment by Feichtmeier** [comment]
To me the window still does not look disabled. Yes I have a branch for this. I also provided a backdrop_selected_bg_color for both dark and light versions. PR incoming

**Comment by fabd** [comment]
Hi guys I have to ask here because I can't find an answer on Google.

Is it possible to turn off this passive / active window styling entirely?

I am working with a VirtualBox machine for web development. I love the look of the last Ubuntu but I feel this constant fade in / fade out is causing a lot of unnecessary redraws and making the VM feel less snappy (currently it's using VBox 6.x with 3D enabled (VMSVGA).

I think there should be a way to just turn this off entirely. It's not smooth either inside a VM so the effect is somewhat a miss.

Even better rather than turning it off, if you could configure this behaviour so that the switch of stlye is instantaneous it would remain effective and also faster inside a VM.

**Comment by clobrano** [comment]
Hi @fabd,

I am not aware of any setting that turn off the management of active and backdrop windows, this is entirely up to the window manager. Moreover, I don't think this would be possible (all the windows on focus? Or all the windows out of focus?).
I used both Vbox and gnome-boxes (libvirtd) and I've found no issues in this regards, probably is just that the VM doesn't have enough resources.

**Comment by fabd** [comment]
It's just that it isn't smooth inside a VM, so the transition between the colours isn't as attractive. I wish I could disable the transition. For example on Windows 10 host, the style of the window titlebars do change style between foreground and background, but they do so instantly as far I can tell. It would be nice to have that option.

**Comment by clobrano** [comment]
Disable 3D acceleration in your VM
