### ISSUE TITLE
Wallpaper has to fit to the communitheme

### ISSUE THREAD

**Issue by NusiNusi** [Ubuntu/gtk-communitheme#215]
**Please add design-label.**
I am not sure if this can be discussed here or if we should open a new thread at community.ubuntu.

The default wallpaper should be designed with the communitheme in mind. The style of the older wallpaper does not fit to the communitheme.

**Comment by madsrh** [comment]
@NusiNusi I've always liked the Ubuntu wallpapers that Canonical creates. I think you should start a thread on the community hub. Is it okay if I close the issue here?

**Comment by NusiNusi** [comment]
sure, you can close it. a complete new thread or as a post in the communitheme-thread?

**Comment by madsrh** [comment]
👍 I would start a new thread and add a post in the communitheme-thread to let people know about it. Like the Adwaita and Cursor discussions.

**Comment by madsrh** [comment]
I keen to hear why you don't think the style of the older wallpaper fits the communitheme, but I'll watch the thread.
IMO we want to say a close to everything Canonical ships and the is, for me, not an issue.
