### ISSUE TITLE
Titlebars still blurry

### ISSUE THREAD

**Issue by CDrummond** [Ubuntu/gtk-communitheme#216]
https://github.com/Ubuntu/gtk-communitheme/pull/209 has fixed the edges of CSD apps (i.e. those that use GtkHeaderbar). However, non CSD apps (GNOME terminal, LibreOffice, Firefox, any Qt app,etc) still have blurry borders.

**Comment by ya-d** [comment]
Is this what you mean? Otherwise please consider it another bug for gtk2 window border:

<img width="609" alt="bug window border gtk2" src="https://user-images.githubusercontent.com/30781876/36868847-e598d7ae-1d99-11e8-8bae-25bfd2fbacc0.png">

**Comment by CDrummond** [comment]
No, it is **not** the toolkit. The window titlebar for non-CSD apps is drawn by the X11 window manager. Metacity used to be the GNOME shell WM, but I'm not sure if it still is.

This issue applies to **all** non-CSD apps - GNOME terminal (gtk3), LibreOffice (VCL?), VLC (Qt5), etc. Any window that does not draw its only titlebar (i.e. does not use GtkHeaderBar) has the **same** issue as reported in https://github.com/Ubuntu/gtk-communitheme/issues/192 - hence no new screenshots required. #209 fixed this for GtkHeaderbar apps - and the same fix is needed for other apps.

**Comment by clobrano** [comment]
Yeah, I always forgot Gtk2...

**Comment by CDrummond** [comment]
I'm pretty sure the window manager is not Gtk2. So this is not a Gtk2 issue.

**Comment by clobrano** [comment]
Alright, I might need some help here. Investigating on gnome-terminal the decoration is exactly what I expect it to be, that is like the other csd windows, but it's window edges are still blurry

![image](https://user-images.githubusercontent.com/2883614/36944658-512f85f4-1fa1-11e8-9bf6-dafedeee2be3.png)

is it possible that this applications do not care of all css style?
@nana-4 , @godlyranchdressing

any help is appreciated :smile:

**Comment by nana-4** [comment]
Non-CSD windows use server-side drop-shadows + [this](https://github.com/Ubuntu/gtk-communitheme/blob/master/Communitheme/gtk-3.0/_common.scss#L4538).
I beleave `.ssd & { box-shadow: none; }` will resolves this. :smile:

**Comment by clobrano** [comment]
> I believe .ssd & { box-shadow: none; } will resolve this.

first think I tried, no luck :disappointed:

**Comment by nana-4** [comment]
@clobrano Did you try restarting `gnome-shell` with <kbd>Alt</kbd> + <kbd>F2</kbd> and <kbd>r</kbd>?
Just reloading the GTK+ theme doesn't change the server-side decoration.

**Comment by clobrano** [comment]
> Just reloading the GTK+ theme doesn't change the server-side decoration.

:man_facepalming: you're right! I'll try again today

**Comment by clobrano** [comment]
yes! So much win! Thanks a lot @nana-4
