### ISSUE TITLE
Add lines to lists

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#218]
This is low priority, but lists like below appears confusing at a glance. One of these could improve readability:
- add a light gray border
- add a light gray background to the list
- adding lines as separators

Below is comparing: current Community Theme / mockups / Ambiance.

![lines-in-lists](https://user-images.githubusercontent.com/3986894/36877338-04e61714-1dba-11e8-9452-7e231c0a5879.gif)

**Comment by ya-d** [comment]
+1 for border.

**Comment by clobrano** [comment]
I was thinking the same for Nautilus list view

**Comment by madsrh** [comment]
@clobrano Yes, that would also be following upstream Adwaita in both cases. 👍

**Comment by madsrh** [comment]
We might want to go with both lines and a border? Maybe...

![untitled-_](https://user-images.githubusercontent.com/3986894/37023520-7caf49cc-2126-11e8-86b3-43cd07448311.jpg)

**Comment by nana-4** [comment]
I can send a PR to add lines to the app and Nautilus, but I think the _border_ shouldn't be added (even if it looks good). The issue with no border is the app specific bug, not the theme bug. If we try to add the border (for the app), it may look broken in other apps.
