### ISSUE TITLE
context menu needs to be updated (?)

### ISSUE THREAD

**Issue by godlyranchdressing** [Ubuntu/gtk-communitheme#22]
Should consult with everyone first as this involves limiting the orange.

![current](https://user-images.githubusercontent.com/27529229/34612886-ffe918bc-f201-11e7-89d4-9a9d8560f21c.jpg)
![750w_menus_cascadelarge](https://user-images.githubusercontent.com/27529229/34612885-ffd14ee4-f201-11e7-8c6c-9136a1376bd0.png)

Should be an easy "fix", just let the background color for hovered items in the context menu be the same color as the one for the popover menu items.

**Comment by madsrh** [comment]
+1 looks much cleaner
