### ISSUE TITLE
Cleanup Software Center review UI

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#226]
Looking at the reviews in Software Center is **very** messy - even in Adwaita.
I would like to see each review separated (_into a white box?_) to achieve a more organized look. In the mockup below I've also add some color, but perhaps I got a little too carried away :laughing:

 **Comparing:** Adwaita vs. Community theme mockup
(_click for fullsize_)
![review](https://user-images.githubusercontent.com/3986894/36940877-252a4794-1f4e-11e8-8dfb-5c385bf7809e.gif)

**Comment by NusiNusi** [comment]
Maybe with more rounded corners?

**Comment by nana-4** [comment]
How about this? I adapted the Unity8 card style to each review.

![image](https://user-images.githubusercontent.com/9556384/36993277-be2e203e-20f0-11e8-9cb3-6ab4aae45bae.png)

Oh, it seems we can't change the "star icon" and "review bar" colors because those styles are hard-coded in the app. 😥

**Comment by madsrh** [comment]
@nana-4 Already a much improved look. Can you push a PR for this?
I really think the difference between Adwaita and the colored mockup is night and day, so it's **truly** bad news that they are hard-coded :disappointed:
We should file a bug upstream ( [or is it this one?](https://gitlab.gnome.org/GNOME/gnome-software/issues/65) ). It looks like they got a ton of more important bugs that needs attention, but we can always hope a fix will land in time for 18.10.

I know that it's a different style then everything else in the UI, but I was trying to mimic paper more than an actual window element. I don't know why, but when thinking of a list of reviews, this was the first thing I thought of. So I deliberately left out the rounded corners @NusiNusi :wink:

![banners-mock-up_1017-6851](https://user-images.githubusercontent.com/3986894/37002969-ae404064-20cb-11e8-8bc6-d9865116a252.jpg)

**Comment by nana-4** [comment]
> Can you push a PR for this?

Sure :smile: 

>  ( or is it this one? )

I don't think it's actually related. I guess this issue is rather close to this:
https://gitlab.gnome.org/GNOME/gnome-software/issues/80

> So I deliberately left out the rounded corners

So do you think that I should left out the rounded corners in the PR?
![image](https://user-images.githubusercontent.com/9556384/37019115-5d4598aa-215a-11e8-8fd6-fdf9f8674543.png)
(Indeed) I might prefer the squared corners rather than the rounded corners for review boxes. 😜

**Comment by madsrh** [comment]
> (Indeed) I might prefer the squared corners rather than the rounded corners for review boxes. 😜

+1 for squared corners. Perhaps remove the gray border (if there is one) and add a bit more shadow - just a thought.

> I don't think it's actually related. I guess this issue is rather close to this:
https://gitlab.gnome.org/GNOME/gnome-software/issues/80

There's a patch! 😃
Okay, we can just add our +1 in this issue.

**Comment by nana-4** [comment]
@madsrh There's no border, there's only a shadow (in the screenshot). :smiley: 
Hmm, I tested but even with just a bit more shadow, the boxes look unfocused and distract attention IMHO. I'd say let's go with the current one (at least so far).
