### ISSUE TITLE
Make backdrop transition more uniform and smoother

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#228]
![backdrop-transition](https://user-images.githubusercontent.com/2883614/36989277-86ec7b7e-20a1-11e8-8500-be18949fe2a6.gif)

**Comment by NusiNusi** [comment]
Shouldnt the icons become grey too?

**Comment by clobrano** [comment]
The idea is to reduce a lot the grey, see #212

**Comment by Feichtmeier** [comment]
![scxyx](https://user-images.githubusercontent.com/15329494/41028447-c070f0c0-6979-11e8-996e-6c603aed501a.gif)
I think software still has some hard transistion

**Comment by Feichtmeier** [comment]
@clobrano every other GTK3 (modern headerbar) I've tried has a smooth transition. I think we can close this one and this one https://github.com/ubuntu/gtk-communitheme/issues/290 as fixed. I rather think this is some problem with gnome-software's hierarchy, which isn't the smoothest gtk app out there anyways (it's still great in functionality)
