### ISSUE TITLE
Suggested Action Button could use a different contrast when deactivated

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#235]
![screenshot from 2018-03-07 17-51-31](https://user-images.githubusercontent.com/15329494/37105792-5f10d75e-2230-11e8-932c-34115411c466.png)
![screenshot from 2018-03-07 17-50-12](https://user-images.githubusercontent.com/15329494/37105793-5f3000fc-2230-11e8-82d5-b9715024de81.png)

It is really hard to read and looks a bit out of place. Nothing really bad but could be an improvement to change the green when it is deactivated to something lighter, so you can read the text.
I try to find an example in the bright version of this theme meanwhile, though the suggested action color is green anyways

**Comment by clobrano** [comment]
@Feichtmeier awesome wallpaper and thanks for the report :wink:

**Comment by Feichtmeier** [comment]
I am happy to contribute atleast somehow :) Which my css skills where a bit better

**Comment by clobrano** [comment]
hey @madsrh, @Luxamman,

what do you think about using a transparent background in this case?

![image](https://user-images.githubusercontent.com/2883614/37179201-2f825eb8-2325-11e8-9e21-4b4cfe2912bf.png)

here in backdrop
![image](https://user-images.githubusercontent.com/2883614/37179241-51406d24-2325-11e8-983f-7095f4d3c53c.png)

**Comment by madsrh** [comment]
@clobrano I don't think it's obvious enough that the button is disabled. I have these notes:

Green buttons background: #3EB34F (is this the current?)
Green buttons text: white
Disabled green button: 50% opacity #3EB34F (which becomes #356e3c)
Disabled text on green: 50% opacity of white (which becomes #aebfb0)

...but maybe the issue is that these, very colorful, suggested-action / destructive-action buttons are next to the text-based buttons.

**Comment by clobrano** [comment]
> ...but maybe the issue is that these, very colorful, suggested-action / destructive-action buttons are next to the text-based buttons?

correct. All of them are text-buttons, so the disabled text color should be the same, but of course what is OK on a dark background it is not on a green one (even if opaque) and vice versa

**Comment by madsrh** [comment]
Sorry, I've missed that :pensive:
Just to be clear, we have to find ONE text-color for all deactivated buttons that works on no (soon slightly gray), green and red buttons? What color is the text currently? #666b72 ?

**Comment by clobrano** [comment]
> Just to be clear, we have to find ONE text-color for all deactivated buttons that works on no (soon slightly gray), green and red buttons?

Well, we can have different colors for normal and special buttons, but I guess it might look weird if they're not the same. Of course if there's a combination that looks good, I'm totally OK

>  What color is the text currently? #666b72 ?

Not sure, on sass it is a very complicated expression :smile: but color picker gives me  something like #777575

![image](https://user-images.githubusercontent.com/2883614/37241766-f13ed966-245e-11e8-9c5a-cd901cb5f454.png)
