### ISSUE TITLE
GtkCheckButton is unthemed in gnome-music

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#236]
Using 18.04. 

The class is called GtkCheckButton and this really looks like adwaita to me

![screenshot-20180307180030-1308x841](https://user-images.githubusercontent.com/15329494/37106183-72dc3a2a-2231-11e8-9d22-f50fe0195ae2.png)
![screenshot-20180307175820-1172x874](https://user-images.githubusercontent.com/15329494/37106184-72fe6ffa-2231-11e8-91cb-ea4e4d057abc.png)

I wondered if this is a gnome-music specific issue and tried to find some other checkboxes, didn't find any yet. In gnome-todo they use a different element class GtkEventBox which you themed allready 

![screenshot-20180307180318-994x714](https://user-images.githubusercontent.com/15329494/37106421-137e4b62-2232-11e8-8000-fba3104897b8.png)
![screenshot-20180307180258-1392x731](https://user-images.githubusercontent.com/15329494/37106422-139af302-2232-11e8-888d-39b28abbe356.png)

**Comment by madsrh** [comment]
@Feichtmeier First of all, **excellent** music collection! :musical_note: Thanks for reporting this issue!

**Comment by Feichtmeier** [comment]
I searched for the checkbox in the gtk3.0 folder and there are only the adwaita checbox asstes.
But you allready got asstes for the checkbox in the gtk2 folder - maybe you can use those?
I wonder how GtkEventBox is themed. Can't find the class in the _common.scss

**Comment by godlyranchdressing** [comment]
I'm seeing the green checkbuttons on my end. Are you still getting the issue?

@Feichtmeier 
After selecting an object, change Miscellaneous to CSS Nodes, that'll give you the widget and class names used in the scss files.

**Comment by Feichtmeier** [comment]
Sadly yes, I am using the ppa on my machine, maybe something went wrong on the 17.10->18.04 upgrade past weeks. Checking on my VM where I pull the changes manually. Checked the assets folder and there is still only adwaita.

**Comment by Feichtmeier** [comment]
@godlyranchdressing yes it's still present until now on both snap installation on my families computers and on my host machine with up to date master
