### ISSUE TITLE
Stackswitcher dark has wrong color

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#237]
Below picture is taken from Gnome-Boxes

![image](https://user-images.githubusercontent.com/2883614/37120388-89c89408-225a-11e8-99d2-53f0a8c251d6.png)

**Comment by godlyranchdressing** [comment]
It's using the regular button style since it's "buttonbox.horizontal.linked button.text-button" instead of stackswitcher.
