### ISSUE TITLE
GNOME Terminal uses solarized tabs but purple background

### ISSUE THREAD

**Issue by pojntfx** [ubuntu/gtk-communitheme#239]
When using GNOME Terminal, for some time the background of it was solarized blue like in Unity8. Since a recent update it's back to the purple, while the tab background is still solarized, which looks ok when in focus (IMHO) but really weird when not focused - is this intentional / could we maybe switch back to the solarized version or just purple?

Unfocused:
![image](https://user-images.githubusercontent.com/28832235/37153553-5dfcf7b4-22dd-11e8-8e39-ebba2498e8d4.png)
Focused:
![image](https://user-images.githubusercontent.com/28832235/37153575-768e31c6-22dd-11e8-981b-ad9ed552290d.png)

**Comment by Xyaneon** [comment]
I personally don't like the Solarized background color when focused. It just doesn't fit the rest of the theme.

**Comment by clobrano** [comment]
Fixed by #249
