### ISSUE TITLE
Highlight-Color

### ISSUE THREAD

**Issue by NusiNusi** [Ubuntu/gtk-communitheme#240]
Colours in ubuntu. There are the ones who hates orange and other who like it. We tried this discussion many times and it was not easy to keep cool. I think now could be the last chance to try it again. If this is definitely already decided i will close this issue.

Why change the highlight-color? Canonical itself did some research and found out, that the color orange could be understood as a warning:
https://user-images.githubusercontent.com/1492981/36139829-56c563c8-109f-11e8-8177-8b8208c63f3b.png

The color-scheme for Unity 8 had blue in mind for the highlight-color:
![colorscheme](https://user-images.githubusercontent.com/36449926/37166151-97a07dbc-22fe-11e8-8dc6-bb82061dbaa7.png)

Should this be tested? At least could someone make some screenshots for comparison? I think we should at least "see" how suru-blue (the darker one?) would look like in the communitheme to be sure.
And again: if this is not open for discussion, i will close this issue.

**Comment by Feichtmeier** [comment]
I am not a designer at all, but I strongly vote no (silently, as a user :) )
Why:

- this theme is minimal, yet it should somehow be attached to Ubuntu and when you think of ubuntu, you think of an orange circle
- most people use LTS and still use ambiance, if this theme is somehow a good bridge between ambiance and the never occurred unity8 future, then with some of ambiance elements, like the orange selectiion. it should not be a too hard transistion imho

**Comment by madsrh** [comment]
> Should this be tested? At least could someone make some screenshots for comparison?

We tried this earlier, along with some other options, but I can't find the mockups at the moment.

> If this is definitely already decided i will close this issue.

That's a strong wording, but yes for now at least we've decided to stay with orange.

I'm taking the liberty of closing this issue (for now).
