### ISSUE TITLE
Old buttons are still used in some places

### ISSUE THREAD

**Issue by yawzub** [Ubuntu/gtk-communitheme#241]
Gnome Videos controls: 
![buttons1](https://user-images.githubusercontent.com/36858800/37170341-a4f78b00-231b-11e8-8838-81ba4590f8de.png)
In-app notifications:
![buttons2](https://user-images.githubusercontent.com/36858800/37170363-b1dab6ee-231b-11e8-9637-075bdf2a1cbf.png)

**Comment by Feichtmeier** [comment]
I am not quiet sure if those are the adwaita buttons. I believe these are the buttons from this theme, but in it's dark variant.

![screenshot-20180308224948-1093x139](https://user-images.githubusercontent.com/15329494/37178521-0949706c-2323-11e8-98a6-7893af543990.png)

**Comment by clobrano** [comment]
I can confirm that, those are the Communitheme dark version buttons

**Comment by yawzub** [comment]
@clobrano  This is how it looked before the redesign:
![buttons3](https://user-images.githubusercontent.com/36858800/37255758-fd648c0a-2561-11e8-9627-f07780e5deb0.png)
And this is how it looks now:
![buttons4](https://user-images.githubusercontent.com/36858800/37255762-0d7a19ac-2562-11e8-9a0d-5ad252c617b6.png)
Is it really intended? The consistency is lost.

**Comment by clobrano** [comment]
Also light version has changed to a flatter version, why do you think the consistency is lost?

**Comment by nana-4** [comment]
I agree with @yawzub. The buttons in the screenshots are `osd` style one. With the new version of the buttons there is no inner box-shadow, but with the `osd` style it still remains.

I assume you forgot to change the [osd button style](https://github.com/Ubuntu/gtk-communitheme/blob/master/Communitheme/gtk-3.0/_drawing.scss#L372-L446) with the recent commits. :smiley:   @clobrano
