### ISSUE TITLE
Initial/Empty states: low contrast on text color

### ISSUE THREAD

**Issue by yawzub** [Ubuntu/gtk-communitheme#242]
![state1](https://user-images.githubusercontent.com/36858800/37170438-dd4edb16-231b-11e8-8b5d-bdab43cb729b.png)
It probably should look like this:
![state2](https://user-images.githubusercontent.com/36858800/37170449-e591949e-231b-11e8-8d91-4f0a68edbd9b.png)

**Comment by clobrano** [comment]
Hey @yawzub thanks for reporting this!
What's the application in the first picture?

**Comment by yawzub** [comment]
@clobrano Gnome Notes/Bijiben.

Also, please check #241 again.  I added some pictures there.

**Comment by clobrano** [comment]
> @clobrano Gnome Notes/Bijiben and Gnome Documents. Gnome Clocks(Alarm/World tabs) and Gnome Music are also affected.

Thank you, in the other application I had no empty state :)

> Also, please check #241 again. I added some pictures there.

yep, I received the notification

**Comment by clobrano** [comment]
Both Gnome document and Note add a **dim-label** class to the text. Without that styling the look would be this one
![image](https://user-images.githubusercontent.com/2883614/37485871-017d46f0-288d-11e8-8ab2-436df9a67ab1.png)

It looks like the maintainers of the projects want a low contrast text
