### ISSUE TITLE
GTK2 issues

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#246]
I know that GTK2 is low priority as things are slowly settling in GTK3 land, but I thought we could list known issues here. Maybe all of these are already known.

- Bold font in menus
- Old style buttons
- Can't see the white _v_ on selected checkmarks

![pinta](https://user-images.githubusercontent.com/3986894/37183004-414014f6-2334-11e8-8c72-7c61f03bff66.jpg)

**Comment by ya-d** [comment]
Duplicate of #112.

**Comment by madsrh** [comment]
Doh!
