### ISSUE TITLE
No pop-up title bar in printer config

### ISSUE THREAD

**Issue by fthx** [Ubuntu/gtk-communitheme#247]
![image](https://user-images.githubusercontent.com/23138504/37208787-e401926e-23a2-11e8-97dd-897986fef383.png)

system preferences > printers > printer info pop-up
I cannot close this pop-up with mouse (ESC key does the job here).
No problem in Adwaita or Ambiance.
I maybe can remember such a bug in Ambiance, possibly it was Didier who solved this issue.

**Comment by pojntfx** [comment]
![image](https://user-images.githubusercontent.com/28832235/37241758-cb43931e-245e-11e8-89a5-8d236b38b3ea.png)

Can reproduce on Bionic.
