### ISSUE TITLE
Style searchbox

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#251]
I really don't know what this is called so feel free to rename this issue (or enhancement / styling).

![search](https://user-images.githubusercontent.com/3986894/37240564-9fdc40ba-244d-11e8-920a-bbec3a2d4d63.gif)

Perhaps something like this:

![search](https://user-images.githubusercontent.com/3986894/37240688-3db86b5a-244f-11e8-84b4-a583de70b7ee.jpg)

**Comment by clobrano** [comment]
closed by #275
