### ISSUE TITLE
Separator between nautilus navigation buttons

### ISSUE THREAD

**Issue by CDrummond** [Ubuntu/gtk-communitheme#261]
1. Start nautilus
2. Click on any folder to change path (back button in nautilus headerbar should now be enabled)
3. Press back button, but do no release, drag window around, and then release
4. There is now a white separator line between the back and forward buttons

![separator](https://user-images.githubusercontent.com/1141694/37399990-47de3b58-277b-11e8-97a0-85a112c0cba0.png)

This is a very minor issue.

**Comment by clobrano** [comment]
I though it was gone with last rework headerbars rework :cry:

**Comment by Feichtmeier** [comment]
@clobrano maybe these lines?

line 959-963
&:not(:first-child) > button.flat {
    // linked buttons will have more defined border colors
    border-left-color: $borders_color;
    &:disabled { border-left-color: $insensitive_borders_color;}
  }
