### ISSUE TITLE
Buttons and entry fields too similar?

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#265]
With the recent change to the button look, buttons and entry fields look **very** similar.

In the following screenshot, its hard to see if the middle item is an entry field or a button (it's an entry field):

![entry_or_button](https://user-images.githubusercontent.com/1141694/37512563-697d8ac2-28fa-11e8-89c6-b1a9ed1c3f12.png)

The above was created using the following python code:

```
#!/usr/bin/python3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class ExampleWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="Example")
        
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10, margin=10)
        box.set_homogeneous(False)

        entrya = Gtk.Entry()
        entrya.set_text("  Is this an entry or a button?")

        entryb = Gtk.Entry()
        entryb.set_text("  Is this an entry or a button?")

        button = Gtk.Button(label="Is this an entry or a button?")
        box.pack_start(entrya, True, True, 0)
        box.pack_start(entryb, True, True, 0)
        box.pack_start(button, True, True, 0)

        self.add(box)

window = ExampleWindow()        
window.connect("delete-event", Gtk.main_quit)
window.show_all()
Gtk.main()
```

Perhaps buttons should have a _slightly_ darker background?

**Comment by madsrh** [comment]
@CDrummond I agree, I think the buttons are still being worked on. [Issue 211](https://github.com/Ubuntu/gtk-communitheme/issues/211) is still open.

@clobrano Isn't there still some shadow missing for buttons? My mockup in #211 isn't the best place to look, but perhaps look to Pop for inspiration for the shadow:
![image](https://user-images.githubusercontent.com/3986894/37515739-13c50896-290c-11e8-9f6c-403a0d021375.png)

I'm not sure if the shadow becomes hard to notice when we also have a border? So perhaps more shadow than Pop uses.

**Comment by clobrano** [comment]
I thought the shadow should appear only on hover. I'll fix it

**Comment by madsrh** [comment]
> I thought the shadow should appear only on hover. I'll fix it

A little shadow on buttons and even more shadow if hovered ;)
Again, like Pop (although their hover shadow might be a bit too much).

**Comment by clobrano** [comment]
We'd need to break the pixel in a half here :smile: , but @CDrummond's right.

This way the different is still too minimal, isn't it?

![image](https://user-images.githubusercontent.com/2883614/37554563-01251c38-29db-11e8-9348-be6e4449521b.png)

but if this is OK, I wouldn't go further, because we should consider also linked widgets where a too different shadow would look weird

![image](https://user-images.githubusercontent.com/2883614/37554581-3c50b808-29db-11e8-8e6a-519a142d389b.png)

**Comment by madsrh** [comment]
I like it!

Much better IMO. @cdrummond ?

**Comment by CDrummond** [comment]
I like the shadow under the button - the difference is subtle, but enough to differentiate. Also, the text being centred on buttons helps - my example was delibertly obfuscated by add spaces before the text in the entry.

I don't think the buttons on editable combos should have a shadow though, as it'd look weird to have shadow on only part of the widget.

**Comment by NusiNusi** [comment]
How about a soft gradient inside the button? This would make easier clear that it is a button.

**Comment by clobrano** [comment]
@NusiNusi I think the gradient will break the flat idea of the theme
How about this?
![button-vs-entry](https://user-images.githubusercontent.com/2883614/37564700-866c422a-2a9b-11e8-8e9d-831e2a9b127b.gif)

**Comment by madsrh** [comment]
This looks really good @clobrano!

Ideally we would want all clickable buttons to have the same shadow, but as mentioned this looks weird with comboboxes. Let's see how people react to this design - I think it's pretty obvious that the dropdown arrow is clickable, although it breaks the "shadow rule". IMO this is a good solution.

**Comment by madsrh** [comment]
@clobrano Is it deliberate that the down arrow button border in the deactivated combo, is darker than the entry field? I know that Ambiance does this, but wouldn't it make more sense to use the same light gray for the entire thing?

![button](https://user-images.githubusercontent.com/3986894/37564892-4b66fb4e-2a9f-11e8-8a77-d07385b2e170.gif)

**Comment by clobrano** [comment]
@madsrh I haven't noticed, nice spotted :)

**Comment by NusiNusi** [comment]
@clobrano i like it a lot! very beautiful! There is only one thing that i think should maybe be changed: the pressed button. Maybe it is too grey? Maybe the shadow is to strong? not sure but it looks very "3d-ish". How about this: pressed has just no shadow. nothing more. Or only an inside-shadow as strong as the normal shadow.

**Comment by clobrano** [comment]
I was thinking the same, however with no inset shadow, buttons would look like entries again

**Comment by CDrummond** [comment]
Perhaps just loose the shadows on the side? ie. so that pressed buttons only have shadow on the top, like raised buttons only have on the bottom? I still think having a darker shade for pressed buttons makes sense.

**Comment by clobrano** [comment]
This doesn't look bad, does it?
![image](https://user-images.githubusercontent.com/2883614/37668165-17ed027e-2c64-11e8-9782-6efd0272dbc5.png)

**Comment by NusiNusi** [comment]
For me the pressed button still looks more 3d-ish than the normal button.

**Comment by clobrano** [comment]
This doesn't look bad, does it?
![image](https://user-images.githubusercontent.com/2883614/37668165-17ed027e-2c64-11e8-9782-6efd0272dbc5.png)

**Comment by NusiNusi** [comment]
its less grey, right?

**Comment by clobrano** [comment]
I think it needs to be a bit more "3d-ish". This is the same effect of hover button, just inverted (please, look just at the pressed one, not the inactive)

![image](https://user-images.githubusercontent.com/2883614/37670340-52626386-2c69-11e8-8a70-7b2a3a08c7cf.png)

to me, the effect is too light, it doesn't really show that the button is pressed

**Comment by NusiNusi** [comment]
hm... is there a situation when a button stays pressed? Or else it would be only for the moment we press the button. Then it should be clear. But your are right. Maybe it is just too much grey that makes it look too 3d-ish.

**Comment by madsrh** [comment]
+1 @clobrano

 It needs a bit of 3D look to look pressed IMO.

**Comment by CDrummond** [comment]
I actually like the look of the last screenshot. In the previous ones, as there's shadon on the sides, it makes the edges look _blurry_ to me.

**Comment by clobrano** [comment]
> hm... is there a situation when a button stays pressed?
of course, the button can stay pressed

> I actually like the look of the last screenshot. In the previous ones, as there's shadon on the sides, it makes the edges look blurry to me.

but it doesn't look pressed. Actually it looks more like an external shadow, like the if light comes from the bottom

**Comment by CDrummond** [comment]
Yup I can agree. So, perhaps the border needs to be darker than the shadow? That way in can have the shadow on 3 sides, but still remain sharp on the edges?

**Comment by clobrano** [comment]
I'll try something, but I'm pretty happy with last one

**Comment by clobrano** [comment]
I'm going to release this change tonight, so I can speed up the review of the backdrop state. If we need new refinements, I will open a new ticket

**Comment by CDrummond** [comment]
@Feichtmeier Due to the removal of the 3d effect on buttons, this bug is now valid again. I'm not opposed to flat buttons - but there needs to be more difference between buttons and entry fields.

**Comment by clobrano** [comment]
RIght @CDrummond, I have forgotten this :(

**Comment by Feichtmeier** [comment]
We could give entry fields a small inset Shadow similar to the new undershots what do you think ? :)

**Comment by CDrummond** [comment]
@Feichtmeier so, remove 3d from buttons, and add to entry fields :-)  (Just joking, no offence intended...)

Perhaps make the buttons slightly darker?

**Comment by Feichtmeier** [comment]
Hmhm =)
The idea was to decrease the amount of visible layers when not hovered. Not to make gtk3 flat. The shell is flat not the gtk3 theme.
Now we have 2 layers when not hovered and 3 or 2 1/2 when hovered. Thus it would be no problem to give entries a super light shadow like undershoots or underpants? How are they called again?

**Comment by clobrano** [comment]
Inset shadow on entry is a Aaron's work in progress, but we don't need to reinvent anything IMO, just revert flat buttons (maybe just a little better)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/41410074-8e335ed0-6fd8-11e8-9106-3bfeacfe3455.png)
With a little darker top border I don't think someone could think that the entries are btns tbh
