### ISSUE TITLE
Hover effect broken in toolbar's button

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#269]
In below picture one button is hovered, but is not visible

![image](https://user-images.githubusercontent.com/2883614/37566243-c8ec6222-2ab6-11e8-8c32-bc00438b6d37.png)

Also expander button in gnome software does not show hover effect as well
![image](https://user-images.githubusercontent.com/2883614/37566388-bd035e14-2ab8-11e8-9b66-124c076ad089.png)

NOTE: expander button is defined as a .flat one, this is why it does not show any border

**Comment by nana-4** [comment]
I guess this is a duplicate of #250.

**Comment by clobrano** [comment]
You're right @nana-4 :+1:

**Comment by Feichtmeier** [comment]
Duplicate of #250
