### ISSUE TITLE
Darker background?

### ISSUE THREAD

**Issue by CDrummond** [Ubuntu/gtk-communitheme#271]
The background colour is **very** light in most cases (sometimes white) - e.g. the background of notebook widgets, the right hand pane of settings and tweaks. IMHO, it'd look nicer if this background was slightly greyer (perhaps even a _very_ slightly brownish grey (as per titlebars, etc)).

The background to tree and list widgets is fine being white, I just think other widgets should be darker - which would help make buttons and entry fields stand out. It does not need to be a lot darker, just slightly.

Edit: I guess the tweaks/settings backgrounds are #259 - but not sure if that covers notebook background? If so, then please just close this.

**Comment by CDrummond** [comment]
Closing - as its really just a duplicate of #259

**Comment by clobrano** [comment]
Hi @CDrummond thanks for reporting this and check for duplicates :+1:
