### ISSUE TITLE
Spruce up entry fields

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gtk-communitheme#273]
What does everyone think of incorporating shadows into the entry fields as well? The colors are a little off in the gif, but this is what I'm proposing.

![peek 2018-03-22 10-12](https://user-images.githubusercontent.com/27529229/37775527-91209efc-2db9-11e8-9741-f5c45da89275.gif)

The sunken effect uses `inset 0 1px 2px 0 rgba(0, 0, 0, 0.1)`
The blured orange on focus uses `0 0 2px 2px transparentize($fc, .8);`

**Comment by clobrano** [comment]
I like it. How does it look like when hover on the linked button?

**Comment by godlyranchdressing** [comment]
![entry](https://user-images.githubusercontent.com/27529229/37776160-15bd39d0-2dbb-11e8-9fb7-d5ecd9ad810d.gif)

**Comment by madsrh** [comment]
@godlyranchdressing did you see the Hangout message on the hub or is this just a coincidence?

I like the orange glow too.

**Comment by madsrh** [comment]
Could you try making the border-top slightly darker?

**Comment by godlyranchdressing** [comment]
@madsrh this is how it actually looks, should I still darken the top border? ![untitled](https://user-images.githubusercontent.com/27529229/37779549-0b7e853e-2dc3-11e8-91cc-1b65eb66a133.png)

**Comment by madsrh** [comment]
@godlyranchdressing If so, I can't see it :confused:

I actually also applied the inner shadow to the button  [in my mockup](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/c/c2e09d588ff10f37ca18f22ae1b9d6a29ac16fa8.gif), but perhaps it makes sense to seperate them since we're also doing this with the **V** button hover shadow.

Here they both appear as #c9c9c9

![topborder](https://user-images.githubusercontent.com/3986894/37780940-114815a2-2df0-11e8-85f0-825a83ef7bb2.gif)

**Comment by didrocks** [comment]
It really looks good and crisps like this :)

**Comment by madsrh** [comment]
@godlyranchdressing I'm really conflicted regarding the orange glow :speak_no_evil: While it looks good here, I felt a bit different when I tried it with the latest update today. IMO it feels like it doesn't fit with the rest of the theme. I'm associating this with something "old school" again.

@luxamman ?

**Comment by fitojb** [comment]
The glows and shadows now make the theme look like an old version of Twitter Bootstrap :/

**Comment by CDrummond** [comment]
I really like the look of these entry fields **and** the look of buttons before 7579503

IMVHO, that change should be reverted (the dark bottom is weird) and the current entry look kept. The internal shadow of entries is consistent with the external shadow of buttons - and helps to differentiate between the two.

**Comment by madsrh** [comment]
I didn't notice this at first, but I'll have to agree with @CDrummond's [post here](https://github.com/ubuntu/gtk-communitheme/issues/288), that the before contrast was better.

I love the shadow inside the fields, but I'll have to say **-1** for the orange "glow" - it really looks out of place to me.

**Comment by CDrummond** [comment]
I love the glow, as its sort of an inverse to the shadow. When not active, the entry field has a sunken look. When active the glow kicks in and raises the field.

**Comment by CDrummond** [comment]
What about drawing the lighter shade inside? This is from KvCommunitheme

![kv](https://user-images.githubusercontent.com/1141694/38204224-eb7ea59a-3699-11e8-8547-0b7e3e93ef2e.png)

**Comment by fitojb** [comment]
When did suddenly the communitheme become all the rage about glows which aren't part of neither Adwaita nor Suru visual languages?

**Comment by NusiNusi** [comment]
no orange glow. only inner shadow (gray) and orange border. the theme uses only thin sharp orange lines.

**Comment by Feichtmeier** [comment]
I am a fan of this glow on a flat UI :+1:

**Comment by Feichtmeier** [comment]
I pretty sure this was fixed/reverted/ =)
