### ISSUE TITLE
Make menubar white

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#281]
Directly from **[jaggers3d](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/727)**'s post on the hub:

> … after playing around in GIMP, I’d like to express some support for pale menubars. They make the “black stripe” at the top of the window thinner, which means menubar apps are more consistent with the other kind.

![image](https://user-images.githubusercontent.com/3986894/37850447-6b6702a0-2edb-11e8-870c-d152c290e29f.png)

I absolutely agree that the current design sometimes feels like a wall of darkness at the top of the screen. @godlyranchdressing / @luxamman ?

**Comment by godlyranchdressing** [comment]
If anyone has any ideas/mockups that we can all agree on then great. I completely get the complaint, but I also don't like the dark titlebar and light menubar combo. Yeah, I can live with it, but it's one of those things that stick out and looks "unthemed" from regular Adwaita to me.

**Comment by madsrh** [comment]
@godlyranchdressing I'm not sure I understand 🤔 

Adwaita:
![adwitaarara](https://user-images.githubusercontent.com/3986894/37852033-5f2bb55c-2ee1-11e8-995e-afbfdaa2cf1e.gif)

**Comment by godlyranchdressing** [comment]
@madsrh to me it'll look like we forgot to update the light menubar (since the theme is based on Adwaita) to match the dark titlebar. I remember the use of blue in the theme got similar complaints: it looks unthemed/like something left over from adwaita.

I'll try to come up with something though.

**Comment by madsrh** [comment]
> I remember the use of blue in the theme got similar complaints

I understand what you mean @godlyranchdressing I remember that too, but I think this is different 😃

> I'll try to come up with something though

If it's not too much work, it would be great to try it, because it sometimes _feel_ different than what you can see in a screenshot/mockup.

**Comment by nana-4** [comment]
I think this means Firefox and Chrome's tab-bar also become light.

![image](https://user-images.githubusercontent.com/9556384/38165379-40e42c06-354d-11e8-9ce9-4219fce3c1e7.png)

Are you really okay with this? I'd definitely prefer the current dark menubar/tabbar.

**Comment by madsrh** [comment]
@nana-4 No, I do agree that the Firefox tab-bar looks a bit off here.

My problem (when considering decisions about design) is that in many cases, I'm not aware of the consequences when we make a change. So, even if IMO the [mockup ](https://user-images.githubusercontent.com/3986894/37850447-6b6702a0-2edb-11e8-870c-d152c290e29f.png)in the first comment looks really good (and I don't think that the white bar will look "unthemed"), I see the problem that now apears in Firefox.

Other "Firefoxes" exist in light versions ([this ](https://www.ghacks.net/wp-content/uploads/2016/09/firefox-xp-vista-end-of-support.png)or [this](https://images.techhive.com/images/article/2015/08/windows-10-firefox-100599858-large.jpg) or [this](http://i1-news.softpedia-static.com/images/news2/mozilla-firefox-40-released-with-windows-10-improvements-488972-2.jpg)) although I know that this isn't Linux and that we have a dark headerbar, but maybe adding a bit of gray (if possible) would make the light version look better?

I cannot make a "strong case" against the current dark menubar/tabbar, because I really like it too. 
When we agreed upon the dark menu design earlier, it was with Unity8 as inspiration and, as mentioned, the difference here with Gnome Shell is that Unity8 had global menus and a thin headerbar.
With a maximized window I still feel that there's a huge block darkness at the top of the screen, but then again, so is there in Ambiance.

Do you have any comments @Feichtmeier ?

> I'll try to come up with something though.

Should we still give this a try or is it a "won't fix"?

**Comment by tsujan** [comment]
I'm an outsider here and judge a theme only based on how it looks, not how some apps can't cope with it. The current dark menubar is elegant, IMHO -- unless you want to change this theme to a completely light one, without dark elements. The only bad thing is that dark menus go better with this theme and, definitely, with a dark menubar.

**Comment by Feichtmeier** [comment]
Missed this one, sorry:

I believe that the original author has a point with this one case where you have a non CSD application with a menu. Since then you have the shell titlebar, the window header bar and the menubar.
But if I would nail myself on an opinion, I would go with the dark menubar, since more and more apps, especially in gnome, come with CSD. 
Unity had global menus, which wiped this whole problem away with one solution. We could try to include the gnome extension https://extensions.gnome.org/extension/1267/no-title-bar/ by default, but this topic should be discussed elsewhere I guess (then we would only have two dark bars when maximized)

**Comment by madsrh** [comment]
Okay, reading through this thread, I don't see any reason to keep this issue open. Let me know if any of you feel differently 😃
