### ISSUE TITLE
Change disabled text color with orange background in lists

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#282]
Change disabled hover color for text in lists to #ee886e as the current (_the one in the bottom_) is very hard to read.
I used Ambiance for the mockup, but the color is the same in the Community Theme currently. See the comparison here:

![image](https://user-images.githubusercontent.com/3986894/37850835-f54a16f0-2edc-11e8-9013-6d2527634db0.png)

I also added a comment on [PR #172](https://github.com/ubuntu/gtk-communitheme/pull/172), but please disregard this now 😃

**Comment by madsrh** [comment]
This might be a bug in "language support". Could anyone point me to another application that has disabled text in a list or testing?

**Comment by nana-4** [comment]
Yes @madsrh, the "language support" app is hard-coding the disabled text color.

You can see the normal disabled-selected-text-color in `gtk3-widget-factory` while selecting a row and executing "Get Busy".

![peek 2018-03-31 18-39](https://user-images.githubusercontent.com/9556384/38161948-72b32c6c-3513-11e8-9e4a-0e2e34da03b7.gif)

**Comment by madsrh** [comment]
Closed, sorry for the noise
