### ISSUE TITLE
Some buttons dont have shadow

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#284]
Noticed that in Geary's account preferences dialog, the `Cancel` and `Save` buttons do not have a shadow.

![geary](https://user-images.githubusercontent.com/1141694/37866023-9682d544-2f7c-11e8-82f5-0a5a9e1dcc97.png)

**Comment by Feichtmeier** [comment]
It's strange - I remember having an issue with the pop gtk theme on this dialog, too.
Did you notice this anywhere else than on Geary?

**Comment by CDrummond** [comment]
@Feichtmeier Can't say that I have. Its odd that the other buttons in the dialog do have shadows.

**Comment by Feichtmeier** [comment]
Just checked it again and
