### ISSUE TITLE
Terminal color scheme

### ISSUE THREAD

**Issue by galgalesh** [Ubuntu/gtk-communitheme#29]
I'd like to discuss the terminal color scheme a bit. I did some research and surprisingly, there is only one "engineered" terminal color scheme: [Solarized](http://ethanschoonover.com/solarized). When you start using Solarized, you immediately feel that it is an extremely readable color scheme. It's very friendly for colorblind people because of the combination of both color wheel and lightness relationships. As a result, the difference between red and orange for example is still clear to me.

The Unity8 color scheme looks similar to Solarized, but it is a bit less clear, even though it is a lot better than the default Gnome color scheme. The Ambiance color scheme sits in between Solarized and Unity8 in terms of clarity.

Solarized dark is shipped with Gnome Terminal, but it is disabled by default. You can try it out in `edit>profile preferences>colour`.

**Unity8**

![screenshot from 2018-01-10 11-08-30](https://user-images.githubusercontent.com/1492981/34766992-e743cd18-f5f6-11e7-8710-65cc7d453688.png)

**Solarized Dark**

![screenshot from 2018-01-10 11-08-59](https://user-images.githubusercontent.com/1492981/34767007-efd9fbaa-f5f6-11e7-992d-67f919b7312d.png)

**Ambiance**

![image](https://user-images.githubusercontent.com/1492981/34767222-d9161222-f5f7-11e7-85a8-46a4d185aecf.png)

**next to each other**

(best to zoom in :wink: )

| Unity8        | Solarized Dark           | Ambiance  |
| ------------- |:-------------:| -----:|
| ![screenshot from 2018-01-10 11-08-30](https://user-images.githubusercontent.com/1492981/34766992-e743cd18-f5f6-11e7-8710-65cc7d453688.png)     | ![screenshot from 2018-01-10 11-08-59](https://user-images.githubusercontent.com/1492981/34767007-efd9fbaa-f5f6-11e7-992d-67f919b7312d.png) | ![image](https://user-images.githubusercontent.com/1492981/34767222-d9161222-f5f7-11e7-85a8-46a4d185aecf.png) |

I've been comparing them for the past few days and my preference goes out to using Solarized Dark, because it is simply the clearest color scheme. However, the disadvantage of that approach is that the color scheme isn't "branded".

What do you guys think?

**Comment by clobrano** [comment]
I'm in favor of Unity8 because of the lighter color of normal text (it's the same change I set every time I switch to Solarized)

Unity8:
![image](https://user-images.githubusercontent.com/2883614/34774693-9f6300e4-f610-11e7-9bc1-356d738ba336.png)

Solarized:
![image](https://user-images.githubusercontent.com/2883614/34774654-755594e2-f610-11e7-96f3-7e9d2be36e9c.png)

Solarized normal text color is way too similar to the background and after some time tiring to see.

**Comment by galgalesh** [comment]
My issue with that lighter color is that it looks too much like the blue:

Unity8

![image](https://user-images.githubusercontent.com/1492981/34775490-9b616d0c-f613-11e7-9b74-d73289959e4e.png)


Solarized:
![image](https://user-images.githubusercontent.com/1492981/34775501-aa1945d6-f613-11e7-9f9c-dd2b774f27a6.png)


Ambiance:
![image](https://user-images.githubusercontent.com/1492981/34775469-8860d0b2-f613-11e7-8cea-309e54a2d6cb.png)

Ambiance is a bit better than unity8 for this.

**Comment by godlyranchdressing** [comment]
In that case maybe we could darken the text color and make the background color a little transparent? That  will lead to the darker text color standing out a tiny bit more (and being closer to Unity 8). We could do a commit and have a trial run and always default to the purple if we don't like it.

**Comment by clobrano** [comment]
I understand. Moreover, the Ambiance background is distinctive of Ubuntu.

**Comment by didrocks** [comment]
I personnally have some issues distiguishing the text with Solarized compared to Unity8 (so, quite the opposite from galgalesh…). I generally prefer the Ambiance background where the constrast is the best, but it may not work well with the rest of the theme though. Remember that transparent background is a distro patch (shared by fedora, ubuntu and a lot of other distros), and if just subtule, generally works well.

**Comment by galgalesh** [comment]
@godlyranchdressing which color scheme are you talking about? :thinking: 

@didrocks which text do you have difficulties with?

**Comment by didrocks** [comment]
@galgalesh the regular text color (white/greyish one)

**Comment by galgalesh** [comment]
Interesting to note: The unity8 terminal color scheme is actually derived from solarized: https://design.canonical.com/2016/08/convergent-terminal/

**Comment by kq01526** [comment]
> @Luxamman wrote in https://github.com/Ubuntu/gtk-communitheme/issues/90 :
> Like already discussed, change the terminal colors back to the typical Ubuntu style, as it is a too big part of branding and recognition value.

With "Ubuntu style", are you referring to "Unity 8" or "Ambiance"?

Unity 8:
![https://user-images.githubusercontent.com/1492981/34775490-9b616d0c-f613-11e7-9b74-d73289959e4e.png](https://user-images.githubusercontent.com/1492981/34775490-9b616d0c-f613-11e7-9b74-d73289959e4e.png)

Ambiance:
![https://user-images.githubusercontent.com/1492981/34775469-8860d0b2-f613-11e7-8cea-309e54a2d6cb.png](https://user-images.githubusercontent.com/1492981/34775469-8860d0b2-f613-11e7-8cea-309e54a2d6cb.png)

**Comment by Luxamman** [comment]
> With "Ubuntu style", are you referring to "Unity 8" or "Ambiance"?

Ambiance

**Comment by kq01526** [comment]
> @Luxxamman wrote:
> Ambiance

Whooops :slightly_smiling_face: , but the Ambiance terminal theme uses aubergine color for the background. Wait, didn't you say:

> @Luxamman wrote in https://github.com/Ubuntu/gnome-shell-communitheme/issues/54:
> Aubergine has no meaning in the UX because it's never been used and the user is therefore not used to it. Also, aubergine is the Canonical brand color, which is used for "consumer or enterprise focus". This is not excluding it, but also not favor it. But it would mean another strong (and very present) color and people have to get used to it.

?

:slightly_smiling_face: 

Looking forward to the explanation to this... :slightly_smiling_face:

**Comment by madsrh** [comment]
@kq01526 How is that comment constructive in any way? What could the Ubuntu project possible gain from you pointing fingers at Luxamann (no matter if you're right or wrong)? Read the response from galgalesh again and **PLEASE** only comment if you have value to add to the conversation!

**Comment by kq01526** [comment]
> @madsrh wrote:
> What could the Ubuntu project possible gain from you pointing fingers at Luxamann (no matter if you're right or wrong)?

How is @Luxamman 's comment constructive in any way? One time he says aubergine has never been used in Ubuntu UX and has no further meaning for the user and is not part of the Ubuntu brand. Another time [he commands you to stay with the aubergine background in the terminal "as it is a too big part of branding and recognition value"](https://github.com/Ubuntu/gtk-communitheme/issues/90).

This is a big contradiction. How exactly does it make sense? And how exactly is this helping communitheme?

And why would it be bad to bring up and discuss this issue here in a thread that deals with terminal color?

Anyway, even having to ask these questions probably means [`sudo apt install gnome-session`](https://www.omgubuntu.co.uk/2017/10/install-vanilla-gnome-shell-ubuntu-17-10) seems to be the way to go.
