### ISSUE TITLE
Buttons in Headerbar receive a grey background after they lose focus for a short time

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#290]
![peek 2018-03-25 22-23](https://user-images.githubusercontent.com/15329494/37879568-4b3c9944-307b-11e8-984e-572afff5a354.gif)

This came up after the latest terminal changes (no idea if there is  connection)

**Comment by Feichtmeier** [comment]
@clobrano I wonder if this has something in common with the transistion time of active/backdrop windows? 
I can't really test stuff because in my VM the animations are so heavily reduced that I don't see any transistion animation :octopus:

**Comment by clobrano** [comment]
@Feichtmeier I think the culprits are these lines that have been changed with the last button update

https://github.com/ubuntu/gtk-communitheme/blob/1da65ce48f098f171a2674b8f7c94cf229a6072c/Communitheme/gtk-3.0/_drawing.scss#L212
https://github.com/ubuntu/gtk-communitheme/blob/1da65ce48f098f171a2674b8f7c94cf229a6072c/Communitheme/gtk-3.0/_drawing.scss#L254

backdrop transition is easy-out and with different timing. I'd like to fix this with the new button styling. Let's wait for @nana-4

**Comment by Feichtmeier** [comment]
There that other transistion issue with the calendar seperator in the shell theme:

@clobrano @godlyranchdressing 
How about defining some global transition times in _colors.scss or an additional .scss file or just at the top of both (gtk and shell) _common.scss? I find it hard to track all those times in the _common.scss at the moment :(

**Comment by clobrano** [comment]
There is already a global transition variable in common.scss, the problem comes from the new transition definition in drawing.scss

**Comment by clobrano** [comment]
Sorry, closed by mistake

**Comment by Feichtmeier** [comment]
![peek 2018-04-27 14-28](https://user-images.githubusercontent.com/15329494/39362625-63b53e52-4a27-11e8-8eaf-47f7b79cdf79.gif)
@clobrano after some of the latest merges it went away on most apps but it is still there, strangely only in some apps, like for example system monitor.

**Comment by clobrano** [comment]
Yes, I noticed it too :(

**Comment by clobrano** [comment]
closing this now, we can reopen it when it is evident that's something that depends on communitheme
