### ISSUE TITLE
Titles of inactive non-headerbar windows unreadable

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#292]
The titlebar text of any window non use GtkHeader bar (e.g. GNOME terminal, any Qt app, any Gtk2 app) is set to a very dark shade of gray - making it impossible to read its title.

Screen shot of GIMP main window and prefences window. As you can see, the title of the main GIMP window is unreadable.

![gimp](https://user-images.githubusercontent.com/1141694/37921430-b47ed092-3121-11e8-9853-53470a2aee25.png)

Note: This is not a Gtk2 issue - the titlebars are drawn by the window manager (which used the Gtk3 theme)

**Comment by clobrano** [comment]
Thanks @CDrummond :wink:

**Comment by clobrano** [comment]
I've spent some time yesterday, but I didn't figure out from where that color came. I'll try again today or the next days with some bisect to check when this issue appeared

**Comment by CDrummond** [comment]
Not sure if this helps much, but:

Revision: 777894cd63ccbf9e8b0d8653ff7eeaa6b601f02a is OK, next revision (afe9d1f38533b324f417ee4efc02dc2ef9176042) is not. However, I have tried just reverting these changes - and still have the same issue :-(

**Comment by clobrano** [comment]
> Revision: 777894c is OK

That's weird, because I cannot confirm that, even going back to January, I still have this error :worried: 
Could it be something to do with bionic dependencies?

**Comment by CDrummond** [comment]
Well, I'm still on 17.10 (and install manually). I assume you restarted GNOME shell each time?

**Comment by clobrano** [comment]
> I assume you restarted GNOME shell each time?

No, I'll try again later today
