### ISSUE TITLE
Depends: gnome-themes-extra

### ISSUE THREAD

**Issue by Evire** [ubuntu/gtk-communitheme#293]
Hi, trying to install following the instructions, but I get the error:

$ sudo apt install ubuntu-communitheme-session
ubuntu-communitheme-session : Depends: gtk-communitheme but it is not going to be installed

$ sudo apt install gtk-communitheme
gtk-communitheme : Depends: gnome-themes-extra but it is not installable

Isn't the dependency supposed to be gnome-themes-extra**s**?

Thanks.

**Comment by madsrh** [comment]
Hi @Evire. Thanks for taking the time to report this issue. Which version of Ubuntu are you running?

**Comment by Evire** [comment]
@madsrh I read the other closed issues, seems like the support for Aardvark has ended.
