### ISSUE TITLE
File dialog path bar inconsistent with nautilus

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#295]
The path bar used in the GtkFileChooser dialog is inconsistent with that in Nautilis:

1. Inactive parts use a lighter grey text - and look disabled. In Nautilus they still look white and normal weight. Perhaps in Nautilus they are still a different shade (hard to tell) - but they do not look disabled.
2. The current folder is drawn using standard text colour and weight. In Nautilus the current folder is drawn using a bold font

I think the file chooser should follow Nautilus's lead - i.e. same colour text for all items, and use bold for the current folder.

File chooser:
![fd](https://user-images.githubusercontent.com/1141694/38083899-d7e11202-3342-11e8-8629-7a4eac64b675.png)

Nautilus:
![n](https://user-images.githubusercontent.com/1141694/38083908-de6fad9a-3342-11e8-9d58-b4d3609ca3a2.png)

**Comment by clobrano** [comment]
I still didn't investigate the mechanism, but it look like filechooser takes just some elements from pathbar and inverts the colors

**Comment by madsrh** [comment]
@CDrummond Perhaps like this: Bold for the current folder and a bigger contrast between disabled elements (only the arrows here <>) and clickable ones.

![-](https://user-images.githubusercontent.com/3986894/38161856-af39739a-34d6-11e8-82ec-36bd82689181.jpg)

**Comment by CDrummond** [comment]
Whilst this is an improvement, why does it need yet another different text colour? Why not just have all the text elements the same colour? The active one is bold with an underline - so its obvious which is active. Not sure why the others need to be made even less active.

IMVHO - here, and in the nautilus path bar, the text elements should have the same colour. Just use bold + underline for the active element.

**Comment by madsrh** [comment]
It should have been only the deactivated text the was another color, so +1. I was going for the same color, just bold for active. Sorry if that wasn't clear.

**Comment by Feichtmeier** [comment]
There is another issue active on this so we can close this and discuss everything in the other issue:
https://github.com/ubuntu/gtk-communitheme/issues/357
