### ISSUE TITLE
Fill groove of sliders with tick marks?

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#305]
Currently the 'used' area of non-tick mark sliders is filled in blue. But not for sliders with tick marks. Why is this? Should they both not be the same?

![gtk](https://user-images.githubusercontent.com/1141694/38178084-eda90898-3602-11e8-8e56-a231cbd93177.png)

**Comment by madsrh** [comment]
@CDrummond This is the slider used to pan speakers left/right (and properly other things I can't think of), so it's a bit different from the volume slider. 

I'm closing this issue! Feel free to reopen if you disagree 😃 

![image](https://user-images.githubusercontent.com/3986894/38209755-a2daf94e-36b5-11e8-8f9a-9417af634b1a.png)

**Comment by CDrummond** [comment]
Ah, its gtk3-widget-factory that is not filling it for these types. Just noticed the icon size setting for Ubuntu dock in GNOME settings has tick marks, and fills in used portion.
