### ISSUE TITLE
Pathbar of unfocused window is inconsistent

### ISSUE THREAD

**Issue by galgalesh** [Ubuntu/gtk-communitheme#31]
Focused

![image](https://user-images.githubusercontent.com/1492981/34818190-6467dd8e-f6ba-11e7-8e1f-6e3bfd949c54.png)

Unfocused

![image](https://user-images.githubusercontent.com/1492981/34818213-753154ec-f6ba-11e7-8cd0-50f6b492b203.png)

I think the solution is to darken all the buttons on the pathbar on unfocused windows since it seems to be common for elements to apear "inactive" when the window is unfocused. Example in gnome tweaks

Focused

![image](https://user-images.githubusercontent.com/1492981/34818302-af2772da-f6ba-11e7-8f3d-00947ded2c64.png)

Unfocused

![image](https://user-images.githubusercontent.com/1492981/34818309-b548c100-f6ba-11e7-8c28-be715b892efc.png)

Although now that I look at it, there seems to be a tiny difference between active and disabled buttons on inactive windows.

**Comment by madsrh** [comment]
Wouldn't this make sense?

![d80fdc4b9e3240cb60066a11a6a0737078ef4437](https://user-images.githubusercontent.com/3986894/34832231-90659776-f6e9-11e7-9f0e-9987cb34fa73.gif)
