### ISSUE TITLE
Minor graphical issue on GTK+ window

### ISSUE THREAD

**Issue by cialu** [ubuntu/gtk-communitheme#311]
Hi all,

I'm testing Ubuntu 18.04 LTS with the communitheme and using GTK+ software like Remmina, I found a minor graphical issue on the main window. It's about a round corner under the title tab, where it's not supposed to be. I don't know if this is an issue related specifically to the theme or to the application. I post a picture to explain better the issue.

![commtheme](https://user-images.githubusercontent.com/1382127/37329151-dc3aab86-269c-11e8-8919-af1131333409.jpg)

**Comment by clobrano** [comment]
This is weird. Remmina is using a headerbar **inside** a box. Usually headerbars are at the top of the window, this is why they have rounded border. Probably it should use a toolbar instead

![image](https://user-images.githubusercontent.com/2883614/38274497-38e2e968-378f-11e8-82d8-459612fb1f34.png)

Any chance you could report this upstream?

**Comment by cialu** [comment]
> Any chance you could report this upstream?

Sure.

**Comment by clobrano** [comment]
Done. Let's see what they say

**Comment by clobrano** [comment]
Fixed upstream https://github.com/FreeRDP/Remmina/issues/1546
let's wait for it to be released. Closing this now
