### ISSUE TITLE
close button in chrome is scaled up and blurry 

### ISSUE THREAD

**Issue by tklevenz** [ubuntu/gtk-communitheme#314]
![community-theme-closebutton-chrome](https://user-images.githubusercontent.com/3456728/38306848-1ef9752a-3812-11e8-9ed9-adc4c11c4fb0.png)

The community theme currently uses an image to render the close button, which in chrome causes it to appear blurry, as it is being scaled up. Other themes like Pop or Ambiance do not have that issue, as they draw the button without using an image.

**Comment by clobrano** [comment]
Unfortunately orange circle image is necessary in order to have both the circle and the background color change on hover
![image](https://user-images.githubusercontent.com/2883614/38317595-b0291f3a-382d-11e8-9135-e0809b453c25.png)

**Comment by Feichtmeier** [comment]
As a first step we could increase the size of the svg file, as @nana-4 suggested for a different issue in the shell overview so the blurryness would decrease.
I believe this happens because chrome scales up the window controls.

**Comment by clobrano** [comment]
> I believe this happens because chrome scales up the window controls.

Agree, I did a little test and chrome disregards background-size property

**Comment by tklevenz** [comment]
How about using SVG instead of PNG for the close buton, it'll still be scaled up in chrome, but it won't be blurry.

**Comment by clobrano** [comment]
We're about to make a change of image for close button, so I think we can test both (not sure svg image can be used though, I should try)

**Comment by Feichtmeier** [comment]
The blurry part is gone since https://github.com/ubuntu/gtk-communitheme/pull/323
For the scale up part, I fear if this would be rather a chrome issue? They scale up the whole button.
Not sure if we should fix general elements for just one application

**Comment by clobrano** [comment]
Just installed chrome and I see no problem

![image](https://user-images.githubusercontent.com/2883614/39394084-e06479d0-4acd-11e8-92c0-942d2d0701e0.png)

could we close this now?
