### ISSUE TITLE
Remove orange from window control close button

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#319]
As discussed in various places, we will remove the orange from the close button, so that it only appears when hovered (along with the background highlight as it currently does).

There's many reasons both for and against, so this change might not be indefinitely - but for now there's consensus for giving this a try.

![image](https://user-images.githubusercontent.com/3986894/38466036-711e9358-3b23-11e8-99ad-435e0f4136e5.png)

**Comment by Feichtmeier** [comment]
@madsrh like this?
![peek 2018-04-10 13-33](https://user-images.githubusercontent.com/15329494/38554698-df640a2c-3cc3-11e8-980e-8a7a3a6d2bce.gif)

**Comment by madsrh** [comment]
@Feichtmeier LGTM

**Comment by clobrano** [comment]
@madsrh @Feichtmeier, this way close button would be the only button with an effect on backdrop

**Comment by madsrh** [comment]
Sorry, I was a little fast on the reply buttpn - I didn't see that the first part was in backdrop. @clobrano is right 👍

**Comment by NusiNusi** [comment]
@Feichtmeier should i open a new ticket for this or is this not necessary?:
![peek 2018-04-11 20-43](https://user-images.githubusercontent.com/36449926/38636642-16afbb38-3dc9-11e8-97fe-d50cc7659cd3.gif)

**Comment by Feichtmeier** [comment]
Yup saw that myself. Pretty strange. I wonder if this has anything in common with the @2.png files :|
Yes please open a new issue so I can track it

**Comment by Feichtmeier** [comment]
Closing this as this mockup is implemented, using the other issue for the bug

**Comment by taciturasa** [comment]
honestly, this looks terrible, with both hover states. If you're going to remove the orange from nonhovered, go ahead and remove it from on hover too. or, make all button hovers be circular and remove the bigger hover.
