### ISSUE TITLE
Dark theme colors

### ISSUE THREAD

**Issue by tsujan** [ubuntu/gtk-communitheme#320]
ubuntu will get stable soon and I don't know if reports could be useful anymore. I wanted to start a matching Kvantum theme for the dark variant of communitheme but saw an incongruence: While none of the bg colors of communitheme is bluish and its selection color is orange, the bg color of the dark variant is bluish (red: 28, green: 27, blue: 33).

Ubuntu has favored red/orange/brown; hence the incongruence, IMO.

EDIT: some color like `#2d2723` might be more suitable for Ubuntu.

**Comment by tsujan** [comment]
> Not sure about the color you suggested, since it's very dark

It was just an example; I didn't use it to see the effect. Anyhow, a smaller B in RGB seems better for Ubuntu.

**Comment by godlyranchdressing** [comment]
The darkish blue is taken from Suru/Unity 8's dark theme though it's pretty much just a placeholder color at this point as the dark theme was never really discussed/actively worked on.

**Comment by tsujan** [comment]
Thanks for the info! I won't make a matching Kvantum theme until the dark variant is really a dark variant.

**Comment by godlyranchdressing** [comment]
@tsujan @clobrano 

How about #403D3D for $base_color and #383535 for $bg_color? ![darktheme](https://user-images.githubusercontent.com/27529229/38890538-b69288f8-424f-11e8-8621-43f309306d3c.png)

**Comment by tsujan** [comment]
> godlyranchdressing

Very nice, IMO.

**Comment by tsujan** [comment]
However, bg and fg colors aren't enough. Slider handles/troughs should also be changed; some other elements too.

**Comment by clobrano** [comment]
Colors look good to me as well. I don't see the urgency of changing the handles, but I'm using my mobile phone now, so... :D

**Comment by godlyranchdressing** [comment]
The consistent $dark_fill background and white colors for sliders don't look as good with the brown as with the dark blue to me. Maybe we should get rid of it? @madsrh
