### ISSUE TITLE
GTK2 apps aren't themed in the snap

### ISSUE THREAD

**Issue by didrocks** [ubuntu/gtk-communitheme#322]
Probably an issue with libadwaita and/or the pixbuf engines not respecting XDG_DATA_DIRS. Need digging through.

**Comment by didrocks** [comment]
Should be fixed in https://github.com/ubuntu/communitheme-snap-helpers/pull/3

**Comment by didrocks** [comment]
Merged now.

**Comment by nicocarbone** [comment]
Sorry if this is not the right place to ask, but I still have this problem (GTK2 apps like inkscape and GIMP are not themed). I see this is closed and the fix merged though. Is there anything else I need to do on my end?
