### ISSUE TITLE
Chromium tabs outline is almost black when window not focused, looks very strong

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu/gtk-communitheme#324]
It doesn't look wrong, but the contrast is a tad too strong to my eye. See the difference when the window is focused, and when it's not:

![chromium-active](https://user-images.githubusercontent.com/11027549/38559679-f38ec446-3cd3-11e8-9c67-f15592b36906.png)

![chromium-passive](https://user-images.githubusercontent.com/11027549/38559683-f761737a-3cd3-11e8-8278-65126b536baa.png)

**Comment by Feichtmeier** [comment]
While we came to the conclusion that we don't want to change global code for individual apps, I try to find the part of the gtk theme which changes these tabs in chromium

**Comment by godlyranchdressing** [comment]
I'm starting to think this might be something Chrome does on its own and not something we can change outside of changing the menubar color so maybe #392 might give us a better result.

**Comment by Feichtmeier** [comment]
@godlyranchdressing yep, that problem in other themes. Closing this for now
