### ISSUE TITLE
Evince has a totally invisible gui with the snap theme

### ISSUE THREAD

**Issue by nicocarbone** [ubuntu/gtk-communitheme#325]
![captura de pantalla de 2018-04-10 15-14-17](https://user-images.githubusercontent.com/9342423/38575531-078db508-3cd2-11e8-888d-5a564cdf14e3.png)

Since changing from the ppa to the snap, evince has a transparent GUI, as seen in the screenshot.
Also, when starting evince from the terminal, I get a permission denied error:

`Theme parsing error: gtk.css:1:0: Failed to import: Error al abrir el archivo /snap/communitheme/current/share/themes/Communitheme/gtk-3.0/gtk.css: Permiso denegado`

**Comment by frenchy82** [comment]
Hi, i have the same problem with gnome-calculator installed from snap.
Gui is invisible.

**Comment by minghuaw** [comment]
Same issue here, and apparently many gnome default applications such as printing, system monitor are also affected. Totally transparent window frame. Was this issue ever present in the ppa installations?

**Comment by Feichtmeier** [comment]
Can't confirm the issue on system monitor.
Would be good if we somehow try to debug until we limited the possibilites.

Could you guys check if those applications are a snap?
I only have this issue on evince and it's from the regular repo installation

**Comment by frenchy82** [comment]
I have the problem with evince too, and it's  an apt installation
same problem with logs and characters but it's a snap

and there is no problem with gnome-calculator if it's installed by apt

**Comment by minghuaw** [comment]
Looks like there will be permission issues with default snap install, as it will install the package into a sandbox. Somehow `snap refresh communitheme --classic ` or `snap refresh communitheme --edge` will allow evince to have a GUI that's in a different theme.

**Comment by didrocks** [comment]
So, there are 2 things here:
* evince, which is protected by apparmor, isn't allowed to read the theme snap dir. Needs fixing.
* the other mentioned are snap, I'll talk to the snapd theme to try adding the communitheme snap dir to allowed directories for the desktop interface.

**Comment by didrocks** [comment]
For evince (and other deb applications protected by apparmor), the fix is submitted as https://salsa.debian.org/apparmor-team/apparmor/merge_requests/5.

Snap will need a little bit of discussions (later today)

**Comment by didrocks** [comment]
Posted a patch + discussion for snaps on https://forum.snapcraft.io/t/snap-using-themes-in-other-snaps/4946

**Comment by nicocarbone** [comment]
Some of my snap apps (calculator, for example) appears invisible. But others (KeePassXX, for example) appears with a different theme (adwaita, I think). Do you why the difference? Can both problems be resolved by the same patch?

**Comment by nicocarbone** [comment]
Ok, I think I get the idea. 
Is there a way of setting a "fall-back" theme in the snaps? If not, what will happen with third-party themes and snap apps?

**Comment by Alculete** [comment]
My libreoffice.snap has the same issue but instead of invisible background I get black background with if icons almost translucent and some above others

**Comment by didrocks** [comment]
@nicocarbone: that's a question for the snapd team itself. I think they won't be supported until snapd treats theme in a special way. I encourage you to bring those use cases to https://forum.snapcraft.io/ to discuss with them (the communitheme one won't be an issue soon as we'll ship this big snap, but for other cases, that will still be an issue)

**Comment by nicocarbone** [comment]
Any ETA with the evice/apparmor bug? I understand that snap theming may take a while longer, but the apparmor fix seems straightforward.

**Comment by nicocarbone** [comment]
Another question, sorry if this is too off-topic: is there any plan to create a flatpack for the theme? I understand that flatpack may not be officially supported, but given that flathub already has an interface in place for themes, it may be worth the effort.

**Comment by didrocks** [comment]
I pinged the apparmor (debian and ubuntu) maintainer again today for my fix. I can't give an ETA for him though :p
You can applied the fix locally and regenerate the apparmor profile manually in between.

On the flatpak question, no plan from me (I won't really have time for this), but anyone who wants to flatpak the theme and push it to flathub are welcome to work on this, ofc.

**Comment by nicocarbone** [comment]
The fix living in the proposed channel works fine. Thanks! :)

**Comment by didrocks** [comment]
and it's now released (for the evince part). The snap part will come once the new snaps using GNOME 3.28 for 18.04 using my gtk-common-theme snap is release.

**Comment by didrocks** [comment]
As the evince part is closed and a more precise duplicate is opened, I'm now closing this one.

**Comment by octopus-prime** [comment]
Any progress here? Calculator is still transparent.
![bildschirmfoto von 2018-07-10 12-47-36](https://user-images.githubusercontent.com/7620013/42505655-b3bb0240-843f-11e8-956d-4ff1f4e3791f.png)

**Comment by Feichtmeier** [comment]
@octopus-prime yes you need to install
sudo snap install gtk-common-themes
Then reboot to be sure

**Comment by octopus-prime** [comment]
`sudo snap install gtk-common-themes`
->
`snap "gtk-common-themes" is already installed, see 'snap help refresh'`

**Comment by Feichtmeier** [comment]
Reboot?

**Comment by Feichtmeier** [comment]
It's fixed. Check the other thread

**Comment by octopus-prime** [comment]
Works now. Thank you!

**Comment by cassianomon** [comment]
@Feichtmeier which other thread?

**Comment by cassianomon** [comment]
Solved by:
`sudo snap remove gnome-calculator`
`sudo apt install gnome-calculator`
`sudo snap remove gnome-system-monitor`
`sudo apt install gnome-system-monitor`
