### ISSUE TITLE
Inconsistency on radio-buttons and checkmarks

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gtk-communitheme#334]
They look like this:
![bildschirmfoto vom 2018-04-14 09-57-38](https://user-images.githubusercontent.com/36449926/38765913-6d4b0e04-3fca-11e8-841c-ab26487f916b.png)

But on menus they look like this (inverted?):
![bildschirmfoto vom 2018-04-14 10-01-18](https://user-images.githubusercontent.com/36449926/38765952-17152bb8-3fcb-11e8-9ab0-622e3040f1dd.png)
LibreOffice:
![bildschirmfoto vom 2018-04-14 10-02-26](https://user-images.githubusercontent.com/36449926/38765955-1e1ffd5c-3fcb-11e8-9b0f-acd2b49eff57.png)

Shouldn't they all look like in the first picture?

**Comment by godlyranchdressing** [comment]
The checkbox style in menus and popovers are [from Canonical's design](https://github.com/Ubuntu/gtk-communitheme/issues/162#issuecomment-365567805) and there was consensus on keeping it.

**Comment by NusiNusi** [comment]
Aha! I have not seen this. So close this issue?
