### ISSUE TITLE
Removing orange glow-effect on enterfields

### ISSUE THREAD

**Issue by NusiNusi** [ubuntu/gtk-communitheme#335]
![bildschirmfoto vom 2018-04-14 10-15-34](https://user-images.githubusercontent.com/36449926/38766075-093404c2-3fcd-11e8-8510-4374f453d84d.png)

Reasons for removing the glow (the orange border-line stays):
- The theme uses orange mostly in thin clean sharp lines (sidebar soon hopefully too). Removing the glow would make it fit more to the rest of the themes style. See:
![bildschirmfoto von 2018-03-29 18-08-05a](https://user-images.githubusercontent.com/36449926/38766100-6c1a1bf8-3fcd-11e8-9079-2fc80656dbb7.png)
- The glow seems to combine orange and transparency. On a white or bright gray background it looks more like salmon or even pink. Same effect (but of course not this strong) we had with selected text color. See: #307 -> this means it looks not so "orangey" how it is intended.

**Comment by fitojb** [comment]
Really, there is no place for glows in this theme; it makes me cringe. It makes it look so 2009-era Twitter.
