### ISSUE TITLE
Backdrop title color for apps that use dark theme

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gtk-communitheme#338]
Window titles in apps that use the dark theme (totem, etc.) have a dark text color when in backdrop. It comes from this line: `label:backdrop { color: inherit; } // make sure to inherit the backdrop label color`. 

Is that line safe to remove? I don't want to remove it if it fixes another issue.

**Comment by clobrano** [comment]
@nana-4 you introduced this line with commit 914aa28c: Fix backdrop dark text color on headerbar
Could you answer to @godlyranchdressing?

**Comment by godlyranchdressing** [comment]
Seems to be working fine since some previous commit.
