### ISSUE TITLE
Backdrop text colors are too light

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gtk-communitheme#341]
Backdrop text colors are too light. 

![afeas](https://user-images.githubusercontent.com/27529229/38891756-4071068c-4253-11e8-88cc-05e556d7d3da.png)

Menubar text color becomes lighter in backdrop too:
![menu](https://user-images.githubusercontent.com/27529229/38891801-6a2293f6-4253-11e8-9330-045117f9b2cf.gif)

**Comment by godlyranchdressing** [comment]
@clobrano That's the GTK3 Widget Factory, but it happens with any menubar. I was about to make a PR that reverts $backdrop_fg_color and $backdrop_text_color. I'm still pretty behind so if these changes were to patch any issues I don't know of then maybe we can revert and try another way.

**Comment by clobrano** [comment]
I think it's just a side effect of the last changes on buttons. I'm working on it as well, but not reverting specific changes

**Comment by clobrano** [comment]
fixed by  #356
