### ISSUE TITLE
Checkboxes clipped in listview

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#343]
This _might_ just be an issue with Ubuntu updater (so app specific), but the checkboxes are being clipped:

![screenshot from 2018-04-18 07-35-04](https://user-images.githubusercontent.com/1141694/38915389-5e173476-42db-11e8-9917-b34a6b936c36.png)

**Comment by Feichtmeier** [comment]
Yes! That bugs me too. I believe I opened an issue for this. I believed to see the it went away and closed the issue -.-

**Comment by godlyranchdressing** [comment]
Weird. I thought the issue was resolved too. Maybe it's only when there's two categories of updates?
![clip](https://user-images.githubusercontent.com/27529229/39000700-a65da49e-43c2-11e8-9c2c-8cb989150f03.png)

**Comment by Feichtmeier** [comment]
Either we theme for this app only or we report it in launchpad
https://launchpad.net/update-manager

**Comment by godlyranchdressing** [comment]
@Feichtmeier The update manager doesn't seem to use any unique IDs or classes, so we can't target it directly unfortunately. So the only option would be to call it a bug or redo checkboxes.

**Comment by Feichtmeier** [comment]
I would not redo checkboxes because of this rather atypical application. As far as I remember all the update mechanisms should be integrated into gnome software at a point? @didrocks correct me if I am wrong
Would be the best if @CDrummond reports this at paunchpad and then closes this issue here after

**Comment by CDrummond** [comment]
Done. https://bugs.launchpad.net/ubuntu/+source/update-manager/+bug/1767679

**Comment by didrocks** [comment]
It should be integrated at some point, indeed, but there is no timeline yet. So, I guess, don't rely on this for communitheme, and makes as if the app will still be around.

**Comment by fitojb** [comment]
Yaru’s checkboxes are oversized, sorry.

**Comment by Feichtmeier** [comment]
That's funny: there is a part in the code where the comment says that it decreases the size of the checkboxes. But actually it increases the checkboxes this way ^.^ 
Ah here it is: https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.0/_common.scss#L3054
