### ISSUE TITLE
Apps opened with root permission don't use snapped communitheme 

### ISSUE THREAD

**Issue by nicocarbone** [ubuntu/gtk-communitheme#345]
Since changing from the ppa to the snap, apps started with root permissions use adwaita instead of communitheme.

For example, running `sudo nautilus` results in a nautilus window using adwaita while opening nautilus without sudo results in a window using communitheme.

**Comment by didrocks** [comment]
Yeah, there isn't any real fix for that I can stich in 18.04 (it would mean adding to the system path the snap entry, which we don't really want…)
`sudo app` is something prohibited and bad practice anyway. Remember that it's not even supported on wayland.

Meanwhile, people can use `sudo -E <app>` if they really want to do that. So closing as won't fix, sorry.

**Comment by nicocarbone** [comment]
Understood completely. Thanks!
