### ISSUE TITLE
Incorrect menu bar color on some applications

### ISSUE THREAD

**Issue by chaNcharge** [ubuntu/gtk-communitheme#349]
Environment: Ubuntu 18.04 final beta
Version: 0.1 revision 70

This also occurs when I'm on the edge or stable channel. I remember it being black before I updated it.
Does not happen when on normal Ubuntu desktop
![image](https://user-images.githubusercontent.com/11594018/39078997-61f97606-44c7-11e8-86f2-653db6b394df.png)

**Comment by clobrano** [comment]
Using communitheme installed from source code, menubar is black in fact

**Comment by chaNcharge** [comment]
Interesting. Is it something specific to the snaps or has something gone wrong with my ubuntu setup?

**Comment by clobrano** [comment]
It is probably the snap, but I cannot confirm right now, I need a VM to test this since I use my main machine with communitheme from source for development

**Comment by Feichtmeier** [comment]
I believe this got fixed by @didrocks 
Maybe you need an additional package. I believe gtk-communitheme

**Comment by chaNcharge** [comment]
Looking in apt and snap, no gtk-communitheme.

**Comment by chaNcharge** [comment]
Can confirm this only happens when using the snap, does not reproduce when used from source.

**Comment by Feichtmeier** [comment]
Yeah it's snap. I installed it via git and I have the menu colored in vscode

**Comment by nicocarbone** [comment]
This workaround also solves #358 . Maybe it is something more generalized? Or Gimp, Inkscape and Fillezilla also don't honor XDG_DATA_DIRS?

**Comment by chaNcharge** [comment]
It's most likely an issue in Electron, since it appears to happen in other apps besides VSCode. Someone should probably file a bug there.

**Comment by didrocks** [comment]
I agree that it may be an issue for electron apps. I'm more puzzled for gtk2 ones though, which used to work (and still work on my machines). I'll try in a clean vm tomorrow (would be great to have someone trying as well).
I heard that snap rev 49 was working, is anyone volunteering trying the various snap revisions and bisect when it started to break?

**Comment by didrocks** [comment]
Ok, I found the issue. Electron apps are using gtk2 styling, so the 2 issues were indeed related.
Do you mind trying the instructions on https://github.com/ubuntu/communitheme-snap-helpers/pull/8#issuecomment-384179997 and keep me posted if this works for you guys?
You need to logout/log back in after updating the snap (and remove any workaround you applied).

**Comment by didrocks** [comment]
The fix is now in master for the wrapper session and in revision 97 published to stable and edge channels of the snap!

**Comment by chaNcharge** [comment]
Just a quick question, is the ppa updated as regularly as the snap? I feel like the ppa runs better for me in terms of stability and usability.

**Comment by didrocks** [comment]
The ppa for 18.04 is going to be decomissionnned, as it's doesn't have automated tests contrary to the snap where we control the release process.
Also, it's released once a day and not per commit, so harder to bisect if an issue happened.

The only missing part of the snap is to be able to theme other snaps, but this is going to be very soon fixed as disucssed on various threads. Then, we'll remove the daily build from the ppa.
