### ISSUE TITLE
Dock and Headerbar backgrounds not coordinated

### ISSUE THREAD

**Issue by wandrewkeech** [ubuntu/gtk-communitheme#352]
On build 71, it is possible to get the Dock to grey the background before hiding, but the headerbar remains transparent. This looks amazingly weird to me and think the previous behavior of the background between both Headerbar and Dock being coordinated was nicer. I do also really like the transparent headerbar with the Dock hidden, and I suspect this issue is a byproduct of that change.

![screenshot from 2018-04-22 08-26-49](https://user-images.githubusercontent.com/7744003/39096766-f46b9e96-4608-11e8-98a1-18563160900d.png)

**Comment by wandrewkeech** [comment]
Issue remains on snap build 73.

**Comment by Feichtmeier** [comment]
Thanks for taking your time to report this. Could you maybe create an animated gif of this? You can use the program peek for it. 
@clobrano should be the best man for this since he worked on this :)

**Comment by clobrano** [comment]
> This looks amazingly weird to me and think the previous behavior of the background between both Headerbar and Dock being coordinated was nicer.

This looks a bug more than a intended change. However, I'm unable to reproduce it on rev 73, can you try it?

**Comment by Feichtmeier** [comment]
Ahhh yeah now I understood :sweat_smile: 
Set dock to autohide and drag a window to the edge of the dock:
![screenshot from 2018-04-23 09-50-56](https://user-images.githubusercontent.com/15329494/39113436-f2074fe6-46db-11e8-8a79-578825caaf81.png)

**Comment by Feichtmeier** [comment]
Yet, this is not a communitheme issue. Logging into regular ubuntu:
![screenshot from 2018-04-23 09-54-08](https://user-images.githubusercontent.com/15329494/39113567-61c5d2b2-46dc-11e8-9129-c2b55048a7be.png)

I'll guess this is a dash to dock issue then

**Comment by clobrano** [comment]
Oh good intuition :grinning: 
So, for some reason Dock and top panel get "disconnected" when auto hide is enabled

> I'll guess this is a dash to dock issue then

At least, we should report this to them and see if we can do something about it

**Comment by clobrano** [comment]
I don't think so. Usually we just open a new one on the right repository and copy a link to the original report

**Comment by Feichtmeier** [comment]
Oh okay, well I would close it and open it either on 
https://launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock
Or upstream 
https://github.com/micheleg/dash-to-dock

Could you do that @wandrewkeech since this also affects other themes like ambiance?

**Comment by wandrewkeech** [comment]
Thanks so much for your work guys.

**Comment by wandrewkeech** [comment]
Posted the bug onto Launchpad: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1766710
