### ISSUE TITLE
GTK2 apps are not themed when using the snap

### ISSUE THREAD

**Issue by nicocarbone** [ubuntu/gtk-communitheme#358]
Sorry if this is a duplicate. I know this was a bug fixed some time ago, but it started happening again to me and, at least, other user in some update of the snap.
Example of apps affected are GIMP, Inkscape and Fillezilla. All of them installed via apt.
I attach a screenshot of Inkscape as an example.
![captura de pantalla de 2018-04-24 09-09-22](https://user-images.githubusercontent.com/9342423/39185937-485a5f6e-479f-11e8-8c83-aa7b9c327a27.png)

**Comment by nicocarbone** [comment]
The proposed solution for #349 also works here. Using the workaround:
> sudo ln -s /snap/communitheme/current/share/themes/Communitheme/ /usr/share/themes/
solves the problem for inkscape, gimp and fillezila.

**Comment by didrocks** [comment]
Right, but it's not the real deal :) Or maybe is it something impacting GTK and so electron apps won't pick up the theme? Worth investigating.

**Comment by didrocks** [comment]
Ok, I found the issue. Electron apps are using gtk2 styling, so the 2 issues were indeed related.
Do you mind trying the instructions on https://github.com/ubuntu/communitheme-snap-helpers/pull/8#issuecomment-384179997 and keep me posted if this works for you guys?
You need to logout/log back in after updating the snap (and remove any workaround you applied).

**Comment by nicocarbone** [comment]
The fix works here! :)

**Comment by didrocks** [comment]
Thanks for testing! The fix is now in master for the wrapper session and in revision 97 published to stable and edge channels!
