### ISSUE TITLE
Color choice for selected elements

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gtk-communitheme#363]
Just a semi-serious proposal. 

Selected treeview elements using $base_hover_color:

![treeview](https://user-images.githubusercontent.com/27529229/39254548-531291a4-4878-11e8-83c4-c951a2e96521.gif)

**Comment by clobrano** [comment]
I agree that in treeview orange might be unnecessary

**Comment by Feichtmeier** [comment]
I would make the selected text bold :octopus:

**Comment by godlyranchdressing** [comment]
@Feichtmeier I hate that this is becoming my motto recently but: I tried, but it looks like you can't. 

`treeview { font-weight: bold }` works, but `treeview:selected { font-weight: bold }` does nothing.

**Comment by Feichtmeier** [comment]
@godlyranchdressing not that big of a problem though imho :)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/39370924-7608b7f0-4a40-11e8-901c-c770dbfdeccc.png)

Geary uses this, too =) Looks kinda weird

**Comment by godlyranchdressing** [comment]
Orange sidebar row + gray treeview row it is. :grin:

**Comment by Luxamman** [comment]
Like already discussed (in 307) and said, it looks just deactivated in some circumstances. If we like to go for the blue selection, we should go for the blue selection. 
Also like said before, I would still like the blue to be more saturated because the contrast to white is sometimes not big enough (will make problems on cheaper displays, sunlight and so on).

**Comment by clobrano** [comment]
I've never expressed an opinion about that, but can we develop a bit more the idea of shades of orange for selection? Agree that salmon is not good, but we are constantly proceding towards no orange anymore in the theme...

**Comment by Feichtmeier** [comment]
I would recommend if we check the stuff on more apps before we change anything.

This was my personal failure (agreeing at the top here, reverting the PR then because I've seen where this change would hit) but I think you guys are also walking into these traps. 

A lot of GtkClasses are used in the most exotic places you would never think they exist.
((For example the new/proposed sidebar which is used in nautilus and the settings app is also used in the software center in the screenshot thumbnails and there the border is being cut off. I will open/reopen an/the issue for this))

___

On topic: 
A) leave it as it is. It does not look too bad on most gtk classes. <--- f
B) Blue @Luxamman mentioned --> recognizable yet unobtrusive

**Comment by godlyranchdressing** [comment]
![tree](https://user-images.githubusercontent.com/27529229/39398172-4c525360-4ad8-11e8-8404-36e3b9d092c1.gif)

Though the blue just doesn't work for the sidebar (at least in its current shade).

![e](https://user-images.githubusercontent.com/27529229/39398187-829c90ca-4ad8-11e8-9706-3f17994f6f96.png)

[Ubuntu palette](https://design.ubuntu.com/brand/colour-palette/) (includes the different shades of orange we can use).

This back and forth has been going on for too long though. It's Ubuntu, it's orange. At this point I say we rollback using blue for selected text as it's only since then that the use of blue has started to seem incoherent. We replace that with a shade that we can all agree on instead. All we need to do is cycle through a couple.

![text](https://user-images.githubusercontent.com/27529229/39398289-9ed1cf48-4ad9-11e8-9462-142f668292df.png)

![h](https://user-images.githubusercontent.com/27529229/39398304-c155571a-4ad9-11e8-9fd4-e4dcb6d14ad4.png)

![t4](https://user-images.githubusercontent.com/27529229/39398312-e5092a10-4ad9-11e8-8617-54a18ce1731c.png)

**Comment by Feichtmeier** [comment]
So many places about the same topic. :smiley: 

From my impressions there are two cases which could be pretty clearly divided:

- selection as an action --> these can be pretty much anything but to be precise ext fields, sidebars, treeview rows: here I would use only orange blocks like pretty much every other GTK theme out there (adwaita, ambiance, materia, adapta, pop, united gnome)

- selection as a marking --> this is pretty much only text marking in gtk: I would keep our light blue and make it a bit darker so as @Luxamman said it can be read with bad screens / bright / dark situations

___

buttons can be ofc selected too but these are special and we just did a good change and I would not touch these now

**Comment by madsrh** [comment]
> This back and forth has been going on for too long though. It's Ubuntu, it's orange. At this point I say we rollback using blue for selected text as it's only since then that the use of blue has started to seem incoherent. We replace that with a shade that we can all agree on instead. All we need to do is cycle through a couple.

@godlyranchdressing As mentioned I really like the light blue for text selection, but you are absolutely right. I'm sad to see it go, but just orange will make the theme look much more coherent (and like Ubuntu). IMO we still want to avoid salmon, so how about keep the #95420 or maybe slightly lighter (although it has lower contrast):
![selectedtext](https://user-images.githubusercontent.com/3986894/39411477-5264a1ac-4c0b-11e8-8c2b-d6baad931e7f.jpg)

These are both orange and doesn't look pink 😃

**Comment by ya-d** [comment]
I really have to say that text selection was the *one* area where I always thought orange was too much. The lighter tone works better now but I still miss the blue. I honestly don't want to start that debate all over again but could you please state or point me to the mayor conflicts with using orange for selected  elements as discussed here but keeping blue for text selection only?

I'm under the impression that almost everybody of you would like to keep blue for text selection. It also made for a nice, friendly and distinctive combination of colors (see save dialog for example) and made the sliders/progress bars feel more at home within the theme too. It is almost universally used for text selection everywhere. 

<img width="915" alt="orange text selection - gedit" src="https://user-images.githubusercontent.com/30781876/39564230-af81ffc4-4eb3-11e8-9e8e-11bfa36e9ea1.png">
<img width="750" alt="orange text selection - save dialogue" src="https://user-images.githubusercontent.com/30781876/39564231-af9fd026-4eb3-11e8-9bd8-309a4955d1d3.png">

**Comment by Feichtmeier** [comment]
I guess Aaron will freak out now but yes the blue would fit perfectly for text selection ONLY. I think the mess started when we followed the wrong idea that text selection is the same thing as ui element selection.  But the blue must be a little darker of it will return some day

**Comment by madsrh** [comment]
I love the blue text! It really looks more professionel / elegant.

> ...friendly and distinctive combination of colors (see save dialog for example)

@ya-d I think it was exactly that - the combination of blue selected text inside an orange frame in the save dialog, right @godlyranchdressing ?

> ...the wrong idea that text selection is the same thing as ui element selection...

@Feichtmeier Are you saying text selection should be blue, but NOT for textfields and other UI elements? 🤔

**Comment by Feichtmeier** [comment]
I am saying that every time you select text and text ONLY it should be blue. Text are in textfields too. But not for example a row in a 🌲 view or a row in a sidebar or anything else that is not only text

**Comment by ya-d** [comment]
Stable-chanel for comparison. There seems to be an issue with the color in the text field though.
<img width="461" alt="blue text selection gedit" src="https://user-images.githubusercontent.com/30781876/39566705-c8932930-4ebc-11e8-88be-f78be922446d.png"> <img width="377" alt="blue text selection save dialogue" src="https://user-images.githubusercontent.com/30781876/39566706-c8b3c4ba-4ebc-11e8-8453-8c084962f9a6.png">

**Comment by madsrh** [comment]
Just for reference, [this](https://github.com/ubuntu/gtk-communitheme/issues/307#issuecomment-378414227) was where we discussed it before.

![image](https://user-images.githubusercontent.com/3986894/39567765-50071054-4ec0-11e8-809b-a4c75eabaf9b.png)

**Comment by clobrano** [comment]
> I am saying that every time you select text and text ONLY it should be blue

so, editable text?

**Comment by Feichtmeier** [comment]
Yes editable text in GtkTextEntry and GtkTextVew =]
So we would have two colors 
selected_bg_color => 🍊
text_selection => the blue seen above but maybe 10% darker for bad screens

**Comment by Feichtmeier** [comment]
I recapped this a bit and just for the record this is what happened:

- blue text was introduced
- Nautilus selection in thumbnail mode was considered to be on line with text selection (which it isn't it's something else) and was thus changed to blue too
- then the blue was also considered for rows in treeview and everything was blue for a moment
- too much blue, we went back to orange, but this time light orange

xD
