### ISSUE TITLE
Deactivated check- and radiobutton styles changed

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#367]
I'm guessing this is a [result of another PR](https://github.com/ubuntu/gtk-communitheme/pulls?q=is%3Apr+is%3Aclosed) 🤔 

## Before:
![image](https://user-images.githubusercontent.com/3986894/39275651-5b46a518-48e6-11e8-95f8-c2cbf44de226.png)

## After:
![image](https://user-images.githubusercontent.com/3986894/39275707-7908feca-48e6-11e8-97be-4268fbcab804.png)

**Comment by godlyranchdressing** [comment]
Probably #360

**Comment by clobrano** [comment]
> Probably #360

Oh, it might be :disappointed:

**Comment by clobrano** [comment]
The problem is also that check/radio share a lot of button css
