### ISSUE TITLE
Running applications as root doesn't use communitheme

### ISSUE THREAD

**Issue by chaNcharge** [ubuntu/gtk-communitheme#368]
Running the latest stable snap, if I try to run an application such as Nautilus or Bleachbit as root, it doesn't use the communitheme at all. This does not reproduce when communitheme is installed from source.
Reproduce:
1. Install latest stable communitheme as snap
2. Open a terminal and type `sudo nautilus`

I don't have an image with me yet, but I can post one as soon as I am able to if you want.

**Comment by chaNcharge** [comment]
Just noticed this was closed earlier, never mind.

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/gtk-communitheme/issues/345
Duplicate and wontfix (read above)
Thanks for taking the time to report this though! And keep up reporting issues! =)
