### ISSUE TITLE
Infobar buttons and selection-mode-titlebar could use some love

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#378]
![screenshot from 2018-04-28 19-38-00](https://user-images.githubusercontent.com/15329494/39399318-ee636a8e-4b1b-11e8-9ab5-afaeaadd6a48.png)

The buttons could use a different solution when pressed:
![image](https://user-images.githubusercontent.com/15329494/39399332-1f3c0e5e-4b1c-11e8-83c0-34c2149d0dfc.png)

The borders could look a bit better when attached to the half of the screen:
![image](https://user-images.githubusercontent.com/15329494/39399342-43541d90-4b1c-11e8-810d-e13d7860843c.png)

It's called selection-mode titlebar of the object gtkheaderbar

The buttons could be changed by @godlyranchdressing while the titlebar could be changed by @clobrano due to their/your recent PR-knowledge ;O

((maybe one coud fix thix issue in the same PR: https://github.com/ubuntu/gtk-communitheme/issues/236))

**Comment by clobrano** [comment]
HI, I can work on this after #367

**Comment by Feichtmeier** [comment]
@clobrano great, maybe you can look into this also then, kinda the same "topic":
https://github.com/ubuntu/gtk-communitheme/pull/371 (scroll down)

**Comment by clobrano** [comment]
Here's a first mockup, that makes it coherent with normal headerbar, where the buttons share the same color with the background

![selection-mode-no-guidance](https://user-images.githubusercontent.com/2883614/39408326-cd94085e-4bd4-11e8-92f6-2c04671e32b9.gif)
![selection-mode-no-guidance2](https://user-images.githubusercontent.com/2883614/39408347-277c147e-4bd5-11e8-9ab3-acd86787383b.gif)
