### ISSUE TITLE
Communitheme incompatible with Window List

### ISSUE THREAD

**Issue by xavifr** [ubuntu/gtk-communitheme#382]
I've tried Communitheme but it is incompatible with Windows List extension (https://extensions.gnome.org/extension/602/window-list/) which I want to keep using.

When using Communitheme, all versions of Windows List fails to load.

**Comment by clobrano** [comment]
Hi, thank you for taking time to report this. The same extension is working on default session?

**Comment by Feichtmeier** [comment]
@xavifr did you install it via snap?

**Comment by xavifr** [comment]
I've used snap with classic and edge.
Also the PPA version.

Using normal gnome session, extension works fine.

I've tested it failed in 17.10 and 18.04.

Are there any logs that could be useful?

Thanks!

**Comment by Feichtmeier** [comment]
so the gnome-session works? What about the ubuntu-session? And did you use x or wayland?

**Comment by xavifr** [comment]
All tests done with Xorg (my default) and Wayland

 * Gnome-session

![screenshot from 2018-04-30 09-09-26](https://user-images.githubusercontent.com/13116609/39417721-8020044c-4c56-11e8-8d06-401a1a52b09f.png)
  

 * Ubuntu (ubuntu-session) / Communitheme on snap (snap --edge version) / Communitheme on Xorg (ppa-version)

![screenshot from 2018-04-30 09-07-52](https://user-images.githubusercontent.com/13116609/39417755-a3abcb1c-4c56-11e8-8315-5a4e11da342c.png)

**Comment by Feichtmeier** [comment]
Okay so ambiance is also affected. This is really out of our development scope. Maybe you should rather file a bug on launchpad for this?
Best regards
