### ISSUE TITLE
Add a dark variant gtk theme

### ISSUE THREAD

**Issue by chaNcharge** [ubuntu/gtk-communitheme#386]
This is a suggestion; some other themes like Breeze and Adapta have a dark themed variant that you can change to in GNOME Tweaks. Maybe Communitheme could have one too?

**Comment by clobrano** [comment]
Hi @chaNcharge, thank you for proposing this. On the Forum this topic appeared from time to time, but I still think it is too early to plan it. Nonetheless some GNOME applications already use some kind of dark variant (Photos, Videos), so this effort is already (partially, I know) taken into account.

**Comment by clobrano** [comment]
I'd close this issue now, since it is not possible to take it into account now.

**Comment by clobrano** [comment]
@Feichtmeier I agree, we can keep working on #320 though, which is more specific to just colors
