### ISSUE TITLE
Tab titles in unfocused GNOME terminals hard to read

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#390]
The tab titles in unfocused GNOME terminal windows are very hard to read.

![tab-titles](https://user-images.githubusercontent.com/1141694/39472982-5e4dcbe4-4d44-11e8-88e8-ee2c48d6a4aa.png)

**Comment by Corsseir** [comment]
I have this issue as well:
![Uploading Screenshot from 2018-05-01 23-51-38.png…]()
