### ISSUE TITLE
Background color of scrollbar looks weird

### ISSUE THREAD

**Issue by Corsseir** [ubuntu/gtk-communitheme#395]
![1](https://user-images.githubusercontent.com/11137173/39552083-04737fea-4e68-11e8-9050-a710c41ba8ad.png)
I think background color of the scrollbar should be white? In this case it looks pretty weird.

**Comment by madsrh** [comment]
@Corsseir Thanks for taking the time to report this issue 👍 
In the screenshot, the scrollbar is disconnected from the top. This is a result of [issue 109](https://github.com/ubuntu/gtk-communitheme/issues/109) adding padding to the wrong container.

We need to add more space to the tab furthest to the right, so it aligns with the scrollbar.
![image](https://user-images.githubusercontent.com/3986894/39656353-7db1ce5a-4fff-11e8-8ccd-47ac7da7b8ea.png)

But @clobrano @godlyranchdressing @Feichtmeier what do you think of this "Telegram" styled scrollbars?
![image](https://user-images.githubusercontent.com/3986894/39656000-4350399c-4ffd-11e8-921c-07df7751433e.png)

**Comment by Feichtmeier** [comment]
![peek 2018-05-05 00-58](https://user-images.githubusercontent.com/15329494/39656445-1c3641d2-5000-11e8-99df-c172c4d346f2.gif)

**Comment by clobrano** [comment]
Issue #109 made the problem more visible, but it was always there
 
![image](https://user-images.githubusercontent.com/2883614/39673028-1a546cf0-5135-11e8-8375-b837e91701d3.png)

+1 on telegram style border
