### ISSUE TITLE
Close button to-backdrop animation is too slow

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#402]
![close-button-backdrop-animation](https://user-images.githubusercontent.com/2883614/39665156-fd0ae836-508f-11e8-94ba-d4b09b4247e4.gif)

**Comment by Feichtmeier** [comment]
How about the thread that is like.... 5 rows below this one?
![image](https://user-images.githubusercontent.com/15329494/39667790-ae75a250-50bd-11e8-9059-f52ed4c0c533.png)
:laughing:
