### ISSUE TITLE
Sliders blue?

### ISSUE THREAD

**Issue by alvarlagerlof** [ubuntu/gtk-communitheme#403]
Why are sliders and loaders blue? Shouldn't they be green? At least sliders.

**Comment by Feichtmeier** [comment]
Is this really an issue? A question? :-1: 
I would suggest you to read this section of the hub first: https://community.ubuntu.com/c/desktop/theme-refresh

They come from the unity8 and/or ubuntu touch design. It is pretty much the "standard" ubuntu design at the moment.
