### ISSUE TITLE
Suggested action button active/pressed could use a different solution

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#406]
![peek 2018-05-06 22-59](https://user-images.githubusercontent.com/15329494/39677827-e5ec02e6-5181-11e8-92cf-55fc44ebc8cf.gif)

When pressed the button looks almost like it's cut off at the top border.

Edit: maybe this could be an opportunity to review the pressed buttons in header bars once more. I believe the black shadow at the top is a tiny tiny tiny bit too black:
![image](https://user-images.githubusercontent.com/15329494/39688185-d89b14d8-51d1-11e8-9465-b0793bd49244.png)
(

**Comment by Feichtmeier** [comment]
@madsrh the cancel button has a border now, maybe I had the wrong branch when taking this gif
![image](https://user-images.githubusercontent.com/15329494/39688632-ea4906de-51d3-11e8-9440-e551108f93ba.png)

**Comment by clobrano** [comment]
Probably the effect on suggested action is just that it uses the same style as black buttons, while it can be improved using a darker green color instead like in selection-mode

**Comment by Feichtmeier** [comment]
Maybe like you did it in the selection header of gnome-music etc:
![image](https://user-images.githubusercontent.com/15329494/39698876-edd950e2-51f6-11e8-9a69-98607cb48b0d.png)

**Comment by Feichtmeier** [comment]
@clobrano if you fix this someday, I've one more thing that could fit that PR:
![image](https://user-images.githubusercontent.com/15329494/39710165-4e1f1a66-521c-11e8-9830-0aeb4c82aa97.png)
There is a little "glitch" in the "corner" if this squircly slider edge

**Comment by clobrano** [comment]
@Feichtmeier the glitch is probably something we can't do anything about it. I even tried with no radius and still persisted.

About the original issue of this ticket, the effect is due to the background behind the switch. Normal switches and also the ones in selection-mode have a bright background, so the shadow is clearly a shadow in fact. This one has a headerbar, which is darker than the shadow and creates this weird effect. I tried multiple solutions and the current one is actually the best I've found

**Comment by Feichtmeier** [comment]
Okay. Could you point me to the code?

**Comment by clobrano** [comment]
Which one? Switch or suggested buttons?

**Comment by Feichtmeier** [comment]
Both, both have that hard shadow at the top (or background)

**Comment by Feichtmeier** [comment]
![qwert](https://user-images.githubusercontent.com/15329494/41005498-fbddb438-691d-11e8-8588-d4c1bafac333.gif)

**Comment by clobrano** [comment]
Sorry @Feichtmeier, but I don't see the improvement :thinking: 

Before
![suggested-before](https://user-images.githubusercontent.com/2883614/41022061-b4b57ffa-6968-11e8-9a89-3945a2d71908.gif)

After
![suggested-after](https://user-images.githubusercontent.com/2883614/41022074-bd3f3e4a-6968-11e8-8007-2f69b2abdf0e.gif)

**Comment by Feichtmeier** [comment]
@clobrano haha you are right. Need to try again later

**Comment by Feichtmeier** [comment]
@clobrano I've reduced this a bit with the darktheme. So it's basically fixed :)
