### ISSUE TITLE
Style GtkFileChooserDialog preview area

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#408]
The preview column in the file chooser dialog looks unstyled. Very small tweaks, I know and yes, the typo is just for fun 😆 

- Center text and add padding
- Center image (if possible)
- Add border

Here is Adwaita, Current and mockup:
![screenshit](https://user-images.githubusercontent.com/3986894/39697333-e1a6a14a-51f0-11e8-92bf-0251445fd0f1.gif)

Align text (I can't believe Adwaita doesn't do this):
![image](https://user-images.githubusercontent.com/3986894/39697088-044d177a-51f0-11e8-85e3-db876e4224d8.png)

**EDIT:** Are the white borders around _Cancel_ and _Open_ missing here? I think _Open_ only has a border because it's the default action if I press Enter ???

**Comment by Feichtmeier** [comment]
(((sorry for the offtopic but why does your ubuntu name the screenshots screenshit? xD)))

Good idea - yet I hope we find a  global solution rather than in _apps

**Comment by madsrh** [comment]
> sorry for the offtopic but why does your ubuntu name the screenshots screenshit?

It's just a mockups, so only for shits and giggles 😆 

> yet I hope we find a global solution rather than in _apps

Yes! Are you suggesting a upstream bug? That would be great, although it might not be fixed in time for the next LTS 🙊

**Comment by Feichtmeier** [comment]
It's in adwaita, too. Could be worth a try to report it. It isn't so bad after they moved to gitlab away from bugzilla.

**Comment by clobrano** [comment]
Oops, I didn't mean to push on master, sorry
