### ISSUE TITLE
Terminal tabs and scrollbar colors with custom color scheme

### ISSUE THREAD

**Issue by toddjames** [ubuntu/gtk-communitheme#410]
I've set my terminal color scheme to "Tango dark", but the tabs and the scrollbar still stay the default Ubuntu purple, which clashes with this scheme and others.

I noticed that the default Ubuntu 18.04 color scheme actually uses white and gray tabs with an orange scrollbar, which seems to be a good match for most color schemes.

Is there a way that I could customize these colors as an end-user or that they could be changed to something that matches better with the default color schemes available in the terminal?

This screenshot illustrates my problem with Communitheme and the "Tango dark" scheme:
![communitheme](https://user-images.githubusercontent.com/860775/39713315-57bf5414-51f4-11e8-92f8-0163633bbd12.png)

Here is the default theme's terminal:
![default-ubuntu1](https://user-images.githubusercontent.com/860775/39713271-373a9e24-51f4-11e8-8c25-f2b90cf3f93a.png)

Here is the default theme's terminal with the "Tango dark" color scheme:
![default-ubuntu-2](https://user-images.githubusercontent.com/860775/39713292-4921fa56-51f4-11e8-9db8-f768a09aa0e6.png)

**Comment by clobrano** [comment]
I will look into it, but I am afraid this could not be possible for the theme, it might be up to gnome-terminal to extend the color to all the selected tab at least.

> I noticed that the default Ubuntu 18.04 color scheme actually uses white and gray tabs with an orange scrollbar, which seems to be a good match for most color schemes.

I don't agree. To me, white and gray matches with no scheme, except white and grey, so it doesn't seem an improvement

**Comment by clobrano** [comment]
I gave a look at how Adwaita woks with the terminal. Their solution is to style the tabs like the headerbar + menubar. This is a possible mockup for communitheme using this way

![image](https://user-images.githubusercontent.com/2883614/39877876-5128c6be-5477-11e8-820a-6ced324c4bc7.png)

here with terminal using solarized dark theme

**Comment by madsrh** [comment]
Again, excellent work @clobrano 👍 

By using the headerbar colors, I experience that the bright tab steals my attention - although the dark one is in focus (I persume). I think we can switch the colors (light=active and dark=backdrop) without anyone mentioning “He-who-must-not-be-named” 😉 

Also slightly darker text for the unfocused tab:
![image](https://user-images.githubusercontent.com/3986894/39886683-7af4315e-5490-11e8-80a3-b57033820e3c.png)

I wondered if I would experience the same with the headerbar colors and tried a few mockups with a window in focus and one in backdrop, but somehow that works differently 🤔

**Comment by clobrano** [comment]
> By using the headerbar colors, I experience that the bright tab steals my attention - although the dark one is in focus

I agree with you, the bright one stands out. However in this case I would use a slighly darker headerbar color for the unfocus one. I'll prepare some mockups

**Comment by clobrano** [comment]
I simplified the change keeping current tab shape, which should be make easier to see which tab is on, and changed the colors

![image](https://user-images.githubusercontent.com/2883614/39917618-7932eecc-550e-11e8-9293-91c328f3dc84.png)

**Comment by madsrh** [comment]
This looks really good @clobrano 👍

**Comment by toddjames** [comment]
@clobrano @madsrh The tabs look great, thanks for the quick turnaround!

The scrollbar background is still purple. Any chance to see that blended better, too, or should I open a separate issue now?

**Comment by madsrh** [comment]
@clobrano I sorry to comment after you've closed this issue, but I've been AFK 💻 

I think the black lines are a bit heavy. What would you think about brighten them a bit and perhaps using a light gray for that active tab? 

Here's a quick and dirty mockup:
![terminal](https://user-images.githubusercontent.com/3986894/39944679-cfafb7a4-5567-11e8-9012-c53deaee5f1c.gif)

**Comment by Paz-it** [comment]
I'll remove the line under the menu-bar as well... See how clean it looks without it:
![screenshot from 2018-05-12 03-30-04](https://user-images.githubusercontent.com/37431503/39951688-d876c594-5594-11e8-9de0-0c9c4af9aa09.png)

**Comment by clobrano** [comment]
@madsrh you're right, buttons should behave the same. 

@Paz-it I prefer a lighter separation line

**Comment by Paz-it** [comment]
>  I prefer a lighter separation line

I prefer no line at all :))
