### ISSUE TITLE
Placement of confirmation dialog

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [ubuntu/gtk-communitheme#411]
Hi,

I'm not sure if this is strictly a communitheme issue or a GNOME issue but when using multi-monitor setup, an unattached dialog renders off-center (or rather, at the exact center of the combined screens)
which is unwanted and unsightly, in unity7 the dialog gets rendered on the center of the active screen.

![screenshot from 2018-05-08 02-16-43](https://user-images.githubusercontent.com/38913802/39717881-237a46f0-5267-11e8-987e-c8561392dc6e.png)

**Comment by clobrano** [comment]
It looks a system bug, but it might be triggered by communitheme session. Any chance you can try with standard session?

1. logout
2. at login click on the gear icon and select "Ubuntu" or "Ubuntu on Wayland"

**Comment by ReyLeonardAmorato** [comment]
I think you might be right. I don't have a Wayland session under the session switcher (apparently it gets removed when using proprietary NVIDIA dirvers?) so I selected the default Ubuntu session instead and logged in from there. Same thing.

![screenshot from 2018-05-12 10-54-32](https://user-images.githubusercontent.com/38913802/39952955-e230a94e-55d3-11e8-9a6d-d70abc91c975.png)

**Comment by clobrano** [comment]
@ReyLeonardAmorato thank you, closing this then since it does not depend on communitheme.

Actually I'm not sure where should you report this issue, is there any bug tracker for NVIDIA drivers?

**Comment by ReyLeonardAmorato** [comment]
Sure, go ahead. Hmm... I'm not entirely sure either. I'll try to find out. Thanks!

**Comment by Feichtmeier** [comment]
Stupid question but you seem to use some kind of on screen calendar. Did you try if this also happens when you disable this?

**Comment by ReyLeonardAmorato** [comment]
Oh, no not at all. It's actually conky. I tried but problem's still there.
![screenshot from 2018-05-14 23-23-41](https://user-images.githubusercontent.com/38913802/40007296-f58771b0-57ce-11e8-9bd0-52fee03d53c8.png)

I even switched up the monitors to see if it makes any difference.
![screenshot from 2018-05-14 23-25-25](https://user-images.githubusercontent.com/38913802/40007373-2665e06e-57cf-11e8-9606-15cc6520f51b.png)

Only way is to mirror the display, then the dialog centers.
![screenshot from 2018-05-14 23-26-51](https://user-images.githubusercontent.com/38913802/40007490-86920b3e-57cf-11e8-839a-8328e76a937b.png)

**Comment by Feichtmeier** [comment]
Ah well, reporting upstream won't help since they removed the desktop form nautilus after 3.26. There is no desktop anymore. Open gnome tweaks and disable this toggle:
![image](https://user-images.githubusercontent.com/15329494/40008403-814ff792-579f-11e8-8b9f-f900632d48c4.png)
Ubuntu only supports this still because they kept 3.26 even if the rest is gnome 3.28 :/
You can still empty the trash from nautilus though! =)

**Comment by ReyLeonardAmorato** [comment]
Oh noes! I like my desktop icons... :( But you're right, it seems to solve the problem. No more rogue dialogs. I'm going to try going without the desktop to see if it changes my workflow.

**Comment by clobrano** [comment]
Nice catch @Feichtmeier :+1:

**Comment by ReyLeonardAmorato** [comment]
Bug reported. https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1771316

**Comment by Feichtmeier** [comment]
Thank you!

**Comment by ReyLeonardAmorato** [comment]
No problem, thanks for the great work guys!
