### ISSUE TITLE
Round hover effect for the app menu button does not look good

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gtk-communitheme#413]
Using Communitheme form snap --edge 
I've noticed that the app menu button has the same background hover effect as the window's controls. The icon is usually a rectangle but the hover effect is a circle which together does not look good. 
Screenshot with Terminal app as the example:
![zrzut ekranu z 2018-05-07 21-26-18](https://user-images.githubusercontent.com/1629120/39723897-1b08b4b6-523f-11e8-9b5d-6e468ca6957b.png)

**Comment by clobrano** [comment]
Hi @mivoligo, how did you get this app menu button?

**Comment by Feichtmeier** [comment]
Ah that's because we use
not(close) .... drawcircle on everything in the window decorations that is not the close button. I guess when you put the app menu in the top bar it get's placed within the window controls

**Comment by Feichtmeier** [comment]
@clobrano you can toggle this in tweaks:
![peek 2018-05-08 15-34](https://user-images.githubusercontent.com/15329494/39760324-52d14ae8-52d5-11e8-8777-936e625e905a.gif)

**Comment by clobrano** [comment]
It looks terrible :smile: , why not use a generic icon, instead of application icon. Anyway, @Feichtmeier are you on this?

**Comment by Feichtmeier** [comment]
@clobrano yes I can fix this. I say let's throw this not(close) away and explicitly set it for min and max

**Comment by Feichtmeier** [comment]
@clobrano don't say this to an elementaryOS designer ;O They use standard icons only for the headerbar

**Comment by mivoligo** [comment]
Yes, I used Tweaks to have the menu there. I can't stand the 'global' menu.

**Comment by Feichtmeier** [comment]
@clobrano which one of your crazy button function do one need to include for headerbar buttons? :dancing_men: 

&.appmenu{@include button(normal);} 

Looks very wrong

**Comment by clobrano** [comment]
You could look at button under headerbar section, it should be flat and with proper background and foreground color, but I'm not sure you need that

**Comment by Feichtmeier** [comment]
This works 

![peek 2018-05-08 16-29](https://user-images.githubusercontent.com/15329494/39763300-06070e7a-52dd-11e8-9876-0401475884e4.gif)

Okay like this?

```&.appmenu{
    @each $state, $t in ("", "normal"),
                        (":hover", "hover"),
                        (":active, &:checked", "active"),
                        (":disabled", "insensitive"),
                        (":disabled:active, &:disabled:checked", "insensitive-active"),
                        (":backdrop", "backdrop"),
                        (":backdrop:active, &:backdrop:checked", 'backdrop-active'),
                        (":backdrop:disabled", 'backdrop-insensitive'),
                        (":backdrop:disabled:active, &:backdrop:disabled:checked", 'backdrop-insensitive-active') {
                          &#{$state} { @include button($t, $c, $tc, $flat:true); }
                        }
    }
