### ISSUE TITLE
GDM should have gradient background

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#42]
In this mockup it's #15030f -> #472c3f

![bg](https://user-images.githubusercontent.com/3986894/34853142-8c5ac6c6-f732-11e7-801f-2a1a6315b02f.jpg)

**Comment by godlyranchdressing** [comment]
Carried over to [here](https://github.com/Ubuntu/gnome-shell-communitheme/issues/24) :stuck_out_tongue_winking_eye:
