### ISSUE TITLE
No indication that tree/list view has focus

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#423]
Because Communitheme uses a dashed orange focus rectangle, and it uses orange for the selected/highlighted item (whether list/tree is focused or not), there is no visual indication that the view has focus.

I'm not sure if this is possible with Gtk themes, but it would be nice if the focused view had an orange border as per focused entry fields.

At the very least, the dashed focus rectangle for selected view items should be white - so that it contrasts with the selection colour.

**Comment by madsrh** [comment]
@CDrummond If I understand correctly, this is what you're looking for?

![peek 2018-05-10 01-39](https://user-images.githubusercontent.com/3986894/39860756-5afab280-53f3-11e8-93d5-e91d59e2cfac.gif)

@clobrano Is something like this correct? (backdrop isn't fixed}
```
*treeview:selected { background: none; border: 1px dashed  #e95420; color: #2d2d2d; }
*treeview:focus { background: #e95420; color: #fff; }
```

**Comment by clobrano** [comment]
@madsrh my understanding is that @CDrummond wanted a selection ring on the whole treeview, is that so?

**Comment by CDrummond** [comment]
Well, personally I'd prefer if the frame around the whole view was orange - like the blue highlight I see on this text field in github.

Not sure I like changing the highlight colour so drastically. Adwaita, for instance, draws a white focus rect for the selected item. (Actually, this should be done anyway - as if multiple items are selected, which has focus?)

@clobrano Yeah - that would be the nicest solution. If its possible.

**Comment by clobrano** [comment]
> @clobrano Yeah - that would be the nicest solution. If its possible.

I'm afraid not. The borders around the treeview are actually owned by the scrolledwindow that contains it, which doesn't know whether or not the treeview is focused.

**Comment by CDrummond** [comment]
@clobrano I thought that might be the case :-(  Shame, as Kvantum does this for Qt apps, and its really nice.

Still, the focus rectangle should be white for the selected item. This would solve 2 issues; you can see that the view itself has focus, and which of the selected items has focus.

**Comment by clobrano** [comment]
> Still, the focus rectangle should be white for the selected item. This would solve 2 issues; you can see that the view itself has focus, and which of the selected items has focus.

I should double check why we cannot see the selection ring in treeview. On other rows (like the one below treeview in widget-factory) the selection ring is clearly visible as the border of the orange blob (and If we use white selection ring in this case, it won't be visible anymore)

**Comment by CDrummond** [comment]
But if you have 3 selected (adjacent) rows, and the middle has focus - how would you tell? The white focus ring should be 1 or 2 pixels _inside_ the selected row. Look at how Adwaita does this in gtk3-widget-factory. If you look at the list view on page 1, you can see that the focus is per column, and the white focus moves with left/right arrow.

>  On other rows (like the one below treeview in widget-factory) the selection ring is clearly visible as the border of the orange blob

Yeah, that's a really weird effect. Even here, I think (IMHO) that it'd be nicer for the focus to be 1 (or 2) pixels away from the edge. Then white for selected rows, orange for others (assuming Gtk allows focus and not selected rows).

**Comment by clobrano** [comment]
> Look at how Adwaita does this in gtk3-widget-factory.

I understood now and I agree on your point, very well spotted :+1:

**Comment by clobrano** [comment]
Not easy to trigger, but it should look this way, I guess

![image](https://user-images.githubusercontent.com/2883614/39872545-9f1d4a02-5468-11e8-8e15-5f53ee701755.png)

**Comment by CDrummond** [comment]
Can a row be focused, and not selected? If so, then you also need a orange border (with the same offsets) for these rows.

**Comment by CDrummond** [comment]
I'll let you decide, but 1px looks OK to me (assuming the last screenshot (the tree) was 1 px). Perhaps if the white focus was semi-transparent then it would look better?

**Comment by clobrano** [comment]
Just a little bit transparent might work better. Last 2 pictures are both -2px

**Comment by madsrh** [comment]
LGTM 👍
