### ISSUE TITLE
GTK 2 app theme inconsistent with GTK 3 communitheme

### ISSUE THREAD

**Issue by chaNcharge** [ubuntu/gtk-communitheme#427]
I feel like this is already a known issue, sorry if this is a duplicate. I'm also aware you fixed this according to #358. One thing I notice in GTK 2 apps like Synaptic, highlighted text, buttons, and icons are different (e.g. highlighted text is blue and not orange). Is there a way you can make the theme consistent with GTK 3 apps?
![image](https://user-images.githubusercontent.com/11594018/39906473-be8ea258-5497-11e8-94f1-8526600071b3.png)

**Comment by clobrano** [comment]
Hi @chaNcharge, is this synaptic installed as snap?

**Comment by clobrano** [comment]
This probably happen because the theme is selected according to the environment of the user that runs it, in this case is root.

Running the application with sudo -E flag is a workaround

```
     -E, --preserve-env
                 Indicates to the security policy that the user wishes to preserve their existing envi‐
                 ronment variables.  The security policy may return an error if the user does not have
                 permission to preserve the environment.
```

    sudo -E synaptic

**Comment by clobrano** [comment]
Since this behavior is not related to communitheme, I am going to close the bug.

**Comment by mivoligo** [comment]
@chaNcharge how did you manage to have more icons in Synaptic than me???
Mine looks like this:
![zrzut ekranu z 2018-05-11 10-17-05](https://user-images.githubusercontent.com/1629120/39917129-80044444-5504-11e8-958f-276d42ac7139.png)
