### ISSUE TITLE
Titlebar button background vanishes when pressed

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#430]
For non-CSD windows, the circular background given to the min/max buttons on hover disappears when pressed. For CSD windows, the circle gets darker.

**Comment by Feichtmeier** [comment]
Hm I thought I fixed this. Are you on the current master?

**Comment by CDrummond** [comment]
Yup. I always update before reporting issues. Logged in/out to ensure new session - still has same issue.

**Comment by Feichtmeier** [comment]
You are right - I believe this is some regression. I've noticed an additional issue.
When you open two CSD windows, for example todo and nautilus, the new backdrop color is being applied:
![image](https://user-images.githubusercontent.com/15329494/39913224-5c9b6b20-5501-11e8-8a8a-d43c249d26ee.png)

However when you mix CSD with non CSD, the CSD does not receive the backdrop color AND keeps the red circle:

![image](https://user-images.githubusercontent.com/15329494/39913310-b188759c-5501-11e8-9710-87e349dc0ada.png)

@clobrano any idea? I believe this  happend in the latest backdrop change

**Comment by clobrano** [comment]
> @clobrano any idea? I believe this  happend in the latest backdrop change

this does not seem to happen on my installation. How do you reproduce it?

**Comment by CDrummond** [comment]
Simple:

1. Open GNOME terminal
2. Open Nautilus (or any other app) and place in front of terminal (but keep terminal's titlebar visible)
3. Hover over min (or max) button in terminals titlebar
4. Press (but dont release) min (or max) button

**Comment by Feichtmeier** [comment]
I am fixing the slow animation with https://github.com/ubuntu/gtk-communitheme/pull/437
but I need some more time or help for this one here. 
My first idea was that the 
    background-image: -gtk-gradient(radial,
                                  center center, 0,
                                  center center, $circle_size,
                                  to($_bg),
                                  to(transparent));

Does not work on non-CSD windows? Could this be? @clobrano

**Comment by clobrano** [comment]
sorry @Feichtmeier I've missed this, but I really don't know :)

**Comment by Feichtmeier** [comment]
I think it's already fixed by you or aaron isn't it?

**Comment by clobrano** [comment]
I haven't tested it

**Comment by clobrano** [comment]
tested, still reproducible

**Comment by Feichtmeier** [comment]
I believe the backdrop close btn is still missing, right? @cdrummond

**Comment by CDrummond** [comment]
Yup - all buttons apart from 'close' are OK.
