### ISSUE TITLE
border bleed in Firefox's contextual menu

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#431]
![image](https://user-images.githubusercontent.com/2883614/39915194-891af098-5507-11e8-877b-80889b9f49ec.png)

discussed also [here](https://github.com/ubuntu/gtk-communitheme/issues/183#issuecomment-377952136)

**Comment by Feichtmeier** [comment]
Closed by https://github.com/ubuntu/gtk-communitheme/pull/485
Thanks @vinceliuice
