### ISSUE TITLE
Update Terminal scrollbar background color

### ISSUE THREAD

**Issue by toddjames** [ubuntu/gtk-communitheme#435]
See #410 . The tab colors were updated (thanks!), but the scrollbar background color is still the standard Ubuntu purple. This looks off when not using the standard color scheme.

![screenshot from 2018-05-11 17-14-17](https://user-images.githubusercontent.com/860775/39947160-e7906766-553e-11e8-9421-da277443a114.png)

**Comment by clobrano** [comment]
I cannot reproduce this, scrollbar is black on my system

**Comment by toddjames** [comment]
Yeah, it's gray/black today. I guess one of the commits over the weekend also had a side-effect of changing it?
