### ISSUE TITLE
Visibility of disabled switch in the title bar

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gtk-communitheme#446]
I hope this is the right repo 😋

I'm not sure if it's intentional or not but the switch in title bar is better visible when an app is in the background than when in the foreground.

App in the foreground:
![zrzut ekranu z 2018-05-14 11-39-18](https://user-images.githubusercontent.com/1629120/39992978-4d00d8a4-576c-11e8-8e2b-d530200d8d2b.png)

App in the background:
![zrzut ekranu z 2018-05-14 11-40-36](https://user-images.githubusercontent.com/1629120/39992999-5db4fcb6-576c-11e8-87a3-19cf1ef24480.png)

**Comment by clobrano** [comment]
Correct, thank you ;)
