### ISSUE TITLE
Some elements shift when clicking app menu button

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gtk-communitheme#447]
I've noticed it in the Software Centre (or whatever it's called these days) app. 
When I click the app menu button in the titlebar, some other elements in the bar shift their position. 

![peek 2018-05-15 11-49](https://user-images.githubusercontent.com/1629120/40052779-b7c568f6-5836-11e8-8787-67a9f00f2c02.gif)

I've checked normal Ubuntu session and I'm not seeing this behavior there.

**Comment by Feichtmeier** [comment]
Confirmed. Though I can't find any other app where that happens beside software. Did you find any other, @mivoligo ?

**Comment by mivoligo** [comment]
Nope, nothing else so far.

**Comment by mivoligo** [comment]
Sorry, just noticed this issue in Calendar app

**Comment by mivoligo** [comment]
Evince as well.

**Comment by clobrano** [comment]
@Feichtmeier this looks like a border is removed when the button is pressed

**Comment by godlyranchdressing** [comment]
Calendar, Software and any other app that this happens in have no left border on their headerbar for some reason. The headerbar's left border pops in only when opening the appmenu. 

I don't even know where to begin. :laughing: 

![poping](https://user-images.githubusercontent.com/27529229/40131687-a7af5382-5908-11e8-88e7-e15975ef088e.gif)

**Comment by ya-d** [comment]
Btw this also causes those apps to have no "separation" to the dock which maybe is what @Luxamman reported. Reference: [#Shell/177](https://github.com/ubuntu/gnome-shell-communitheme/pull/177).

<img width="389" alt="maximized - missing border" src="https://user-images.githubusercontent.com/30781876/40162167-543c58ca-59b3-11e8-98e3-3c9e7062841a.png">

**Comment by clobrano** [comment]
This is a side effect of 2f0c1217

**Comment by clobrano** [comment]
Could you double check whether the above change fixes the shift?

Now, I don't really know how the following line inside headerbar could affect gnome-software-center's headerbar :thinking: , however removing it, g-s-c works fine, but we have thick separation line in gnome control center and tweaks again...

    &:not(:only-child):not(:nth-child(1)) { border-left-width: 0; };
