### ISSUE TITLE
Issue with readability of some entries in Calendar app

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gtk-communitheme#449]
When the Calendar app is in the background, some entries are hard to read. For me specially black text on dark green background.
Comparison between Calendar in foreground (left) and background (right):
 
![calendar](https://user-images.githubusercontent.com/1629120/40109109-92ca4648-58f4-11e8-9e5f-af775e059e2c.png)

**Comment by clobrano** [comment]
I am not sure we can fix this. The user can choose any background color and only calendar knows which one, so only calendar could decide which text color fits best. Note that Calendar does this when the windows is on focus, but instead relies on theme's backdrop text color when is out of focus.

**Comment by mivoligo** [comment]
Thanks for explanation. I think I understand what you're saying.

**Comment by clobrano** [comment]
Closing this then, thank you and keep testing! :smile:
