### ISSUE TITLE
Grey text on white background for unresponsive program is unreadable

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [ubuntu/gtk-communitheme#450]
Is this by design or was just overlooked with all the switching from light/dark dialogs?

![screenshot from 2018-05-16 18-01-19](https://user-images.githubusercontent.com/38913802/40111122-7f4d1f9c-5934-11e8-8a94-5e23fabe0afc.png)

**Comment by Feichtmeier** [comment]
Overlooked. Thanks. Will fix it

**Comment by Feichtmeier** [comment]
Oh but this is the wrong repo again. Can you close this and reopen this in the shell repo? This is actually the 🐚 talking to you :)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/40207647-e8588be6-5a35-11e8-90fc-902cff4d71f7.png)

**Comment by ReyLeonardAmorato** [comment]
Sorry if I posted in the wrong repo, I can't tell the difference between the two. I shall close this.

**Comment by Feichtmeier** [comment]
Np it's fixed thanks for reporting!! :)
