### ISSUE TITLE
Treeview header button has no hover effect, sidebar separator is too light

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/gtk-communitheme#453]
The treeview header button has no hover and active effect. The sidebar separator is too light and the treeview button blends into the sidebar too much.
![sidebartv](https://user-images.githubusercontent.com/27529229/40129288-e7cb1c28-5901-11e8-9797-d3fe27f73fad.gif)

**Comment by Paz-it** [comment]
I disagree about the separator. I think it's clean and elegant.

**Comment by godlyranchdressing** [comment]
It'd be fine if you couldn't interact with the treeview header buttons.

**Comment by clobrano** [comment]
Just a note: sidebar separator on Nautilus now it's the same as in gnome control center (settings), but these separators are defined in different places

https://github.com/ubuntu/gtk-communitheme/blob/c018f322f4b8dd97dcc47b5c61c4c396ee7a290d/Communitheme/gtk-3.0/_apps.scss#L55

https://github.com/ubuntu/gtk-communitheme/blob/c018f322f4b8dd97dcc47b5c61c4c396ee7a290d/Communitheme/gtk-3.0/_common.scss#L3767

**Comment by godlyranchdressing** [comment]
The separator between elements within the sidebar shouldn't be darker than the separator between the sidebar and a whole other view (which is now how it is in both control center and nautilus). I never noticed the difference between the sidebars in nautilus and control center, but I'd label control center the odd one out instead of Nautilus. What if we try to standardize things like this?

Nautilus
```
placessidebar separator { background: #e1e1e1; } // separators within the sidebar
separator { background: #ccc } // separators outside
.view { border-bottom: 1px solid #f5f5f5 } // lightening the separator between treeview rows
```

Control Center
```
list separator { background: #E1E1E1 } // separators within the sidebar
separator { background: #ccc } // separators outside
```

![cc](https://user-images.githubusercontent.com/27529229/40205855-affc2d78-59fb-11e8-9a41-80b4bde023a2.png)
![sidebar2](https://user-images.githubusercontent.com/27529229/40205856-b013b290-59fb-11e8-8caf-b4a11cd2bded.png)

I can make a PR.

**Comment by clobrano** [comment]
Previously separator in Nautilus was way too dark to me, so I changed it, but this one looks good
