### ISSUE TITLE
Pressed toggle button has no hover effect

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#457]
A toggle button that is toggled/active has no hover effect. This can be seen in `gtk3-widget-factory`. Press one of the toggle buttons (so that it looks sunken, and has a dark background) - if you move the mouse away from it then back over, the button no-longer gets lighter when the mouse passes over.

**Comment by clobrano** [comment]
what do you mean by toggle button? Checkbutton (squared) or Radiobutton (circled)?

**Comment by CDrummond** [comment]
No, just a regular button that stays pressed when toggled. Look at `gtk3-widget-factory`, first page, there is a column of buttons (to the right of the combo-boxes). The top 4 are all toggle buttons. If you hover over the 1st, it gets lighter. Now press it - so that it is toggled - it gets a darker background. Move the mouse out, and back over this pressed button, and no hover effect is seen.

**Comment by clobrano** [comment]
:man_facepalming: sorry, it's even written in the button.
:+1:
