### ISSUE TITLE
Switch expands header bar

### ISSUE THREAD

**Issue by zappedfish** [ubuntu/gtk-communitheme#462]
![test](https://user-images.githubusercontent.com/36744029/40249569-7768dc6a-5ae4-11e8-9248-2c73f977fe0c.gif)

![screenshot from 2018-05-18 21-45-49](https://user-images.githubusercontent.com/36744029/40249756-04fc1678-5ae5-11e8-9b23-f3fc3026027b.png)
(it also make buttons look weird)

**Comment by clobrano** [comment]
Nice spotted, thanks!
