### ISSUE TITLE
.context-menu border in light, bradius of last-child in dark & sub-menu placement

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#464]
For the first-child in the light theme (which is the last-child in nautilus? =D) there is a tiny border-bleed:
![lightborderbleed](https://user-images.githubusercontent.com/15329494/40300769-7fbcaeb6-5cea-11e8-80f4-d6ec8dc7ace0.gif)

The border-radius of the last-child for the dark theme (at least in EOG) seems to be small_radius on all edges:
![darklastchild](https://user-images.githubusercontent.com/15329494/40300801-975345ee-5cea-11e8-86d7-78d1a4bb3ffe.gif)

The sub-menu seems to popup like 2 or 3px too early (meaning the "frame" of the submenu could be placed exactly at the edge of the context-menu, they overlap atm):
![submenu](https://user-images.githubusercontent.com/15329494/40300844-b546cc24-5cea-11e8-8cbf-8b3a0f9ff591.gif)

Edit: also in non CSD menus we have the wrong border-radius for both first and last child:
![peek 2018-05-21 13-43](https://user-images.githubusercontent.com/15329494/40305972-2188c5b0-5cfd-11e8-88a2-aaba5983a5b3.gif)

**Comment by Feichtmeier** [comment]
Not sure if this is wanted? @godlyranchdressing 
![image](https://user-images.githubusercontent.com/15329494/40325038-b30579f6-5d3a-11e8-86a2-3b0eedac7276.png)
(The separators are almost invisible - I was never a fan of them, but this looks like it is not wanted - either remove it or bring back the old color? :D no idea really)

Maybe I've merged the PR once again ... - I didn't realize that the context-menu might also be affected

**Comment by Paz-it** [comment]
@Feichtmeier 
I wish they will not be visible, just the way it is in your SS. so much cleaner and elegant this way.

**Comment by clobrano** [comment]
> The separators are almost invisible - I was never a fan of them, but this looks like it is not wanted - either remove it or bring back the old color?

We should take into account developer desire :) if he/she put the separators, we should try to find a nice way to style them

**Comment by Paz-it** [comment]
I agree. @godlyranchdressing  styled them the best way :))

**Comment by Feichtmeier** [comment]
I like it too! Just wondering if this was wanted :dancer:

**Comment by madsrh** [comment]
![image](https://user-images.githubusercontent.com/3986894/40607104-c9bc7fc8-6267-11e8-95cd-c92fbd60b0c6.png)

**Comment by Feichtmeier** [comment]
@madsrh @godlyranchdressing @vinceliuice @clobrano 

Cant' we just remove the border radius for hovering menu entries completely and add a padding to the context-menus? This would make everything hell lot of easier and why ship something broken if the solution is so easy yet does not look weird (quiet the opposite).

As proposed in the closed PR [:](https://github.com/ubuntu/gtk-communitheme/pull/439#issuecomment-388651032)
![39971219-ebffff54-56f7-11e8-9fcc-18256e86b370](https://user-images.githubusercontent.com/15329494/40608276-3b4353bc-626b-11e8-9088-5c1108832441.gif)

And that's also very similar to the shell:
![peek 2018-05-28 11-31](https://user-images.githubusercontent.com/15329494/40608185-005a3d06-626b-11e8-98de-216190fa9156.gif)

And basically every other context-menu out there on the web with round corner :)

**Comment by clobrano** [comment]
Padding looks good to me too, maybe I just use the same (small) padding in shell as well

**Comment by madsrh** [comment]
I say +1 for this because it solves the headache, BUT I've said this before _(in an issue I can't find it atm_):
IMHO the padding looks broken, and the current doesn't (_except for where it's actually broken_ 🤡 )

Beautiful and clean IMO:
![image](https://user-images.githubusercontent.com/3986894/40610926-9551d820-6274-11e8-9790-29fb24e0b3cc.png)

IF there should be top / bottom padding IMO overdoing it - like the shell above - would make it more obvious that this isn't an issue.

**Comment by Feichtmeier** [comment]
Theme idea is beautiful idd.
Sadly we also still have also a border bleed for the first and last child hover. You can even see that inthe pic you posted mads :D it's just tiny but it's there

**Comment by Feichtmeier** [comment]
@madsrh @luxamman @clobrano 
I tried @Paz-it 's idea and I love it:
![pazitftw](https://user-images.githubusercontent.com/15329494/40915786-a007b03a-67fd-11e8-8d32-63c5cc2727e5.gif)
- solves all problems
- looks like the popovers:
![pop](https://user-images.githubusercontent.com/15329494/40915810-bc10282a-67fd-11e8-9227-5433dddf0641.gif)
What do you think?

**Comment by madsrh** [comment]
Perfect! The other suggestion looked like a compromise - this one doesn't 👍 Please merge 😀
