### ISSUE TITLE
Some check buttons cropped

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gtk-communitheme#466]
Just noticed in Update Manager:
![zrzut ekranu z 2018-05-22 12-11-33](https://user-images.githubusercontent.com/1629120/40359304-2cb7fca4-5dba-11e8-99ff-29d7327cbbe5.png)

Here's standard Ubuntu session:
![zrzut ekranu z 2018-05-22 12-13-11](https://user-images.githubusercontent.com/1629120/40359324-3f3cf262-5dba-11e8-8ae3-bf1353e6a9a9.png)

**Comment by madsrh** [comment]
Hi
This has been reported so I'm closing this issue.

https://github.com/ubuntu/gtk-communitheme/issues/343

**Comment by mivoligo** [comment]
Ah OK. I was searching for "update" but could not find. Turns out I should look into closed issues as well :)

**Comment by madsrh** [comment]
No problem, thanks for reporting it 😁
