### ISSUE TITLE
Treeview.view.header background-color 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#467]
![adwaita_treeview_header](https://user-images.githubusercontent.com/15329494/40369086-85e0d800-5ddd-11e8-9ffc-13361f01062d.png)
![ambiance_treeview_header](https://user-images.githubusercontent.com/15329494/40369089-8917cbfa-5ddd-11e8-99e2-f76524fa416e.png)
![canta_treeview_header](https://user-images.githubusercontent.com/15329494/40369098-8c05a30a-5ddd-11e8-8a7a-408691371019.png)
![materia_treeview_header](https://user-images.githubusercontent.com/15329494/40369105-8ec2681c-5ddd-11e8-985b-f1f349916e41.png)

And this is our treeview header:

![communithem_treeview_header](https://user-images.githubusercontent.com/15329494/40369112-9161dbfc-5ddd-11e8-9b3d-35dc26671213.png)

____

The way it is colored in our theme makes it look like the header does not belong to the table. Every other theme I found colors the header of the table in the same color as the table. Especially in the dark theme:
![image](https://user-images.githubusercontent.com/15329494/40369608-9d6f3e8e-5dde-11e8-971b-b04e22996836.png)
(I actually used a  different color for the dark theme here but I think some other  PR has overwritten this)
I think it would be better if we color the header in the same color as the rest of the table in both dark and light themes and dark backdrop + light backdrop.

**Comment by godlyranchdressing** [comment]
>(I actually used a different color for the dark theme here but I think some other PR has overwritten this)


@Feichtmeier That'd be mines. The added background-color line overrode the hover and active effects for some reason. Once it looks like a button and not like part of the treeview.

I just did some experimenting and adding:

```
&:not(:hover), &:not(:active) { background-image: image($bg_color); }
&:hover, &:active { background-image: none; }
```

Underneath %column_header_button will have the treeview header use $bg_color for its normal state without overriding the hover and active effects.
