### ISSUE TITLE
Text color in "software" - warning color should be orange? !not .white  

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#471]
![screenshot from 2018-05-22 23-20-03](https://user-images.githubusercontent.com/37431503/40391585-712ee37c-5e21-11e8-8b3e-e59ad59b87f1.png)

**Comment by clobrano** [comment]
Nice, a custom styled infobar :disappointed:

**Comment by Paz-it** [comment]
@Feichtmeier it looks like it's already fixed : 
![screenshot from 2018-06-02 10-08-29](https://user-images.githubusercontent.com/37431503/40871879-f9f1b2f6-664c-11e8-9eff-974c2185eed5.png)

**Comment by Feichtmeier** [comment]
Oh okay thanks !
