### ISSUE TITLE
Color enhanchment : suggestions in Nautilus

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#472]
as you can see in my screenie : 
![screenshot from 2018-05-23 03-48-36](https://user-images.githubusercontent.com/37431503/40397790-47ea4cce-5e3d-11e8-9c68-d34f387f8ddf.png)
Too many colors, right? 
So...
What if the search area bg will be #efeded (the same as sidebar)?
What if(2) the underline of the column headerbar will be no more? 
What if(3) The canvas/view area will be #f2f2f2 (the same as column header bar) 
End if 
# 
Then it will look much more harmonious and flowing and less bright to the eyes .
If I remember well, it means to have base.color : #f2f2f2 instead of #ffffff.    
What do you think?

**Comment by clobrano** [comment]
Hi @Paz-it, thanks for contributing ;)

I can tell you that there are two threads of work on this exact view, so we'll probably change something in the coming weeks.

That said:

>  What if the search area bg will be #efeded (the same as sidebar)?

With current colors, it will clash with tab view: unfocused tabs have sidebar color already

![image](https://user-images.githubusercontent.com/2883614/40408835-2b4a64e2-5e69-11e8-85bb-e04dcd0bb28d.png)

However, treeview's color is different than folder view's one (it's brighter) so yes, it's something to work on

**Comment by Paz-it** [comment]
Hi @clobrano , ;)
I see what you mean, the tabs make it even more complicated. 
The all area looks like a big mess :))...
Radiance : 
![screenshot from 2018-05-23 10-58-55](https://user-images.githubusercontent.com/37431503/40411663-b2e4b898-5e79-11e8-9149-07a645923aff.png)
 Communitheme current :
![screenshot from 2018-05-23 11-00-59](https://user-images.githubusercontent.com/37431503/40411722-e4a2c816-5e79-11e8-98c0-7ea888aa1fb2.png)
Something to work on for sure ..

**Comment by zappedfish** [comment]
New Nautilus versions will probably put search field in the headerbar so it should looks less messy in the future 
![image](https://user-images.githubusercontent.com/36744029/40586781-ecb9fd60-61d7-11e8-9cfc-377085cf98ea.png)
[Source](https://gitlab.gnome.org/GNOME/nautilus/issues/322)

**Comment by clobrano** [comment]
closed by #532 and #389
