### ISSUE TITLE
Square instead of a circle in a radiobutton

### ISSUE THREAD

**Issue by slackmate** [ubuntu/gtk-communitheme#473]
I have noticed a theme issue in the Preferences window of the GNOME Dictionary. There one can select a dictionary source. The issue is that if the currently highlighted source is not the selected one then there is an empty square on the left instead of a circle. Best illustrated with a screenshot. The "Ambience" theme does not have this issue.

![dictionary](https://user-images.githubusercontent.com/30923711/40411219-1755e90a-5e70-11e8-8d71-8b98d782807a.png)

**Comment by clobrano** [comment]
Thanks @slackmate, it seems that an old fix we made is not working here

**Comment by slackmate** [comment]
Thanks @clobrano for fixing this 👍
