### ISSUE TITLE
Unreadable labales in Logs 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#477]
![screenshot from 2018-05-25 04-04-18](https://user-images.githubusercontent.com/37431503/40520963-aec37034-5fd1-11e8-86b1-20e1d5fcd83d.png)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/40583725-6ed75192-6194-11e8-852d-700438774b9f.png)

**Comment by madsrh** [comment]
@Feichtmeier Hmmm, ny first thought was gray like Adwaita, but maybe that's too much gray.
The selection blue or orange might also fit here.

**Comment by madsrh** [comment]
I think this is a good solution. It follows upstream. But not as branded as using blue or orange, but we don't know where else this might show up, so this is less "dangerous".

Better play it safe 😁
