### ISSUE TITLE
Firefox menu border issues - recommended solution

### ISSUE THREAD

**Issue by vinceliuice** [ubuntu/gtk-communitheme#483]
```
Hello! I'm vince, I find your theme have rounded border menu style,
but there is a background below the Firefox menu 
（Firefox's own program can't remove this background），
so I suggest that maybe you can remove the firefox menu borders to fix this issue。

Here is the code to fix this:
---------------------------------
window.background:not(.csd) { // firefox menu
  .menu { border: none; }
}
---------------------------------
You can add this under menus
```
![ubuntu 64 -2018-05-26-11-37-35](https://user-images.githubusercontent.com/7604295/40572303-f07a304e-60da-11e8-816a-83e240f15969.png)
Then it will looks like this:
![ubuntu 64 -2018-05-26-11-36-48](https://user-images.githubusercontent.com/7604295/40572305-fb331870-60da-11e8-9cf0-7b20b611b4f2.png)

**Comment by Paz-it** [comment]
Hi @vinceliuice, Thank you for your help. I suggest you to change the header of you subject to:
" Firefox menu border issues - recommended solution".

**Comment by Feichtmeier** [comment]
Hi @vinceliuice ! Thanks - that's the fix from our e-mail, right? =)
We've tried that before - for whatever reason it did not work when I tried it. Could you open a PR?

**Comment by vinceliuice** [comment]
@Feichtmeier Yes, we contacted before，I will open a PR to fix this

**Comment by Feichtmeier** [comment]
Closed by https://github.com/ubuntu/gtk-communitheme/pull/485
Thanks @vinceliuice
