### ISSUE TITLE
Light separator over header bar in Gedit side panel

### ISSUE THREAD

**Issue by ed10vi** [ubuntu/gtk-communitheme#484]
Hello.
Here you can see that the side panel separator is light even over the header bar
![captura de pantalla de 2018-05-26 23-54-04](https://user-images.githubusercontent.com/569353/40580523-3f1628c4-6140-11e8-921c-b577c561ab49.png)

**Comment by Paz-it** [comment]
I tried to fiddle a bit -
at the *panned separator* values but could't make it right. but that is the place to check.
