### ISSUE TITLE
Change app launcher icon

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#49]
Change app launcher icon to a white Ubuntu logo with a darker background
https://community.ubuntu.com/t/mockups-new-design-discussions/1898/162

![image](https://user-images.githubusercontent.com/3986894/34906944-1d2216ce-f877-11e7-9725-9ceff59d9114.png)

![image](https://user-images.githubusercontent.com/3986894/34910897-694e3838-f8be-11e7-98e9-a06e380da737.png)

**Comment by godlyranchdressing** [comment]
[Carried over to here](https://github.com/Ubuntu/gnome-shell-communitheme/issues/23)
