### ISSUE TITLE
Keyboard focus for switches should span whole widget

### ISSUE THREAD

**Issue by ya-d** [ubuntu/gtk-communitheme#491]
Currently only the "knob" is surrounded by the dotted orange line which is hardly visible and differs from other widgets. The selection ring should span the whole widget with some padding.

<img width="75" alt="keybord focus_switch" src="https://user-images.githubusercontent.com/30781876/40607698-806e540c-6269-11e8-97cd-8a1f38a41f8e.png"> <img width="306" alt="keybord focus_slider" src="https://user-images.githubusercontent.com/30781876/40607702-84194184-6269-11e8-9539-3ecf31bba9aa.png">

**Comment by clobrano** [comment]
If the ring is around the knob, it means it's the selected widget. Not sure we can "transfer" the selection to the whole switch. I need to investigate a bit more

**Comment by ya-d** [comment]
Would it be possible to add an asymmetrical padding to achieve something like this?

![keybord focus_switch_padding](https://user-images.githubusercontent.com/30781876/40683676-8190d19e-638f-11e8-95b9-72fff1cbe52f.png)

**Comment by clobrano** [comment]
:thinking: I'll try!

**Comment by ya-d** [comment]
Argh. I just figured that the selection ring probably moves with the knob so this hack won't work for both on and off states. But even the one with symmetrical padding looks better to me and is more visible in any case.

**Comment by clobrano** [comment]
Uhm, right I didn't think at all myself. Theoretically we know in which state the knob is, but it's getting a bit complex. What about the same as the buttons and treeview row, selection ring slightly inside the knob?

**Comment by ya-d** [comment]
I would say its better than the selection ring being the border itself but might get a bit small. I tend to prefer the outer ring even if it crosses the switch. But thats only a personal preference.

![keybord focus_switch_padding2](https://user-images.githubusercontent.com/30781876/40686463-ab29f046-6397-11e8-9874-add5577d4a7a.png)

**Comment by Paz-it** [comment]
Just a stupid question - Why do we need this ring anyway??!!??

**Comment by Feichtmeier** [comment]
It is the focus ring. Some people use the tab key to travel through the UI elements. The focus ring indicates were the focus is

**Comment by clobrano** [comment]
Unfortunately outline-offset property cannot be asymmetric, so the best we can have is this one

![image](https://user-images.githubusercontent.com/2883614/41199987-ad30f70a-6c9c-11e8-8970-37cb49b0ddd1.png)

the thin line does not help, but bigger would be even worse

**Comment by Feichtmeier** [comment]
I'd prefer the current solution then which looks pretty logical to me. This one ∆ looks like something went wrong in my opinion

**Comment by ya-d** [comment]
Agreed. What about a very minor inset?

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/41229362-00c4e5c2-6d7c-11e8-9f9d-e4e3e8317124.png)
