### ISSUE TITLE
Flat combobox in evolution

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#493]
Evolution's new message window contains 2 combo-boxes to choose message type, and bullet list type. With most themes these are not flat, with Communitheme they are. However, the flat look does not look right - as the drop down arrow can look separate from the text.

Communitheme:
![communitheme](https://user-images.githubusercontent.com/1141694/40654460-51e62cfe-6336-11e8-9742-0cc93fae5dac.png)

Ambiance:
![ambiance](https://user-images.githubusercontent.com/1141694/40654472-580fa754-6336-11e8-9901-7a5cb72214fc.png)

**Comment by madsrh** [comment]
+1 they shouldn't be flat here. IMO they should look exactly like a regular combobox 😃 

The _Plain text_ and _Normal_ combos are styled similar to  _Signature_ in both Adwaita and Ambiance.
![image](https://user-images.githubusercontent.com/3986894/40892106-4e03a8e0-6792-11e8-803f-953a3f8d9c53.png)

**Comment by madsrh** [comment]
Sorry for the newbie questions, but @clobrano are the combos flat because they are in a toolbar? Would changing them here be an individual app fix or would this impact other places in the theme? Is there another place where there are combos in a toolbar?

**Comment by clobrano** [comment]
Yes @madsrh, some time during the development we added a flat style to toolbar buttons. Without those lines of code, the above picture would be this way

![image](https://user-images.githubusercontent.com/2883614/40973246-db50660c-68c3-11e8-8cb3-77ca3f4b4266.png)

And it would be this way in every toolbar. Probably all the toolbars out there have this same problem, but I don't remember any other application that has one at the moment.

We can keep the current code only for toolbar buttons explicitly defined as flat (button.flat) by the developer

**Comment by madsrh** [comment]
That looks much better. Seems like a good solution @clobrano
