### ISSUE TITLE
Spinbutton dark variant hover effect is too bright

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#498]
previously reported [here](https://github.com/ubuntu/gtk-communitheme/pull/469#issuecomment-391134919)

![image](https://user-images.githubusercontent.com/2883614/40671728-f8adf45a-636c-11e8-8e08-2bbfe5d59fb0.png)

**Comment by Feichtmeier** [comment]
Works but something happend to the spin btns there is some strange shadow in them:
![yayacdscsd](https://user-images.githubusercontent.com/15329494/40678612-45d1eaf2-6381-11e8-8287-76bc50b62753.gif)
What happened to the dark theme? :O
