### ISSUE TITLE
Hover of togged headerbar buttons very harsh

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#501]
When hovering over a pressed headerbar button (e.g. the search (magnifying glass) button in nautilus) the change in background colour is a bit harsh. Does it need to brighten by so much? Other hover effects are not as drastic.

**Comment by Feichtmeier** [comment]
![peek 2018-05-31 15-31](https://user-images.githubusercontent.com/15329494/40785041-afeeaabc-64e7-11e8-8794-864ecd091dac.gif)
