### ISSUE TITLE
Selected text is hardly readable in the dark theme

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#502]
Because the text color of the darktheme is bright, the light blue makes selected text very hard to read in the dark theme:

![image](https://user-images.githubusercontent.com/15329494/40800000-6e2e3156-650f-11e8-8201-fb224a2f0197.png)

First ideas:

A) $text_selection: if($variant == 'light',#C4E4F0, lighten($blue,10%));

![image](https://user-images.githubusercontent.com/15329494/40800180-edd3fc24-650f-11e8-8a6e-f15898c50b03.png)

B) $text_selection: if($variant == 'light',#C4E4F0, $blue);

![image](https://user-images.githubusercontent.com/15329494/40800234-0f7d0d2a-6510-11e8-92f4-24485cbebaf2.png)

@madsrh @luxamman @clobrano 
Any other ideas?

**Comment by clobrano** [comment]
Test selection should be dark, it's a mistake from last PR

**Comment by madsrh** [comment]
![image](https://user-images.githubusercontent.com/3986894/40803103-ed21c11e-6517-11e8-8aa8-5dfc905154a5.png)

**Comment by Feichtmeier** [comment]
Ah, okay changing text-color would be an option, too. So I change this locally in %selected_text, alrighty?

%selected_text {
  $c: $text_selection;
  $tc: if($variant==light,$text_color,#2D2D2D);
  background-color: $c;
  color: $tc;

![image](https://user-images.githubusercontent.com/15329494/40803171-35bc47e6-6518-11e8-8672-1abd3e2f8c33.png)

**Comment by Feichtmeier** [comment]
Okeee. Talking about text-color. Light theme backdrop text color looks a bit weird, too:
![carlandmadso](https://user-images.githubusercontent.com/15329494/40803913-21f02e56-651a-11e8-83db-c8d494b89550.gif)
Any preferences? @madsrh @clobrano

**Comment by madsrh** [comment]
@Feichtmeier well, it depends on if we still want to follow the overlay/multiply idea? Then it should become darker. Below I've made the text slightly lighter, but my first thought was the the background color should turn gray

![image](https://user-images.githubusercontent.com/3986894/40804395-6e877408-651b-11e8-9248-dc36ac045ae0.png)

**Comment by Paz-it** [comment]
For the light theme : 
![screenshot from 2018-05-31 22-46-25](https://user-images.githubusercontent.com/37431503/40804709-c191827a-6524-11e8-987c-aeba0e77bbdb.png)
Agree with @madsrh  but goes a bit lighter

**Comment by Feichtmeier** [comment]
![yolf](https://user-images.githubusercontent.com/15329494/40804936-071c6e66-651d-11e8-9354-752bb01f7297.gif)
![olft](https://user-images.githubusercontent.com/15329494/40804937-0733979e-651d-11e8-8ea4-f759cf52aefd.gif)

@madsrh okee?

@clobrano I can't change it here:
$backdrop_selected_fg_color: ...
Because that changes many other stuff.
So I change it here, oke?
```
%selected_text {
  $c: $text_selection;
  $tc: if($variant==light,$text_color,#2D2D2D);
  background-color: $c;
  color: $tc;

  &:disabled { color: mix($tc, $c, 50%); }

  &:backdrop {
    background-color: _backdrop_color($c);
    color: $slate;//$backdrop_selected_fg_color;

    &:disabled { color: mix($backdrop_selected_fg_color, $c, 30%); }
  }
}

**Comment by madsrh** [comment]
@Feichtmeier I can't see that the blue selection color changes in the light version. Shouldn't it just a tiny tiny bit darker/lighter?

And the blue color in the dark version is IMO too much. A more subtle change would be good (also for the text).

**Comment by Feichtmeier** [comment]
Yeah because that _darken function didn't care for the light case.

@function _backdrop_color($c) {
  // adjusts colors for use in the backdrop state
  // colors are darkened when using the dark theme so they aren't such a light grey
  @if $variant != 'light' {
    $c: darken($c, 7.5%);
  }
  ____

@function _backdrop_color($c) {
  // adjusts colors for use in the backdrop state
  // colors are darkened when using the dark theme so they aren't such a light grey
  @if $variant != 'light' {
    $c: darken($c, 5.5%);
  }
  @else {
    $c: darken($c, 4.5%);
  }

Like this?
![wurst](https://user-images.githubusercontent.com/15329494/40805430-8c792940-651e-11e8-80f6-b024b9e44354.gif)
![trump](https://user-images.githubusercontent.com/15329494/40805431-8c9d0752-651e-11e8-9ea3-75ae9b902a35.gif)

**Comment by madsrh** [comment]
Looks good.

I'm a little in doubt if the dark theme shouldn't become darker anyway 🤦‍♂️  Doesn't it steal too much focus currently in backdrop? 🤔

**Comment by Feichtmeier** [comment]
That's what I thought too! The dark theme does not work like the light theme!
Okay, so I could start off with the text backdrop and use other issues/PR for the rest of the backdrop?

**Comment by Feichtmeier** [comment]
![seltextlight](https://user-images.githubusercontent.com/15329494/40811692-7a0b8514-6532-11e8-87bf-11afe80c3c80.gif)
![seltextdark](https://user-images.githubusercontent.com/15329494/40811693-7a2bf25e-6532-11e8-93e3-01198a42fcd5.gif)
