### ISSUE TITLE
Switch btn top- border is missing?

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#504]
![screenshot from 2018-06-01 01-34-31](https://user-images.githubusercontent.com/37431503/40822666-e26c1c70-6575-11e8-8fc3-bfc071bb689a.png)

**Comment by clobrano** [comment]
It is not missing, it is just of a color very similar to headerbar. Being the headerbar so dark, the switch design with top shadow creates this kind of illusion.
