### ISSUE TITLE
Firefox menuitem is round on not round menu

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#510]
![peek 2018-06-04 15-13](https://user-images.githubusercontent.com/15329494/40919618-4f2c95d8-680a-11e8-91f7-9fb3c9bcd3dc.gif)

:face_with_head_bandage: 
Yeah.. well, @madsrh that was a little early.

**Comment by Feichtmeier** [comment]
Okay chrome fixed:
window.background.chromium {
....
  menuitem { border-radius: 0;}
}

**Comment by vinceliuice** [comment]
Hey guy! I have pulled a PR to fix this and some other issues. you can check "Fixed gedit and menu issues #519"
