### ISSUE TITLE
Tweak the orange line in stackswitcher

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#52]
Currently the orange line isn't centered between the bottom and the label. 
<img width="834" alt="skaermbillede 2018-01-13 19 36 44" src="https://user-images.githubusercontent.com/3986894/34910003-dde53a5a-f8ac-11e7-8fa0-83ce86c6b712.png">

I know this is a hairsplitting detail, but this really bugs my eye nonetheless. Could we do one of the following: **centered**, right **underneath** the label or at the **bottom**?
![screenshot-from-2018-01-13-10-29-31](https://user-images.githubusercontent.com/3986894/34910016-236b5708-f8ad-11e7-9b7c-32f4cf562f98.gif)

**Comment by godlyranchdressing** [comment]
That's kind of why I wanted to go with this, which also solves the disembodied left and right arrows for me. How does this look? 

![pathbar](https://user-images.githubusercontent.com/27529229/34918077-04a25d5e-f924-11e7-9ebb-00ecd039e5f3.png)
