### ISSUE TITLE
Replace the dotted lines for more content

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#523]
Sorry for the vague title - feel free to rename it 😃 

I'm not a fan of the dotted lines when there's more content. I know that Adwaita and Arc has this too. Ambiance has nothing at all. 
Would something like this be possible @godlyranchdressing @nana-4 ?

Might not be the best suggestion 🤷‍♂️ 

 ![untitled-1](https://user-images.githubusercontent.com/3986894/41067234-18cda874-69e5-11e8-92d3-7b7ce01b0076.gif)

Or white?

![image](https://user-images.githubusercontent.com/3986894/41068296-24061e2a-69e9-11e8-9937-7707b272b828.png)

**Comment by Paz-it** [comment]
The first one look good to me!

**Comment by ya-d** [comment]
I grew to like it somehow. I find the dark shadow to be much more obtrusive and alien. The white fading looks good imho. Not sure if this should work against any background color though.

**Comment by madsrh** [comment]
I'm simply just asking. If everyone else is happy with the dots we shouldn't spend any time on this at all 😁

**Comment by ya-d** [comment]
You're perfectly right to do so. I found them to be strange as well - but grew to like them. And after all, they're very flat at least 😄

**Comment by Feichtmeier** [comment]
I was never a big fan of that dotted lines: https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/445?u=frederik-f 
:smile: 
I think what could work is the same level of depth that the gtk buttons have. Anything more would look like there is too much depth.
If this does not work maybe @ya-d is right to keep them :man_shrugging:

**Comment by Feichtmeier** [comment]
This thing is called
undershoot
and this is how it looks without:
![noundershoot](https://user-images.githubusercontent.com/15329494/41084300-093a7fbe-6a34-11e8-98f7-3402f1ed2e4d.gif)

**Comment by ya-d** [comment]
I don't even even beat the drum to keep them - I just don't like the dark shadow proposal 😝

Nowadays it might even work without indicating "scrollability" - although I like the idea from a usability standpoint.

Fading the list or give it a shadow might conflict with these "end indicators" though.

**Comment by madsrh** [comment]
> Nowadays it might even work without indicating "scrollability" 

I simply can't think of another place they are used?

**Comment by CDrummond** [comment]
Dark shadow looks the best to me - as it gives the impression the content goes underneath. Perhaps a more subtle shadow though?

Never liked the dotted lines - they just look like an after thought. They also interfere with the scrollbar groove in gedit (which is more noticeable if you use a dark gedit colour scheme).

**Comment by Feichtmeier** [comment]
![lolo](https://user-images.githubusercontent.com/15329494/41109125-89837dc8-6a76-11e8-8dc9-826d26e6e329.gif)
