### ISSUE TITLE
Dark variant nautilus white bg and text unreadable

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#540]
Previously reported [here](https://github.com/ubuntu/gnome-shell-communitheme/issues/213)

**Comment by Feichtmeier** [comment]
Did we "hardcore" the colour of view for Nautilus? Other than that every colour has a dark variant now

**Comment by clobrano** [comment]
That's possible, I don't have dark variant in mind since Nautilus should not available in this variant
