### ISSUE TITLE
Some Open buttons have a weird white border

### ISSUE THREAD

**Issue by jlemonde** [ubuntu/gtk-communitheme#551]
For example :
![capture d ecran de 2018-06-15 17-44-17](https://user-images.githubusercontent.com/30623792/41477324-2ea1a214-70c4-11e8-9a9d-199c758ebcf9.png)
Expected :
![capture d ecran de 2018-06-15 17-46-54](https://user-images.githubusercontent.com/30623792/41477325-2efe8ee8-70c4-11e8-89ec-5e4edc348479.png)

Most open buttons are correct, but for instance the one when you want to attach a file from Telegram is not, and another few examples neither. They have a stronger border than the other buttons of that kind, such as the Cancel button ("Annuler" in French).
![capture d ecran de 2018-06-15 17-51-45](https://user-images.githubusercontent.com/30623792/41477522-d59575e6-70c4-11e8-926b-cc4b839878e0.png)

If a get new examples, I'll add them below. I've noticed that a few times in different contexts.

**Comment by clobrano** [comment]
Hi @jlemonde thanks for reporting this! Is the first picture from Telegram? Web or Desktop version?

**Comment by jlemonde** [comment]
Yes, it is from the desktop version. To reproduce, open a chat in Telegram and click on the paper-clip icon.

![capture d ecran de 2018-06-18 14-44-41](https://user-images.githubusercontent.com/30623792/41536530-2b378104-7306-11e8-8292-f9ac1b6f73db.png)

**Comment by clobrano** [comment]
Alright now I got it. It is not wrong, it's the "default action" highlight. If you press enter without touching anything "Ouvrir" is the button that will be pressed. Same thing happen on bright buttons, just the border is dark

**Comment by clobrano** [comment]
closing this now, feel free to comment again if you feel I misunderstood something :wave:
