### ISSUE TITLE
editor-color-sample border-bleed

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#552]
![image](https://user-images.githubusercontent.com/15329494/41478074-b7d5452a-70c6-11e8-8eed-6ed227e8670d.png)
![image](https://user-images.githubusercontent.com/15329494/41478105-ca7e9d20-70c6-11e8-99b5-1558ca160dde.png)

**Comment by clobrano** [comment]
Not sure it's a border bleed or a limit of that shape. It's the same problem with switches
