### ISSUE TITLE
Dark theme Gnome-Terminal menus - Light

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#554]
![2018-06-16-114301_1920x1080_scrot](https://user-images.githubusercontent.com/37431503/41497302-37aea978-715b-11e8-9c1e-0212dc079443.png)

**Comment by Paz-it** [comment]
Yes, I'm sure : 
~/.config/gtk-3.0/setting.ini : 
 gtk-application-prefer-dark-theme=1
Any better way to do it?

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/41500273-cca5155c-718e-11e8-8e77-ed0f9ac296e5.png)

**Comment by Feichtmeier** [comment]
Ok?

**Comment by Paz-it** [comment]
:+1:  
Danke! :kissing_heart:

**Comment by Feichtmeier** [comment]
Kein Thema :)
