### ISSUE TITLE
Dark theme - tabs in Natilus -white

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#557]
Column headers fixed after refreshing edge.. :+1: 

Now this : 
![screenshot from 2018-06-16 19-08-27](https://user-images.githubusercontent.com/37431503/41500428-b5e5cb80-7199-11e8-8e78-26d9e534cb5f.png)

**Comment by Feichtmeier** [comment]
notebook > header > tabs {
    background: $porcelain;
    &:backdrop { background-color: $backdrop_bg_color; }

Will do when back home Frome shopping
