### ISSUE TITLE
GNOME Software visibility issue on label and stars 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#559]
Self-explanatory:) :
![screenshot from 2018-06-16 21-17-02](https://user-images.githubusercontent.com/37431503/41501379-098978e2-71ac-11e8-82f7-3472caff7847.png)

Stars hardly recognizable and when hovered they are invisible :
![screenshot from 2018-06-16 21-23-06](https://user-images.githubusercontent.com/37431503/41501474-9b90596c-71ad-11e8-8cc2-87415b3446f7.png)

**Comment by clobrano** [comment]
Hi @Paz-it, I edited the title, otherwise anyone that would contribute would be forced to open the ticket to understand what the problem is.

**Comment by Feichtmeier** [comment]
The stars are also very hard to read in the white version in the "all" stacks. Sadly there are several elements in software without a style class. I already tried to change the orange check marks to green without success. Let's see if we can style the stars for both black and white. The infobar is also some custom infobar which can not be targeted by infobar. Yet I've seen ambiance somehow managed to change its look. Do you have any idea who to tag in here from the ambiance team to help us with the infobar?

**Comment by madsrh** [comment]
I believe there is work being done up stream to fix this.

**Comment by Feichtmeier** [comment]
Really? That would be great. To fix the lack of style classes or to fix the wrong colours somehow in their code directly?

**Comment by clobrano** [comment]
@Feichtmeier we can have a look inside Ambiance code itself, since it's normal css, otherwise I can ask on IRC

**Comment by Paz-it** [comment]
In ambiance under apps/software-center.css :  
 .action-bar {
    background-color: @bg_color;
}

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/41928302-071bb8ba-7975-11e8-815f-7e8ca60d5cbe.png)

no it's called .application-details-infobar

**Comment by clobrano** [comment]
Well, well, not that bad though
