### ISSUE TITLE
Gnome Web: Dark text on dark address bar

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [ubuntu/gtk-communitheme#560]
On Gnome Web's (Epiphany) Incognito mode, The text and and address bar are both dark, making it difficult to read.

![screenshot from 2018-06-17 04-14-25](https://user-images.githubusercontent.com/38913802/41502150-15be715a-71e6-11e8-8ff2-3c1b6004ca6d.png)

While were at it, is the header bar themable too? IMO the cool/blueish grey does not blend well with the current theme.

**Comment by Feichtmeier** [comment]
This looks like some freaky abomination of adwaita mixed with communitheme? :octopus:  What happened there?

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/41775117-e34e132e-7622-11e8-8319-6d5f2508d676.png)
This also happens with the  light theme

**Comment by godlyranchdressing** [comment]
Epiphany's incognito window does this for every theme, I don't think there's a solution, unfortunately.

**Comment by clobrano** [comment]
Thanks @godlyranchdressing, closing this then
