### ISSUE TITLE
Gnome Video selection-mode checks are too big

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gtk-communitheme#562]
Similar to one issue we had in another application (which I don't remember now)

![image](https://user-images.githubusercontent.com/2883614/41510211-c7fa3f1e-7260-11e8-8b59-3c5c2803357e.png)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/41964975-afc73030-79fb-11e8-9677-ae01f75e32db.png)
Changed to 20x20 px
Buuuuuuuut it doesn't apply to videos :D :dagger: 
![image](https://user-images.githubusercontent.com/15329494/41965015-cb3da4f2-79fb-11e8-8d5d-6aeb2e5d339b.png)

**Comment by clobrano** [comment]
Yes, I discovered it yesterday :(

**Comment by Feichtmeier** [comment]
Uhh, and for some reason videos doesn't have that little "no-icon-moment" when clicking Oo oO Oo like in music

**Comment by clobrano** [comment]
It seems that's not fixable :(
