### ISSUE TITLE
Dark theme: nautilus list view header is white when unfocused

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/gtk-communitheme#570]
I know the focus is not on the dark theme for apps that don't use it by default, but am reporting this for what it's worth!
When unfocused, the header of the list view in nautilus is white with the dark theme:

![nautilus_header_dark](https://user-images.githubusercontent.com/1044087/41753281-db5687ae-760f-11e8-8929-4982369fc45b.png)

**Comment by Feichtmeier** [comment]
I am pretty sure I've fixed this last week :thinking: 
Is your installation up to date?

**Comment by Feichtmeier** [comment]
No never mind sorry, that was the iconview :+1: Thanks for reporting fix incoming
