### ISSUE TITLE
Toolbar button hover very hard to see

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#571]
The toolbar hover/mouse-over is very hard to see - it seems to be a very subtle lightening of the background. This can be see in non-headerbar apps such as Evolution, EasyTag, Synaptic, etc.

LibreOffice, however, has a much nicer hover effect - here the button frame is drawn on hover. (Although there is no effect for hovering over toggled buttons).

Perhaps all Gtk apps should follow the LibreOffice style? ie. draw frame on hover?

**Comment by clobrano** [comment]
Considering that there is no special hover for libreoffice toolbar, this sounds weird. I'll look into it, thanks!

**Comment by clobrano** [comment]
So, Libreoffice is taking GTK2 style now, that for toolbar button that is a mix between headerbar (flat) and normal buttons. On normal state is flat, on hover it gets a small 3D effect. Considering that GTK2 isn't as easy as GTK3 to style, I'd like to keep the first. So for GTK3 the solution would be this one

![toolbar-hover](https://user-images.githubusercontent.com/2883614/41901404-1bf18b96-7931-11e8-9783-f4ed7f20feb0.gif)

**Comment by CDrummond** [comment]
Whist it is _slightly_ clearer, (IMVHO) it looks **awful.** Why not use the same button border as for regular buttons? Why does the border have so little contrast? The previous dark (non-3d) hover was much nicer than this. Sorry, but this just looks really bad :-(

**Comment by clobrano** [comment]
I understand you don't like it (really, not that hard to understand :D), but all your questions are already answered in the PR message. Usually when a PR does not get answered by some days it gets merged, we cannot wait forever.

**Comment by clobrano** [comment]
I'm going to open a new PR with a different hover on toolbar, but it will require a change on GTK2 as well

**Comment by clobrano** [comment]
@CDrummond no worries, you are of course not forced to review any PR :) I was only explaining why the change was approved (that is, no one said anything against)
