### ISSUE TITLE
New light-blue selection colour: darker blue when on dark background (proposal)

### ISSUE THREAD

**Issue by jlemonde** [ubuntu/gtk-communitheme#574]
I really enjoy the new light-blue selection colour, although I'd preferred a light orange. But in some places such as in Nautilus' path bar, the blue just doesn't match the other colours:
![capture d ecran de 2018-06-25 11-40-48](https://user-images.githubusercontent.com/30623792/41843255-5a20b6a4-786d-11e8-80fa-3d6474b84c2d.png)

I think that the new light-blue matches pretty well with the orange, **but only when it is on a light background**, such as in the file-renaming field (white background). Here it is beautiful:
![capture d ecran de 2018-06-25 11-54-35](https://user-images.githubusercontent.com/30623792/41843787-b0ebdca6-786e-11e8-9c3b-721b487cfa52.png)

But when it is on a dark background, a light-orange should be a better idea.

Or: put the old orange colour again:
![capture d ecran de 2018-06-25 12-02-31](https://user-images.githubusercontent.com/30623792/41844210-c78be900-786f-11e8-9d08-5d21eb075c5f.png)

It could also be better if it were like the colour in GNOME's overview:
![capture d ecran de 2018-06-25 11-44-32](https://user-images.githubusercontent.com/30623792/41843288-72f2ded2-786d-11e8-9447-90fe26dc427f.png)

**Comment by Feichtmeier** [comment]
Hi @jlemonde 
Well, this was a very "hot" topic on the community hub. And this is somehow the solution most people prefer, thus we have gone for this blue.
Concerning the adaption of the shell entries: we haven't talked about that, so thanks for bringing this up! If we would reduce this issue to the shell entries then this would be the wrong repo, though :D

**Comment by madsrh** [comment]
@Feichtmeier Are you asking me, what I think about using blue for white backgrounds and orange on dark backgrounds?

**Comment by Feichtmeier** [comment]
No: the headerbar entries have a dark background but use the light blue for text selection. In the dark theme we use a darker blue for text selection bcause it looks a bit "sharper" on dark backgrounds. For the same reason I would propose to change the text selection for header bar entries to the same dark blue as we use in the dark variant normal entries text selection

**Comment by madsrh** [comment]
@Feichtmeier Aaahhh, sorry I didn't see the gif.

Sure, let's give it a try 👍 

BTW, while you're tweaking the text colors (again), what do you think about a lighter black for selected text? Is the current Jet? 
Below is the same color as the background, but maybe it's a bit too subtle. Perhaps something in between??? 🤷‍♂️ 

![untitled-1](https://user-images.githubusercontent.com/3986894/41849595-c0aba758-7881-11e8-8dbb-d327f6c3c087.gif)

**Comment by jlemonde** [comment]
Your comboboxentry looks really good :+1: 

I enjoy that stronger blue: it seems less weak than the previous one on dark backgrounds. For the text, a black in between should be amazing: the light one in your gif is too light and the strong one seems too bold...

**Comment by Feichtmeier** [comment]
![peek 2018-06-25 15-32](https://user-images.githubusercontent.com/15329494/41853004-f6c7230c-788c-11e8-9f25-0ed7d2aebdc3.gif)
The text is 5% lighter now. Ok this way?

**Comment by jlemonde** [comment]
Yeah! It looks fine. I can't wait to see the change for real.

**Comment by madsrh** [comment]
+1

![image](https://user-images.githubusercontent.com/3986894/41875999-cdbc7350-78cc-11e8-9e36-91987f317748.png)

**Comment by clobrano** [comment]
@jlemonde might suggest you to change the title of the bug? It would be helpful to see that it actually proposes a change to the dark variant text selection, more that saying that it looks ugly :)
