### ISSUE TITLE
Shell overview window labels (.window-caption) shortened with small font size

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#587]
Previously report here: https://github.com/ubuntu/gnome-shell-communitheme/issues/156

If a font-size smaller than 11 is selected, the .window-caption labels are cut at a certain amount of letters:

![zrzut ekranu z 2018-05-01 13-20-22](https://user-images.githubusercontent.com/1629120/39473003-85243276-4d44-11e8-872f-8bed3e6023c9.png)

This has also been reported upstream and seems to be an Ubunutu font problem:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/378

**Comment by madsrh** [comment]
If no one in the team / community can fix this 🐛 we should ask @didrocks or someone from the desktop team to take a moment to look at this 👀 

It's an upstream bug that affects EVERY distro that doesn't use the stock `Cantarell Regular 11` font _(which explains why it's not a priority for upstream)_ - a lot of users would benefit form this.

**Comment by madsrh** [comment]
Oh, I forgot to write that the reason why this minor issue is **high-prio** to me, is that you "threatened" (used in the most positive way here 😄) to switch back to the old large font size 😉

**Comment by clobrano** [comment]
> If no one in the team / community can fix this bug we should ask @didrocks or someone from the desktop team to take a moment to look at this eyes

Someone in Gnome is working on a fix :)

**Comment by clobrano** [comment]
Closing this now, since we cannot do anything about it
