### ISSUE TITLE
Button label color lightening/darkening on hover

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/gtk-communitheme#592]
After merging the wrong [PR](https://github.com/ubuntu/gtk-communitheme/pull/590#issuecomment-401551256) this is the place to discuss button label hover effects

Darkening on hover:
![image](https://user-images.githubusercontent.com/3986894/41497558-939a9fc0-7157-11e8-9b17-6b75aa97a486.png)

Lightening of hover:
![hover](https://user-images.githubusercontent.com/15329494/41491085-5fb9dfe6-70f7-11e8-8daa-84d3c31cd09c.gif)
![peek 2018-06-16 00-02](https://user-images.githubusercontent.com/15329494/41491308-97d9cf48-70f8-11e8-9ebc-7043082001d3.gif)
Previously discussed here: https://github.com/ubuntu/gtk-communitheme/pull/538

**Comment by clobrano** [comment]
Just to add some context. This is the result of a couple of discussions, one about the hover effect on buttons and one about the spinbuttons to be promoted a button using the mixin function (which is TBD at the moment). I must say I'm not a fan of the label highlight when in hover, but I made the PR to let everyone test it.

Summing it up, -1 for me :smile:

**Comment by madsrh** [comment]
@clobrano and how do you feel about darkening it on hover?

**Comment by clobrano** [comment]
@madsrh it doesn't feel right to me as well. Not sure if it's only the color, but I still prefer the current state

**Comment by Feichtmeier** [comment]
@clobrano when you say current state do you mean the current master?

**Comment by clobrano** [comment]
> @clobrano when you say current state do you mean the current master?

correct, I prefer master

**Comment by madsrh** [comment]
I don't know. I guess I'm kind of neutral too
