### ISSUE TITLE
Suggestion: Reduce the size of the headerbar height.

### ISSUE THREAD

**Issue by izznogooood** [ubuntu/gtk-communitheme#593]
Are you considering this? It looks strange with the default font size and takes opp screen space.

![screenshot from 2018-07-01 15-42-11](https://user-images.githubusercontent.com/23040578/42135016-8d0bcb1c-7d45-11e8-96c1-373a9d2fd817.png)

Unless your targeting touch screens...

**Comment by clobrano** [comment]
Hi @izznogooood, as @madsrh said, thank you for taking time to propose this. As a matter of fact we considered this and we reduced the headerbar size already respect Adwaita and my idea is that current size is fine, even if we're not targeting touch screen. As example, on my 13'' screen the size is good enough for clicking rapidly with the mouse.
If nobody is against my idea, I'll close this later
