### ISSUE TITLE
Gnome Music sidebar selection is gray

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#598]
...should be orange

![image](https://user-images.githubusercontent.com/3986894/42139666-711718ce-7d92-11e8-847b-71664be2033b.png)

**Comment by Feichtmeier** [comment]
It's hard coded :(

**Comment by madsrh** [comment]
I'm closing this as this is [an upstream issue](https://gitlab.gnome.org/GNOME/gnome-music/issues/204)
