### ISSUE TITLE
Remove little gap between Dock and Maximized windows

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#60]
![image](https://user-images.githubusercontent.com/2883614/34951617-2910cdd0-fa17-11e7-9744-750ef67d881b.png)

**Comment by godlyranchdressing** [comment]
I've been trying to fix this forever. I finally figured out that it's an issue with the dock. It's an invisible border. I just removed it since it's very noticeable and for now the box-shadow acts as the border between active windows. [Shell commit](https://github.com/Ubuntu/gnome-shell-communitheme/pull/16/commits/3a32515b0f06421f0d47d39a798b8544e45ea397)

**Comment by galgalesh** [comment]
:raised_hands:

**Comment by ya-d** [comment]
For me this is still present for the header bar area. Also visible in reports by TonyS: https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/327 or jasonflindt: https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/343. No gap for clobrano anymore though 😄 : https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/347

<img width="256" alt="header-dock-gap" src="https://user-images.githubusercontent.com/30781876/35670330-947ed89a-0738-11e8-90f3-7491c7e5398e.png">

**Comment by galgalesh** [comment]
I don't have the gap either.. Maybe it's the conflicting stylesheet from Ubuntu itself?

**Comment by didrocks** [comment]
There is no dock modification for Ubuntu or personal stylesheet, what do you mean @galgalesh ?

**Comment by galgalesh** [comment]
The one in `/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css`

Most of us have cleared the contents of that stylesheet because it was conflicting with our own styling of the dock.

**Comment by didrocks** [comment]
Yes, this is upstream stylesheet, not ubuntu one :)
Btw, I gave a look at this and detailed instructions: https://community.ubuntu.com/t/mockups-new-design-discussions/1898/210 but didn't get feedback on it :(

**Comment by clobrano** [comment]
This looks fixed to me. If the issue still affect anyone, please re-open it
