### ISSUE TITLE
[Nemo integration] Places sidebar - place disappear at click

### ISSUE THREAD

**Issue by rypz79** [ubuntu/gtk-communitheme#601]
Redirected from [https://github.com/linuxmint/nemo/issues/1884](url)

![screenshot from 2018-06-30 20-51-09](https://user-images.githubusercontent.com/28814757/42134110-796fee74-7d3d-11e8-8116-407bf6a85c80.png)

![screenshot from 2018-06-30 20-51-19](https://user-images.githubusercontent.com/28814757/42134112-8e5fa55e-7d3d-11e8-8973-d385d5214776.png)

Nemo works fine with all my other themes

**Comment by madsrh** [comment]
Thank you for taking the time to report this @rypz79. There is already a fix that will land very soon, so I'll close this issue 😄
