### ISSUE TITLE
Dark-Theme: Strange border in Gnome-terminal+Transmition+LibreOffice 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#602]
Looks like the border added is not working well with some apps. not sure if it's only those 3 that I found.
 I didn't add LibreOffice here (it looks awful with and without it) :face_with_head_bandage:   

![screenshot from 2018-07-03 00-36-45](https://user-images.githubusercontent.com/37431503/42188639-804a2392-7e5d-11e8-83a0-0c37144c965e.png)
![screenshot from 2018-07-03 00-53-44](https://user-images.githubusercontent.com/37431503/42188652-8e0e279e-7e5d-11e8-91ed-2c4af4ae7a45.png)

**Comment by madsrh** [comment]
Looks like a semi transparent border:

![image](https://user-images.githubusercontent.com/3986894/42189611-581ffecc-7e59-11e8-934e-92d7411fcd26.png)

**Comment by Feichtmeier** [comment]
Alright then let's remove it again?

**Comment by Feichtmeier** [comment]
uhm, tried an old branch - this does not seem to be caused by the latest PR, sorry.
@clobrano  any ideas?

**Comment by clobrano** [comment]
I can check with git bisect, but not sure I can do it today

Il mar 3 lug 2018, 01:03 Feichtmeier <notifications@github.com> ha scritto:

**Comment by Feichtmeier** [comment]
@clobrano @Paz-it @madsrh 
Oh I need to correct myself:
this IS caused by our latest changes to the dark themes window border! I've only forgotten to restart the shell after reverting the change -.-
So.... remove it again?

**Comment by madsrh** [comment]
Maybe this is a stupid question, but Why can't the border be solid?

**Comment by Feichtmeier** [comment]
this may fix the problem of the "two" parts of the border, but as far as I can see this, the border is added on top of the window and is not part of the window
But maybe we could fix this for server side decoration applications (the ones that look a bit oldschool and don't use the header bars [client side decorations])
Buuuut then the question may arise, why the border is only in the CSD applications :man_shrugging: 
I'd say the best is to remove it again

**Comment by madsrh** [comment]
> I'd say the best is to remove it again

Sad but true _(unintentional song title quote)_
