### ISSUE TITLE
Problem with drop target in Nautilus

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gtk-communitheme#605]
Not sure if already known bug.
If I try to drag&drop a file onto a tab in Nautilus there's a rectangle with green border indicating I can drop it here. The problem I see is that rectangle partially covers the close icon in the tab. 
Please see the screenshot:
![zrzut ekranu z 2018-07-04 11-56-11](https://user-images.githubusercontent.com/1629120/42294501-314b1d82-7fd9-11e8-8325-87f39c33770c.png)

**Comment by madsrh** [comment]
Wow, good spotted @mivoligo 👍 

It's not a known but, so thank you for opening this issue!

**Comment by mivoligo** [comment]
No problem. I had not much time recently to keep up with the project or submit any bugs. But I see you guys keep doing great work! Many thanks for that! :1st_place_medal:

**Comment by clobrano** [comment]
I need to investigate a bit more, but I am afraid this would be an upstream bug. The "problem" is that when the drag&drop reaches the tab, it is not the tab that changes state to drop-active, but a box inside the tab that does not fully contain the close button, so when the green box-shadow is drawn cause the error

btw, that green is terrible
