### ISSUE TITLE
Flat GTK color picker selection

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#611]
#MoreHairSplitting
The selection in GTK color picker has a highlight at the top and a shadow at the bottom. Could we make it flat? 

![image](https://user-images.githubusercontent.com/3986894/42402759-2700a6bc-817d-11e8-8b84-0526790c22aa.png)

I'm not sure I understand the rounded corners. I really prefer this non-rounded style seen in Arc, but maybe it would be best to follow upstream here 🤷‍♂️ 

Arc:
![image](https://user-images.githubusercontent.com/3986894/42402920-0354fd2a-817e-11e8-8e4e-eda125a188b4.png)

**Comment by clobrano** [comment]
How would you like the selection to be instead? The arc version is very subtle in this

**Comment by madsrh** [comment]
> How would you like the selection to be instead? The arc version is very subtle in this

A border, like Arc but less subtle (I'm on my phone so can't post mockups atm)

**Comment by Feichtmeier** [comment]
I link this one into here:
https://github.com/ubuntu/gtk-communitheme/issues/552
And close 552
