### ISSUE TITLE
Gray text for non-selected apps in Alt-TAB switcher

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gtk-communitheme#612]
As mentioned [here](https://github.com/ubuntu/gnome-shell-communitheme/issues/113#issuecomment-382544386)

> The text of non selected/hovered applications might also be slightly less white...

![image](https://user-images.githubusercontent.com/3986894/42403418-56bc477c-8181-11e8-9aa9-aa6f19657b5a.png)

This is the current --edge: (you can see that the arrows already does this)
![peek 2018-07-06 15-51](https://user-images.githubusercontent.com/3986894/42403447-1ca4818a-8136-11e8-89bc-0c3540ff5fcc.gif)

**Comment by Feichtmeier** [comment]
30% darker fg_color
![peek 2018-07-07 08-32](https://user-images.githubusercontent.com/15329494/42407642-5a8328be-81c0-11e8-9470-0a4dbb174978.gif)

Lighter or darker or ok like this? @madsrh

**Comment by madsrh** [comment]
Perfect! Please merge 😁
