### ISSUE TITLE
Add Blur effect for Dock

### ISSUE THREAD

**Issue by dattrn** [ubuntu/gtk-communitheme#620]
I think that the ubuntu's dock will be more attractive and good looking by this change.
![image](https://user-images.githubusercontent.com/18400469/42557003-7e6beca2-8517-11e8-8611-e09d87f1266d.png)

![image](https://user-images.githubusercontent.com/18400469/42557340-711caaae-8518-11e8-90c9-5c0af99f517c.png)

**Comment by Feichtmeier** [comment]
Yes we would love that too.
Sadly this is not possible with the current gnome shell.
Best regards and thanks for reporting issues
