### ISSUE TITLE
Not showing all tray icons

### ISSUE THREAD

**Issue by Alculete** [Ubuntu/gtk-communitheme#64]
when using tray icon not all tray icons of installed app appear. I have skype and dropbox installed and only appear if I'm using ubuntu section and not communitheme section

**Comment by clobrano** [comment]
Hi @Alculete, thanks for reporting this. I can not reproduce this issue, could you tell us

- what do you mean by ubuntu section/communitheme section
- how did you installed communitheme?

Thanks a lot!

**Comment by godlyranchdressing** [comment]
@Alculete if you have GNOME Tweaks installed, you can go into the Extensions section and turn on/check to make sure that the "Ubuntu appindicators" extension is turned on. The tray icons in the default Ubuntu session is the result of a turned on extension. The Communitheme session is a default GNOME session (other than the theme) so it probably isn't turned on.

Thanks for testing.

**Comment by galgalesh** [comment]
@Alculette
I believe you mean the "Communitheme Session" that you choose when you login?

Can you give a screenshot/list of all the installed extensions? Are you using 17.10 (latest Ubuntu release) or 18.04 (beta/daily Ubuntu build)?

**Comment by Alculete** [comment]
Yes @galgalesh is the Communitheme Session.
screenshot below

![image](https://user-images.githubusercontent.com/2129497/35001507-94ebdb7a-faef-11e7-8a8e-b8f6575b62a2.png)

**Comment by clobrano** [comment]
Removing this here and reporting everything to the other issue in gnome-shell-communitheme
