### ISSUE TITLE
In Firefox search entry borders are not completely highlighted

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#66]
![image](https://user-images.githubusercontent.com/2883614/34980702-8c177a26-faa5-11e7-970c-38228e300679.png)

**Comment by godlyranchdressing** [comment]
I think there probably isn't anything we can do but make text entries look like Firefox's. Firefox seems to pull a couple colors from themes and that's about it (even Chrome does more than that).

**Comment by clobrano** [comment]
In Ambiance entries partially highlighted have been considered a bug (fixed), so I don't think that make everything like Firefox would be accepted. Better keep things as they are now and if/when possible will fix Firefox too.

**Comment by clobrano** [comment]
closing this since it does not depend from theme
