### ISSUE TITLE
Toolitem entry highlight goes out of border to the next widget

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#68]
![image](https://user-images.githubusercontent.com/2883614/34996552-41c05a30-fada-11e7-8570-dcc2972e02d9.png)

Not sure it is the best description, so I took a picture. This happen in Document Viewer, on top-left widget

**Comment by godlyranchdressing** [comment]
Most likely a result of unlinking headerbar elements so the buttons can be flat (to fix the problem with GNOME Dictionary's linked button and entry field). I didn't think an entry would be linked to an entry, though, that's the problem there. 

I think I know how to fix it, but rogue issues like this might still pop up. Even though I'm liking the flat headerbar buttons more than I thought I would, I say we just go back to linked headerbar buttons not being flat to avoid this trouble, but we should hear what Mads and Stefan have to say first.

**Comment by clobrano** [comment]
If there is no way to fix it everywhere, we should consider that gnome-dictionary is less used than document viewer

**Comment by galgalesh** [comment]
Also consider that application developers specifically opted to link two elements. I think the theme should respect that decision..

I really like this btw:

![image](https://user-images.githubusercontent.com/1492981/35097576-ffb09d6c-fc50-11e7-896b-fa65b7170a21.png)

Still semi-flat but the association is more clear. Is it possible to do something similar for linked elements? (sorry if I'm asking/proposing stuff that is already discussed)
