### ISSUE TITLE
horizonal linked button first child shrinks when hover or backdrop

### ISSUE THREAD

**Issue by clobrano** [Ubuntu/gtk-communitheme#69]
![horizontal-linked-button-shrinks](https://user-images.githubusercontent.com/2883614/35002495-2260d5f6-faea-11e7-840d-31fa227498f5.gif)

**Comment by godlyranchdressing** [comment]
What program is that in the gif? Removing that line seems to result in a double border problem for linked elements. 

![image](https://user-images.githubusercontent.com/27529229/35003365-01201d42-fac3-11e7-81fb-51973fbf63dd.png)

**Comment by clobrano** [comment]
Its the headerbar demo in gtk3-demo

**Comment by clobrano** [comment]
I'm working on an improvement

**Comment by clobrano** [comment]
It should look better now

![fix-double-border](https://user-images.githubusercontent.com/2883614/35044846-211b92f0-fb92-11e7-880b-0d56a2fcca48.gif)

**Comment by godlyranchdressing** [comment]
I think I found the problem. A workaround was made for the issue in gtk3-demo (linked headerbar buttons not having the right amount of borders), but the selector wasn't specific enough for it to work in the gtk3-demo and probably other programs, too.

Changing line #1570 from

`.linked button, .linked button.image-button, .linked entry {` 

to

`.horizontal.linked button, .horizontal.linked button.image-button, .horizontal.linked entry {`

Resolves the issue without modifying %linked_middle. There shouldn't be any vertically linked buttons in headerbars so this _should_ be foolproof. I'll see if I can tidy up the solution for flat linked elements. I've noticed that the margin between them can be a little too much, too.

**Comment by clobrano** [comment]
@godlyranchdressing I only wonder why %linked_middle should style only the right border style. It would make much more sense to me to move this on a &:first-child target

**Comment by godlyranchdressing** [comment]
@clobrano It's been a while since I realized how it all makes sense, but buttons linked to entries and linked toolbar buttons seem to be handled differently from combobox buttons which are also linked. Or something like that. So modifying %linked_middle can mess up comboboxes but not regular linked buttons.

**Comment by clobrano** [comment]
Alright, let me try only what you suggested then

**Comment by clobrano** [comment]
Line #1570 was slightly different, but the suggested fix seems to work as well :+1:
