### ISSUE TITLE
Menubar items should use a darker text color

### ISSUE THREAD

**Issue by godlyranchdressing** [Ubuntu/gtk-communitheme#74]
A new $headerbar_text_color should be used instead of the standard headerbar text color.

**Comment by clobrano** [comment]
@godlyranchdressing could you provide a picture of such a menubar item?

**Comment by godlyranchdressing** [comment]
I don't know how we're going to handle the text colors till I sift through the new stuff posted by Canonical and get some ideas though. The checkboxes might get overridden when I'm updating them to match Canonical's, so maybe this will need to be put on hold till that stuff is organized.

![4293a01aa7a39a0aee46f3ebb5e66fe733aac944](https://user-images.githubusercontent.com/27529229/35154088-3abd23f4-fcff-11e7-991b-f52ba5f0bbea.png)

(Better inactive text colors here from Mads' mockup) ---
![3865ea04fc9d1d12670262958f64cf00bbe15ddc](https://user-images.githubusercontent.com/27529229/35154089-3add27da-fcff-11e7-93ad-c3b66ef33d6c.gif)

A transition would make the text color change more obvious.

**Comment by madsrh** [comment]
A quick contrast test with the Canonical colors:
![colors](https://user-images.githubusercontent.com/3986894/35183130-3043be82-fde1-11e7-8693-b5c32e3a6106.jpg)

**Comment by godlyranchdressing** [comment]
@madsrh is that title/subtitle/caption or active/disabled/backdrop?

**Comment by madsrh** [comment]
@godlyranchdressing it's a bit unclear [here](https://github.com/CanonicalLtd/desktop-design/blob/master/Colour/colour.png) and also page [13 in Colour in the toolkit](https://docs.google.com/presentation/d/1FtHFW67ycl6uvxZqKIZwyinVyOuV9NxXDuJv1SwQ70k/edit#slide=id.g13b3c671fc_1_0)
