### ISSUE TITLE
Inline progress bars (inside GtkTreeView) are orange instead of green

### ISSUE THREAD

**Issue by fitojb** [Ubuntu/gtk-communitheme#9]
This is an inconsistency with regular progress bars, which are green, a much better color.

See this Synaptic screenshot:

![captura de pantalla_2018-01-01_15-19-32](https://user-images.githubusercontent.com/554953/34471253-d3dda76a-ef09-11e7-94cc-baa3d3eb0644.png)

**Comment by galgalesh** [comment]
This has been fixed, thanks for reporting!
