### ISSUE TITLE
Change terminal colors back to Ubuntu style 

### ISSUE THREAD

**Issue by Luxamman** [Ubuntu/gtk-communitheme#90]
Like already discussed, change the terminal colors back to the typical Ubuntu style, as it is a too big part of branding and recognition value.

**Comment by kq01526** [comment]
It's already being discussed in: https://github.com/Ubuntu/gtk-communitheme/issues/29

**Comment by clobrano** [comment]
> It's already being discussed in: #29

Right, we didn't indicate to which previous discussion we were talking about. thanks!
