### ISSUE TITLE
Slider handle transparency on non focus windows 

### ISSUE THREAD

**Issue by Luxamman** [ubuntu/gtk-communitheme#91]
When a window is not in focus including a slider with a handle, the handle is getting transparent and the indicator line shines through. 

![virtualbox_ubuntu1804_23_01_2018_15_12_16](https://user-images.githubusercontent.com/20417555/35280269-f514b17e-004f-11e8-80ab-57af84806c48.png)

**Comment by clobrano** [comment]
closed by #224
