### ISSUE TITLE
App launcher searchfield border is too thick

### ISSUE THREAD

**Issue by madsrh** [Ubuntu/gtk-communitheme#96]
The App Launcher searchfield should match other searchfields like Nautilus. 1 px border and less border-radius. Perhaps also white background?

![screenshot-from-2018-01-23-07-22-52-recovered](https://user-images.githubusercontent.com/3986894/35301974-5501ca1c-008d-11e8-87b9-cbfbc2fb47fe.gif)

**Comment by godlyranchdressing** [comment]
I made a [pull request](https://github.com/Ubuntu/gnome-shell-communitheme/pull/28). The orange border color is barely visible with a white background, though, so I kept it black for now.

**Comment by didrocks** [comment]
As the screen turns basically dark when entering the activities views, I would say keep it black with the white text on top. The focus makes it visibles IMHO, but I may be wrong. Thoughts?

**Comment by galgalesh** [comment]
+1 for keeping it black, it's also consistent with all the other shell stuff (like notification drawer and calendar etc..)

**Comment by madsrh** [comment]
> I made a pull request. <

The white was just a thought ;) I'm perfectly happy with a 1px border.

> +1 for keeping it dark, it's also consistent with all the other shell stuff (like notification drawer and calendar etc..) <

+1 for dark. The searchfield background looks black to me (maybe it's because of the wallpaper) and not semi transparent like other shell stuff.
