### ISSUE TITLE
Checkboxes and radio buttons design change

### ISSUE THREAD

**Issue by Luxamman** [Ubuntu/gtk-communitheme#97]
Change design to full color like the right ones:
![radio](https://user-images.githubusercontent.com/20417555/35328635-4dff79d8-00fd-11e8-91eb-da6c935bd2eb.png)

**Comment by clobrano** [comment]
Is this still relevant considering @madsrh comment [here](https://github.com/Ubuntu/gtk-communitheme/issues/162#issuecomment-365567805)? Canonical's design consider a different styling for checkboxes inside lists and menus

**Comment by madsrh** [comment]
+1 for following the Cannonical design again :D

**Comment by clobrano** [comment]
yeah @madsrh sorry 😄 I needed to clarify. Again 😄
