### ISSUE TITLE
Click button color darker

### ISSUE THREAD

**Issue by Luxamman** [Ubuntu/gtk-communitheme#98]
Make the color on clicked buttons darker to have more contrast between the clicked button color and the dark header bar.
![virtualbox_ubuntu1804_23_01_2018_15_15_22](https://user-images.githubusercontent.com/20417555/35328830-f0fa6e86-00fd-11e8-813f-67117780d08c.png)

**Comment by madsrh** [comment]
Perhaps the very light background works best? I'll add my mockup:

![image](https://user-images.githubusercontent.com/3986894/35331716-a80b6698-0108-11e8-844b-113cc1bacb38.png)
